### ISSUE TITLE
installation doc addition

### ISSUE THREAD

**Issue by buuhsmead** [magneticio/vamp#10]
The documentation mention at option3 a POST to mesos. If you have never worked with mesos you have no idea what to do.
Maybe a sample command can be added to get going with the 'berry-test / xbox-test':
curl -v -H "Content-Type: application/json" -X POST -d @vamp.json http://localhost:8080/v2/apps
and vamp,json is the proposed

**Comment by tnolet** [comment]
@buuhsmead You're absolutely right. We're doing an update of the docs tomorrow. Thanks for the heads up.

**Comment by tnolet** [comment]
Is now part of installation docs.
