### ISSUE TITLE
event based workflows on DC/OS with Metronome not working due to Docker version

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#1018]
Workflows are triggered based on events, but the workflows execution as a Metronome job fails.
This is due to the use of the new `docker container run` instead of the older `docker run`

magneticio/vamp: katana 
Docker image hash: cd4756db3e94 
DC/OS 1.9.0 and 1.9.1

fix would be to remove to "container" stanza from 

https://github.com/magneticio/vamp/commit/db1c1950692cec11e902a2133046e544565f24f9#diff-8934c38493f5f3615aaf3f5e3115733dR146

Reading the docker docs seem to note that `docker run` is not going to be deprecated any time soon

**Comment by tnolet** [comment]
@mihaiSimu I get another error now. I'm using the last katana container with  The `--network` flag is not populated

This is the metronome log
```
I0828 10:42:05.967108     5 exec.cpp:162] Version: 1.2.1
I0828 10:42:05.972143     7 exec.cpp:237] Executor registered on agent 6da75b69-f109-45e1-85bc-27174012bc97-S1
flag provided but not defined: --network
See 'docker run --help'.
```

**Comment by olafmol** [comment]
might be related to #1024

**Comment by olafmol** [comment]
@tnolet can you close the issue if this works correct now? tnx!
