### ISSUE TITLE
Support Elasticsearch 5.6

### ISSUE THREAD

**Issue by jason-magnetic-io** [magneticio/vamp#1030]
**Goal:**
Support Elasticsearch 5.6

**Considerations:**
- There are a number of [breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-5.0.html) between 2.x and 5.x
- There are additional minor changes between 5.0 and 5.6

Created from Aha! https://magneticio.aha.io/features/VAMPEE-6-1

**Comment by jason-magnetic-io** [comment]
Related to magnetic/elastic#3

**Comment by jason-magnetic-io** [comment]
The quickstart runs OK but I now see these warnings in the logs.

`[o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [type]`

`[o.e.d.r.RestController   ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.`

**Comment by jason-magnetic-io** [comment]
Health and metrics are not showing correctly. 

Version: 0.9.5-1244-g65eb0c73
UI Version: 0.9.5-22-g27b1446

**Comment by mihaiSimu** [comment]
vamp-node-client (for the javascript workflows), vamp-docker-images, elastic repositories have been updated to work with ES 5.5.2. Closing this.
