### ISSUE TITLE
Vamp running on docker - which docker version is supported?

### ISSUE THREAD

**Issue by bernieatenovlab** [magneticio/vamp#1039]
The documentation says vamp can run on "Linux: Docker 1.9.x (Vamp works with Docker 1.12 too)" (from https://vamp.io/documentation/installation/v0.9.5/hello-world/). 

When I look at https://docs.docker.com/release-notes/ I see they're at version 17.09. 

When I install docker on an AWS AMI, the version is 
ec2-user@ip-10-3-1-184 ~]$ docker --version
Docker version 17.03.2-ce, build 7392c3b/17.03.2-ce

Is the Vamp documentation correct in saying it supports version 1.9? Shouldn't the version be much higher?

**Comment by jason-magnetic-io** [comment]
@bernieatenovlab Thanks for reaching out. "Linux: Docker 1.9.x (Vamp works with Docker 1.12 too)" is a hangover from a previous release note. 

I can confirm the Vamp definitely works with Docker version 17. We currently test it against 17.06.2-ce during development.
