### ISSUE TITLE
Rest endpoint does not return 404 when Content-Type application/x-yaml

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#104]
I want to perform a GET request at the breeds endpoint for a non-existing breed.
I expect to get a `404`, since the resource can not be found.

With the headers `Content-Type` & `Accept` set to `application/json`, the response is:
`404`  - `The requested resource could not be found.`

With the headers `Content-Type` & `Accept` set to `application/x-yaml`, the response is:
`200` - `!!map 'null'`

I did not check if this is also the case for other endpoints.

**Comment by dragoslav** [comment]
Good find!
