### ISSUE TITLE
Remove WebSocket connectivity except for streaming data

### ISSUE THREAD

**Issue by mihaiSimu** [magneticio/vamp#1042]
The backend has duplicated APIs written with WebSockets and HTTP(S).

The socket-connectivity fails in some cases and user is given a message indicating that the backend as unavailable. This can happen frequently enough to make the UI unusable.

The socket connectivity was introduced for streamed data however in most places we've come to realize that HTTP(S) is enough. Maintaining HTTP(S) and WebSockets also increases the potential threat surface.

We should only leave WebSockets in places where we actually use streamed data.

**Comment by olafmol** [comment]
fixed in Vamp EE
