### ISSUE TITLE
Remove PersistenceMultiplexer and refactor PersistenceActor

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#1043]
## Intro

In general artifacts are managed via API endpoints and by internal Vamp engine. For example a deployment can be created and updated by an end user, however some properties are set by Vamp: instance hosts/ports, evaluated environment values etc. In order to avoid data collisions and race conditions, artifacts are internally (low level) treated as set of fragments (patches) that combined form "end-artifacts" (seen via endpoint API).

## Phase 1 (past) 

KV and Elasticsearch were used for data storage. On each read, fragments are assembled (no in memory cache) - this is sole purpose of PersistenceMultiplexer.
Advantage of this was to use existing 3rd parties (KV/ES) without introducing additional dependencies ("real" DB), also it was easy to add new fragments as it was needed (new features etc.)
Disadvantage a part of not using "real" DB, was that this is not optimal solution - each endpoint read required additional internal read requests to KV/ES.

## Phase 2 (now)

KV/ES are abandoned in favor of DB servers. Current approach is using event-sourcing: all modification (write/delete) requests are persisted in event/data log and Vamp keeps an internal data representation (aggregate) in memory. However, there is still PersistenceMultiplexer to assemble fragments. 

## Phase 3

PersistenceMultiplexer can be removed - there is no need to assemble fragments on read, but on write. Once requests are persisted to the data/event log, internal data representation should be updated in such way that fragments are assembled immediately - for instance host/port update should be applied directly to corresponding deployment artifact, later when this deployment is read it is already "complete". Important thing is that this **MUST** be thread safe. Updating PersistenceActor this can be achieved - basically using thread safeness of Akka actors itself.

**Comment by olafmol** [comment]
fixed in Vamp EE
