### ISSUE TITLE
User-agent strings with special characters in route conditions are interpreted as ACL's

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#1056]
when f.e. setting "User-agent=Mozilla/5.0 Macintosh" Vamp should enter:

```
hdr_sub(user-agent) Mozilla/5.0\ Macintosh
```
in the VGA haproxy config

(see here for escape rules: https://serverfault.com/questions/804733/format-for-hdr-sub-pattern-matching/804892)

But Vamp interprets this as an ACL rule and uses this "as-is" and enters: 

```
User-Agent =  Mozilla/5.0 Macintosh
```
which doesn't work.

**Comment by olafmol** [comment]
Additionally, we found another issue and a fix for it. 

With a typical modern user-agent string there is a comma in it, which makes HAproxy break it up in 2 parts:

http://www.serverphorums.com/read.php?10,856179

The solution is not to use hdr_sub but to use req_fhdr and of course escape the user-agent string correctly.

Proposed behaviour: if we enter "user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14" in the condition field (either in UI or to API) the end result in our VGA should be:

req.fhdr(User-Agent) -m str Mozilla/5.0\ (Macintosh;\ Intel\ Mac\ OS\ X\ 10_10_5)\ AppleWebKit/602.2.14\ (KHTML,\ like\ Gecko)\ Version/10.0.1\ Safari/602.2.14

**Comment by dragoslav** [comment]
https://github.com/magneticio/vamp/pull/1091/commits/cf65a88e58c7b508b997ad3ddde9fe99cafd2963
A part of using `req.fhdr(...) -m sub` by default, also values with space/comma are supported - however you need to surround them by single or double quotes, e.g.: `user-agent = 'Mozilla/5.0 (Macintosh'` or `user-agent = "Mozilla/5.0 (Macintosh"`.
