### ISSUE TITLE
Cannot delete a deployment when it's in deploying state

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#1069]
sometimes deploying never finishes because of f.e. lack of resources or a incorrect network-setting. It's currently not possible to stop/delete the deployment when it's in deploying state. Vamp reports that the deployment was succesfully deleted but it stays active and in deploying state.

**Comment by cristifilip** [comment]
tested from `magneticio/vamp-ee:katana` on Chrome & Safari & FF

**Comment by cristifilip** [comment]
Change was done in `vamp-ui` 58a4285
