### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by bench87** [magneticio/vamp#1108]
I ran vamp with DC/OS Marathon and I deployed 14 apps

1. open vamp UI http://hosts/service/vamp/#/vamp/deployments
2. keep refresh web site
vamp container Memory usage is increasing 

finally when vamp memory usage 100% (docker stats) vamp is sooooooo slow

**Comment by bench87** [comment]
@olafmol I think, if I use 0.5.5.6-dcos memory usage increase but after minute it decreased memory usage, but 0.5.5-dcos never decrease memory usage...

**Comment by olafmol** [comment]
What version of DC/OS are you running, and what are the memory allocation settings for the Vamp container? tnx! Can you give some metrics on the number of active deployments, gateways, services/breeds inside them etc?

**Comment by bench87** [comment]
@olafmol I use DC/OS 1.9.5

**Comment by olafmol** [comment]
tnx @bench87 can you describe the number and size (ie number of services, breeds, gateways, routes etc.) of your running deployments?

**Comment by bench87** [comment]
@olafmol I think when vamp disconnected with jookeeper, Memory usage increases.

**Comment by bench87** [comment]
@olafmol I resolved this issue by add java option in vamp exe file
like blow
```
java ${JVM_OPT} \
     -Dlogback.configurationFile=${LOG_CONFIG} \
     -Dconfig.file=${APP_CONFIG} \
     -cp "/usr/local/vamp/bin/*:/usr/local/vamp/bin/lib/*" \
     io.vamp.bootstrap.Boot
```

I know you have fixed it already in latest version...

**Comment by olafmol** [comment]
tnx!
