### ISSUE TITLE
Additional distribution formats for Vamp releases

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#115]
Vamp is currently shipped in two packaging formats:
- Docker images
- Fat Jar files

For ease of deployment, shipping Vamp in additional formats is something we should consider. Formats which come to mind are:
- .deb (debian / ubuntu)
- .rpm (redhat)
- .dmg (osx)

There is a sbt plugin, which could be essential for this task:
http://www.scala-sbt.org/sbt-native-packager/gettingstarted.html#packaging-formats

Especially the java-server archetype looks very promising:
http://www.scala-sbt.org/sbt-native-packager/archetypes/java_server/

**Comment by tnolet** [comment]
duplicate. Closing mine, yours is more complete: https://github.com/magneticio/vamp/issues/108
