### ISSUE TITLE
/api/v1/info endpoint returns 500

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#118]
In my setup, the network segment where vamp-router & marathon are located, is not reachable.
The collection of info from router & container-driver times out.

The info endpoint return a HTTP 500, instead of a partial populated info blob.

**Comment by tnolet** [comment]
this is fixed. Info page returns a neat message.

**Comment by dragoslav** [comment]
Did you check with connection (future) timeout? I have reproduced it.

**Comment by tnolet** [comment]
No idea...I just loaded the info page on the last developer build and all was fine when I wasn't running pulse or router.

**Comment by dragoslav** [comment]
It works in that case, also if connection can't be established (e.g. no pulse running), otherwise you get the problem.
