### ISSUE TITLE
Router changes too early during deployment

### ISSUE THREAD

**Issue by vlesierse** [magneticio/vamp#135]
When I update my deployment to the next version I see that the router already allows traffic to the new instance even when it isn't running yet (Staging in Mesos). Especially when the application is containerized it could take a minute to download the new version of an image (depending on the size of course), but during download it appears that the Vamp router allows traffic to the endpoint which result in `503 Service Unavailable`

Shouldn't Vamp have to wait until he knows for sure that the service is running and can receive traffic?

**Comment by tnolet** [comment]
Hi,

you are correct. We had a feature planned already for release 0.6.0 but had to take it out. We will move this up and release it before beta. The issue is in our private repo but we'll move it up to here.

**Comment by vlesierse** [comment]
For now I will try to add an additional stage which deploys the new version with a routing weight of 0 for some time. Didn't tried it yet, but I hope it works.

**Comment by dragoslav** [comment]
Endpoint can be created only if all cluster services are deployed (even though the containerised application may not still be initialised/running).
