### ISSUE TITLE
Implement pagination in Pulse

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#139]
Related to #138

**Comment by dragoslav** [comment]
Only internal wiki update: https://github.com/magneticio/vamp-internal/wiki/Event-API#pagination
For public wiki we still need to make an update about Elasticsearch ranges (e.g. now-1d) etc.

**Comment by tnolet** [comment]
Will update the docs soon with a proper section on Event & Metrics. This is now somewhat overshadowed.
