### ISSUE TITLE
Collapse all the inspect, list & create commands into three commands

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#145]
Replace all the inspect-???? commands with a single inspect command

Current command | New command
-------------------------|---------------------
 `vamp inspect-breed mybreed` |  `vamp inspect breed mybreed`
 `vamp inspect-blueprint myblueprint` |  `vamp inspect blueprint myblueprint`

The same for the `create` commands 

The list commands are now scattered in the list of available commands. Combine the commands
`breeds`, `blueprints`, `deployments`, `escalations`, `filters`, `routings`, `scales` &, `slas` into a single list command: 

Current command | New command
-------------------------|---------------------
`vamp breeds` | `vamp list breeds`
`vamp filters` | `vamp list filters`

Rational: This makes the list of available commands a lot shorter and also makes the documentation easier (less cut&paste)

**Comment by tnolet** [comment]
yes. This would be better.
