### ISSUE TITLE
Build & test .deb packages for core, cli & pulse

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#147]
- Finish the core implementation in vamp-dist
- Add support for pulse
- Test all packages on a clean machine
- Use sane defaults for configuration - #144

Part of #115

**Comment by plamola** [comment]
Found the following issues:
* debian repo incorrected indexed; workaround by creating new temporary repos.
* logback.xml logs to stdout; should be a file
* vamp-core & vamp-pulse not running correctly as service / starting manual seems to work; needs further investigation
* vamp-core install could set the VAMP_HOST environment variable, so vamp-cli can run on machine without additional config/parameter

**Comment by plamola** [comment]
Communication with docker fails:
```log
06:53:29.769 | ERROR | io.vamp.common.notification.Notification | Container response error.
06:53:29.792 | ERROR | io.vamp.common.notification.Notification | http://localhost/containers/json
```

**Comment by plamola** [comment]
Tested on Ubuntu Trusty (upstart), Debian Wheezy (SystemV) & Debian Jessie (Systemd)

**Comment by tnolet** [comment]
awesome
