### ISSUE TITLE
Export as blueprint on deployment screen with hover to determine export type

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#154]
The export as blueprint link should:

- on click open up a new browser tab/window and call 'http://localhost:8080/api/v1/deployments/281fd129-1976-4837-abee-0ab88d3a897b?as_blueprint=true'. The export should per default be YAML, set with 'Accept: application/x-yaml' header
- on hover show a popover that allows the user to choose between JSON or YAML. This just flips the 'Accept' header to either application/x-yaml or application/json

**Comment by danielsneijers** [comment]
fixed
