### ISSUE TITLE
/reset does not remove all deployments when running the Docker driver

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#164]
This might be related to https://github.com/magneticio/vamp/issues/163 as it happens typically when trying to deploy a second blueprint and when the Docker driver "hangs"

**Comment by plamola** [comment]
After applying the fix for #163, I can not reproduce this issue.

**Comment by tnolet** [comment]
@plamola that was my hunch indeed. Looks like we squashed two bugs in one go!
