### ISSUE TITLE
Trying to access a non existing resource should report a proper error.

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#165]
When you access `http://vamp-local:8080/api/v1/deployments/6052cbf3-1731-430e-9888-4a6046379c5c`
and that deployment does not exist, you get the error:

```
{
"message": "The request content was malformed. Unexpected resource: 'deployments'."
}
```
This message has no relation to the actual flow of the user or what is normal in these situations. The message should report something like "no deployment found"

**Comment by dragoslav** [comment]
branch feature/0.7.8
