### ISSUE TITLE
Add undeploy command to CLI

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#166]
For development / CI purposes, the reset command, as present in the REST api, would be a good addition.

**Comment by dragoslav** [comment]
'reset' should be removed from the REST API once we have an UI.
In that case if you want to remove all deployments multiple requests would need to be executed (i.e. get all, remove one by one...). It's better if we use that approach in the CLI then to rely on direct REST call.

**Comment by dragoslav** [comment]
Also, maybe it would be good for dev purposes to have something like:

* reset pulse (requires Elasticsearch API calls for index/template deletion)
* reset deployments
* reset all (pulse, deployments, artifacts)

**Comment by plamola** [comment]
An `vamp undeploy <deployment name>` might be the better solution for replacing the reset functionality.

**Comment by tnolet** [comment]
yes, that is indeed better and mimics the ui
