### ISSUE TITLE
Vamp Workflows

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#168]
# Vamp Workflows

Workflow is an automated change of the running system/deployments. Scaling up or down based on metrics (e.g. SLA) is an example of the workflow. Workflow can be seen as a recipe or solution, however it has more generic meaning not just related to a "problematic" situation.
Another example is a workflow that will decide automatically if new version (canary release) should be accepted or not. For instance scale up to 50% of traffic for the new version, compare metrics over some time (e.g. frequency of 5xx errors, response time) , scale to 100% and remove the old version. This workflow can define the rate of the transition as well.

## Rationale

Workflows allow closing the feedback loop: deploy, measure, **react**.

Specifying workflows:

* DSL (e.g. SLA)
  * cheap - basically configuration update
  * limited power - needs a DSL support for common workflow types

* Scripting
  * a bit more expensive than DSL - requires programming skills not just simple configuration
  * more powerful than DSL - common API should be defined and JVM can support many different languages easily: JavaScript, Ruby, PHP, Groovy etc.

* External tools and applications
  * more expensive - tend to solve only a specific (complex) problem

* Manual human intervention
  * the most expensive

In order to get the best value for our costumers we should support things within DSL. Another level is scripting. Implementation is not complex and defining the execution hooks is relatively easy. This would allow experimentation with different features and if the feature is common and generic enough, it could be supported in DSL itself. Main goal is to automate deployments as much as possible which increases number of services handled by single operator (DevOps).

## Features

The main focus here should be on **scripting**:

* script managing in the similar way as other resources (REST API)
* execution of the scripts in specific context (deployment, cluster) on specific change (e.g. time, event)

## Implementation direction

* support for JavaScript - we can support later on many other languages
* linking scripts (import another)
* full access to REST and Event APIs (everything you could do with APIs you can with a script)
* providing execution context:
```
  var deployments = vamp.deployments()
  // do something with deployments

  var cluster = ...
  var responseTime = cluster.metrics("response_time", "now-10m")

  if(responseTime > maxResponseTime) {
    _.each(cluster.services, scaleUp)
    vamp.notification("scaling up...")
  }
  
``` 
* executing in a sandbox (no System.exit allowed)
* describing data expected by the script, e.g. in order to run it some deployment needs to passed to the script
* additional API like logging
* definition of hooks:
  * time (Cron like)
  * pre/post deployments, routes, server restarts etc.
  * generic (Elasticsearch) events - e.g. script execution can be triggered by creating an event (by Vamp or external party)

**Comment by dragoslav** [comment]
Internal wiki page: https://github.com/magneticio/vamp-internal/wiki/Workflow-API

**Comment by tnolet** [comment]
awesome! Could you add or reference the one with the staged deployment?
