### ISSUE TITLE
"Getting started" issues

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#171]
- on page 1. deploying your first blueprint there is a curl command that points to the wrong (mesos?) port: curl -v -X POST --data-binary @sava_1.0.yaml -H "Content-Type: application/x-yaml" http://192.168.59.103:8081/api/v1/deployments  >>> 8081 should be 8080

- On installation page i would suggest putting the "prerequisites" block first, it's easy to skip over the link in the first paragraph

- after successfully deploying the first sava 1.0 blueprint from the Sava github repo i get an error in the browser when trying to access the endpoint: 503 Service Unavailable, No server is available to handle this request.

**Comment by tnolet** [comment]
We have to add that boot2docker AND docker should be at 1.6.x release. This is luckily a very simple `boot2docker upgrade` command. Will fix the typos.
