### ISSUE TITLE
Delete request on REST API needs Content-Type set explicitly, unlike other methods

### ISSUE THREAD

**Issue by danielsneijers** [magneticio/vamp#172]
Deleting a deployment trough the API returns a 400 error, unless I explicitly set the Content-Type header. Example (simplified with the superagent js lib):

```javascript
// Works
function post(url, body) {
  return request
    .post(url)
    .send(body)
    .timeout(TIMEOUT);
};

// Works
function put(url, body) {
  return request
    .put(url)
    .send(body)
    .timeout(TIMEOUT);
};

// Doesn't work
function del(url,body) {
  if(body) {
    return request
      .del(url)
      .send(body)
      .timeout(TIMEOUT);
  } else {
    return request
      .del(url)
      .timeout(TIMEOUT);
  }

// Works
function del(url,body) {
  if(body) {
    return request
      .del(url)
      .set('Content-type', 'application/json')
      .send(body)
      .timeout(TIMEOUT);
  } else {
    return request
      .del(url)
      .timeout(TIMEOUT);
  }
};

**Comment by dragoslav** [comment]
@danielsneijers could you confirm that superagent doesn't set implicitly the "Content-Type" header for post/put? Didn't find any problem during testing with Postman - all requests without proper content type were rejected.

**Comment by danielsneijers** [comment]
Good call, it seems that superagent defaults POST/PUT request the 'Content-Type' header to 'application/json', but not for delete. Will close the issue.
