### ISSUE TITLE
Add http client to workflow API 

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#210]
The workflow engine should enable people to do http calls to external services (Jira, Pagerduty, etc.) using a simple, async http client. Javascript examples are [superagent](https://github.com/visionmedia/superagent), the node [request](https://github.com/request/request) or the jquery `$.get` apis. Problem is these libraries rely on XmlHTTPRequest or other DOM/Browser related API and therefore don't work on Nashorn. This means we cannot import them

**Comment by dragoslav** [comment]
Similar to [superagent](https://github.com/visionmedia/superagent) but synchronous.

- set header: set(name, value)
- set body: send(body)
- get request: get(url)
- post request: post(url)
- put request: put(url)
- delete request: delete(url)
- get response as string (end): string()
- get response as json (end): json()

```JavaScript
var breeds = http.get("http://localhost:8080/api/v1/breeds").json();
log.info(breeds);

# YAML

var breeds = http.set("Accept", "application/x-yaml").get("http://localhost:8080/api/v1/breeds").string();
log.info(breeds);

```

Note #217
