### ISSUE TITLE
Pulse should allow more fine grained queries for metrics and services for UI

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#216]
The UI implementation now has to do multiple backend calls and filter a lot of data to fill the deployment detail screen. This causes unnecessary roundtrips and race conditions on the frontend side.
We need to able to query multiple, specific metrics for one deployment or route, for example.

"get the response time and the current sessions for service x,y and z in deployment a"

Such a query could look like:
```
{
  "tags": ["routes:214615ec-d5e4-473e-a98e-8aa4998b16f4_frontend_8080","metrics:scur", "metrics:rtime","services:monarch_front:0.2","services:monarch_front:0.3"]
    "timestamp" : {
      "lte" : "now"
    }
}
```

**Comment by dragoslav** [comment]
better to have a separate metrics api for these things.

**Comment by dragoslav** [comment]
Once we have #284

**Comment by dragoslav** [comment]
Using new features from #284 is sufficient.
