### ISSUE TITLE
Core, Pulse and Router should report their version on the info endpoint

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#221]
This information is needed when debugging issue and can be easily visualized in the UI for easy reference by end users.

Implementation:

a JSON string directly under the "message" string, i.e.

```json
{
"message": "Hi, I'm Vamp! How are you?",
"version": "0.7.7"
}
```

**Comment by tnolet** [comment]
This is done for Router

**Comment by dragoslav** [comment]
It gets the version form the jar manifest, otherwise it's null (i.e. running from the IDE).
