### ISSUE TITLE
Synchronisation of host:port combinations for servers seems to not pick up port changes when a taks is rescheduled on Marathon

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#226]
We have a case where a task is scheduled to host with a specific host:port combination. However, the task fails and is rescheduled on the same or another host. During that restart/reschedule, Vamp does not pickup the newly assigned port.

**Comment by dragoslav** [comment]
Couldn't reproduce it with Marathon/Docker setup and since we didn't have this problem afterwards let's close it.
