### ISSUE TITLE
Save button does not collapse the input box after second usage on screen

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#229]
1. Have a blueprint in the list.
2. Delete it.
3. Add another blueprint using the Add button.
4. Press the save button.

The blueprint is added correctly but the input field is not collapsed.

**Comment by danielsneijers** [comment]
Fixed. The method watches the size of the blueprints list in the state of blueprintslist to check if new blueprints are added, and if so, closes the edit section. It didn't track deletions, so it didn't register additions after a blueprint was deleted. It does now
