### ISSUE TITLE
Kibana setup for Pulse events

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#23]

**Comment by tnolet** [comment]
This depends on this upgrade https://github.com/magneticio/vamp/issues/39

**Comment by tnolet** [comment]
depends on  https://github.com/magneticio/vamp/issues/79

**Comment by tnolet** [comment]
depends on https://github.com/magneticio/vamp/issues/133

**Comment by tnolet** [comment]
Kibana hook up is fine, search also, but plotting graphs is harder because our "value" field has multiple types. Kibana reports it as "conflict"

![settings_-_kibana_4](https://cloud.githubusercontent.com/assets/3802923/8058940/41299ebc-0ebd-11e5-919a-4adcc278bc66.png)

**Comment by dragoslav** [comment]
Yes, in general you can't index (or later even aggregate properly) values of different type/schema.
Instead of "vamp-*" try to use "vamp-router-metrics-*" (if type of router events is "router-metrics").
So you would basically use only events of certain type.
I guess the main problem is that Kibana creates another index, maybe we can specify value to be not indexed - the same approach we use for events without explicit type. This could be done using index templates.

**Comment by tnolet** [comment]
yes, this works! with "vamp-router-metrics-*" as the index pattern, you can draw graphs.
