### ISSUE TITLE
Unsupported Artifact when using "vamp create breed <NAME>  --file <some file>"

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#230]
I cannot create a breed with a name defined on the command line.

```
Tims-MacBook-Pro:scala-2.11 tim$ java -jar vamp-cli-0.7.7.aabb8a2.jar create breed monarch_front:0.2 --file br_template.yaml
ERROR: Unsupported artifact 'monarch_front:0.2'
```

Just using the --file option, without specifying the <NAME> parameter does work.

version is:
```
CLI version: 0.7.7.aabb8a2
```

**Comment by plamola** [comment]
Specifying a name on the command doesn't make much sense, since all the other properties of the artifact need to be read from file/stdin anyway. I'll remove the NAME parameter.
