### ISSUE TITLE
Create Breed does not overwrite an already existing breed but silently just keeps the one that is there

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#231]
Creating a breed using a file works OK. If I then change the contents of that file (i.e. add a dependency or something) and do the create again, I get back the breed that was already there from the previous create. This is not expected behaviour. The API just overwrites it. The CLI should either do this or prompt the user that that breed already exists or if he/she wants to overwrite it.

**Comment by plamola** [comment]
Seems like the API no longer overwrites an existing artifact; only a PUT command updates an artifact.
CLI has the same behaviour as the Rest API.

**Comment by zutherb** [comment]
When will version 0.7.9 publish. I have the same bug when updating a deployment.

**Comment by tnolet** [comment]
Lets stick to the common REST principles. POST creates, PUT updates a static artefact

@zutherb for deployment, always use PUT when updating.

**Comment by plamola** [comment]
Added an update command to the cli
