### ISSUE TITLE
"validate_only" parameters on /deployments (similar to a `noop` run)

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#233]
# "validate_only" parameter for /deployments

It should be possible for a user to validate if all references in a blueprint are available in Vamp before deploying a blueprint. This is now implicitly possible by deploying and waiting for errors. 

## Rationale

- helps building complex deployment with many references and dependencies.
- catches errors before users press the deploy button in the UI.
- gives feedback on references that might not be in place yet and should be provided by other teams.

## Features

A simple `?validate_only` option on POST-ing a blueprint to `/deployments`

**Comment by dragoslav** [comment]
deployment: create, update & delete.
