### ISSUE TITLE
Docker driver incompatible with Docker 1.7

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#241]
At this moment, the Tugboat driver probably does not support Docker 1.7 as it keeps throwing 'Empty head of list' errors. Downgrading to Docker 1.6 solves this.

We should consider ditching the Tugboat driver and using Maps for reading the JSON output from the daemon. We could reuse the socket and https connectivity.

**Comment by tnolet** [comment]
Some research shows the following:

A lot of options/fields have moved from the 'Config' object to the 'HostConfig' object in 1.7. We need to either update the case classes in tugboat, or use some kind of "easy failover" with regard to JSON marshalling and unmarshalling from the Docker daemon.


https://github.com/docker/docker/issues/14281

**Comment by plamola** [comment]
I'll upgrade the necessary code to support docker 1.7; there will not be any backwards compatibility, so once released, every Vamp install using the Docker driver needs to upgrade to Docker 1.7
