### ISSUE TITLE
RestClient.http with no 2xx response should return response body as well (e.g. custom Exception)

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#243]
In case of no 2xx we get the exception back with status code (e.g. 4xx) but not the body as well.
Implementing this will provide in most cases reason why call failed (e.g. validation failure).

**Comment by tnolet** [comment]
checkup the relevance of this issue

**Comment by dragoslav** [comment]
rest client: log.trace(code + body)
for security reasons (e.g. unintentional logging of passwords) only trace level
