### ISSUE TITLE
Proper style and layout for deployment detail screen

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#244]
The deployment detail screen needs CSS, styling and layout:

**general**
- all elements should be fixed on the grid
- all text elements should follow a uniform typography

**specific**
- bar graphs replaced with properly placed and colour coded area chart, see reference https://www.pinterest.com/pin/517702919638266733/

- servers array should be properly aligned (server + ip )
- indicator circle should size properly (now it splits in the middle)
- hover states are slightly random with regard to the background color.
- loose the `/` in the breadcrumb bar.
- use loader/spinner when getting metrics (same as undeploy button)

**Comment by danielsneijers** [comment]
all fixed
