### ISSUE TITLE
Get compressed artifact

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#25]
Return an artifact without the inline named artifacts. These should be replaced by references.

Anonymous inline artifacts can not be replaced with a reference and will remain in the sub tree.

This can be implemented as a layer on top of the current persistence implementation, which will strip down the result of the 'Get artifact(s)' call.

magneticio/vamp-internal#210

**Comment by dragoslav** [comment]
shrink=true

```
http://localhost:8080/api/v1/deployments?as_blueprint=true&shrink=true
```
