### ISSUE TITLE
Suggestion to use Hungarian notation for blueprint examples in documentation

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#251]
I noticed that in some blueprint examples in the online documentation the naming of clusters, breeds and/or deployables is exactly the same. This can be confusing, as in YAML the indention/closing of the structure is not very clear. My suggestion to solve this is to use Hungarian-style notation to explicitly use the type in the naming, f.e.: savaCluster, savaBreedA, saveService etc.

**Comment by tnolet** [comment]
We will look at making the descriptions clearer
