### ISSUE TITLE
After first edit, a second edit does not pop open the edit box anymore

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#259]
When editing and updating a breed or blueprint, you save the edit.
If you want to edit some other breed again, the edit box does not open.
When you navigate way to some other screen and return again, the editing is possible again.
Probably some boolean controlling the pop open is not reset correctly.

**Comment by danielsneijers** [comment]
fixed, there was a reference to the 'breedCreated' property instead of 'blueprintCreated' in the blueprintsList file, that broke the flow
