### ISSUE TITLE
Container driver for Docker

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#26]
For tests and showcase purposes, a container driver for Docker would make local deployment easier.
It would also prove that the design of Vamp can handle different container solutions.

The container driver can be specified in the application.conf:

`vamp.core.container-driver.type=`

**Comment by plamola** [comment]
At the end of milestone 0.7.5, the following functionality is still missing:
* Setting environment variables
* Handling the scale parameters correctly -> requires implementation of issue #56
* Reporting the status of the container when the name is hashed -> requires  implementation of issue #57
* Update an existing container

**Comment by plamola** [comment]
Feature branch needs to be merged into development

**Comment by dragoslav** [comment]
Retested with few examples:
* simple service with 1 and 2 instances scale
* A/B testing: 1 cluster, 2 services
* 2 service, 1 depend on another

Found few small issues, and finalised scale and update support.
