### ISSUE TITLE
"export as blueprint" should be "edit" button

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#263]
Going thru our tutorials with the UI, it makes way more sense to remove the "export as blueprint" button on the deployment detail screen and make it a proper "edit" button. The journey would be as follows:

- user clicks edit
- the text edit screen opens, exactly like the blueprint and breed edit screens
- user makes edits
- user presses save or cancel and is redirected back to the deployment details screen.

**Comment by danielsneijers** [comment]
fixed
