### ISSUE TITLE
Polling of deployment detail screen does update the filter list

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#265]
You can see the polling, but any updates done to the deployment using straight REST calls do not all show up in the screen. This seems to be only a problem in the filters list.

 A hard browser refresh fixes this.

**Comment by danielsneijers** [comment]
fixed

**Comment by tnolet** [comment]
This is issue is not fixed in 0.7.9 build. I can easily reproduce it.

**Comment by danielsneijers** [comment]
Must have missed something the last time, will look into it tomorrow!

**Comment by danielsneijers** [comment]
tested and fixed!
