### ISSUE TITLE
Create new debian repos

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#273]
The current magnetic-io debian repo contains a lot of test packages and is quite frankly, a mess. Instead of cleaning it up, it is more practical to start new repos, especially since we never announced the availability of the debian repo.

I suggest creating new 3 new debian repo's, one for each init system. 

Suggested names:
* upstart
* systemv
* systemd

Ubuntu 14.04 LTS user will use the upstart repo; Debian Wheezy will use systemv and Debian Jessie systemd. All other Linux flavours users will have to figure out which repo they have to use themselfs.

**Comment by tnolet** [comment]
@plamola yes, sound fine. What do I do?

**Comment by plamola** [comment]
1. Login @ bintray
2. Select magnetic-io organisation
3. Select `New Repository`
4. Enter name of repo: `upstart`
5. Select repository type `Debian`
6. Check box `GPG sign uploaded files ....`
7. Press `Create`
8. Repeat steps 3 - 7 with repo names `systemv` & `systemd`

**Comment by tnolet** [comment]
@plamola done!

**Comment by plamola** [comment]
Added packages; ready for vamp-dist run
