### ISSUE TITLE
Lintian check error on .deb-files 

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp#278]
Great that you are generating .deb-files now! I get a rather strange notification when installing the vamp-router using package manager under unbuntu:

The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.

Lintian check results for /home/josh/Downloads/vamp-router-0.7.9.1_amd64.deb:
E: vamp-router: arch-independent-package-contains-binary-or-object usr/share/vamp-router/vamp-router

**Comment by plamola** [comment]
Thank you for bringing this to our attention.

I know the .deb packages aren't perfect yet and will require some additional fine tuning.

Which version of Ubuntu are you using?

**Comment by plamola** [comment]
Released a new set of .deb packages for vamp-router, which got rid of this specific error:
```
E: vamp-router: arch-independent-package-contains-binary-or-object usr/share/vamp-router/vamp-router
```

Still got some other errors / warnings in lintian which need to be fixed -> #277

**Comment by JoshFalken** [comment]
@plamola Great, thanks! Just another random thought: I think it would be nice if you could just download a complete vamp-package with default settings and start this package to get the complete vamp-experience. That would be great if someone quickly wanted to try out vamp. The less someone has to search for settings, the sooner he/she will use it.

**Comment by plamola** [comment]
@JoshFalken For the 'quick try out', please check our new tutorials on http://vamp.io  
We have the [Docker quick start](http://vamp.io/documentation/installation/quick_start/), which only requires you to install docker/boot2docker and perform a `docker run` command.

The .deb & .rpm packages are aimed at actual doing a full install. Each component in the Vamp stack could be installed on a different machine, therefor we do not supply an 'all-in-one' package for installation.

Doing a `apt-get install vamp-router vamp-pulse vamp-core` would however also get you a fully configured Vamp stack, without the need to do any further configuration (assuming Java 8 & docker are already installed)

**Comment by JoshFalken** [comment]
@plamola new tutorials, nice! I had a lot of issues with getting the vamp docker image running under ubuntu. But that could also be caused by configuration errors on my side, not sure. But now I also see this tutorial: http://vamp.io/installation/ubuntu/ which almost is what I meant. Will be playing around with it some more.
