### ISSUE TITLE
Add an alias / tag to deployment

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#281]
In order to reference a certain deployment in integration scripts, it would be very handy to be able to use an `alias` and/or `tag`, instead of a *randomly* generated uid, which is different each time a blueprint is deployed.

If it is a deployment `alias`, is has to be unique; 
if it is a `tag`, multiple deployments with the same tag(s) can exists.  In that case, it would be up to the integration script to decide if it will take the first deployment found, of update them all.

In addition to the use case for CLI usage, displaying an `alias` instead of the deployment guid, would also make for a cleaner UI.

**Comment by olafmol** [comment]
@plamola could you describe the use-case behind tags? Alias is very clear, but tags is not clear for us right now.

**Comment by plamola** [comment]
With tags it would be possible to search for certain type of deployments. 
For example, all deployments on System Test environments or all deployments running on User Acceptance Test environments. This could be a feature in both the UI as well as the CLI.

Also, in the UI, it would be possible to create views, based on tags.

In MoSCoW speak:
I think the `alias` is a must have and `tag` a could have.

**Comment by olafmol** [comment]
tnx @plamola! Could you extend (maybe even in epic/story format) what you would like to achieve use-case wise with finding all deployments with a certain tag? I can imagine f.e. creating a filtered overview in the GUI and CLI using tags of specific deployments, for reference. Are there any more cases you envision?

**Comment by dragoslav** [comment]
`alias` we indeed need to have #437, while `tag` can be implemented as some pattern matching (not something in DSL). For instance `/deployments/?name=...`, e.g. `sava-1.0`, `sava-1.1` (aliases) could be matched with `?name=sava-*`
