### ISSUE TITLE
Add knobs library

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#283]
https://oncue.github.io/knobs/

Knobs is a configuration library for Scala. It is based on the Data.Configurator library for Haskell, but is extended in a number of ways to make it more useful.

In addition to the configuration options we currently have, we'll gain:
- Zookeeper support
- Dynamically reloading of configuration when it changes (must be explicitly enabled)
- An import directive allows the configuration of a complex application to be split across several smaller files, or to be shared across several applications. For example, placing the dictionary in a separate file.

**Comment by dragoslav** [comment]
Closing this as similar features are implemented in https://github.com/magneticio/vamp/issues/872 (no knobs but dynamic reloading, overriding etc.)
