### ISSUE TITLE
Edit service weights in clusters on the deployment detail screen

### ISSUE THREAD

**Issue by danielsneijers** [magneticio/vamp#286]
Users should be able to edit and distribute the weights of services in a cluster trough the UI. The idea is simple: range sliders should be used to increase or decrease the weight of a service. Increasing should automatically decrease the weights by ratio of other services in the cluster, and vice versa. It should also be possible to 'lock' a range slider so it will not increase or decrease while adjusting the other values.

The following steps should be made:

- UX proposal
- Prototype UX
- Implement code
- Test performance in different configurations
- Fine tune design

**Comment by danielsneijers** [comment]
When no data is received the stream should output 0 for reqs/sec. Now it stops sending and the UI shows the latest received number. If that is the desired back-end behaviour I'll have to manually set the value to 0 after a period of inactivity.

**Comment by tnolet** [comment]
@danielsneijers If you are asking a question with regard to solving a specific problem, please link someone into the question. I stumbled on this by accident.

Setting the value to zero is misleading. There should an indicator that data is not being updated. Like a timeout that fires and lets the user know that no fresh data is being received.
 This is strictly polishing, but if easy to implement would be nice.

**Comment by danielsneijers** [comment]
fixed, implemented a timeout after 5 seconds of inactivity
