### ISSUE TITLE
Very very very tiny error in http://vamp.io/installation/ubuntu/

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp#290]
I ran through the installation guide and encountered some small errors (great docs by the way):

- I didn't have to start the services, this was done automatically (at least on my ubuntu 14.04)
- small typo on 'install pulse' sudo apt-getinstall -y vamp-pulse (should include a space)

**Comment by plamola** [comment]
Good catch.

I've updated the documentation.
