### ISSUE TITLE
Some possible user stories

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp#292]
Some possible user stories that I thought of (and might go against the grain of Vamp or already be included in Vamp):

- As an administrator I want to use Vamp to enhance fault tolerance of my services. To this avail I want to define a group of backend services that run in one data center and a group of backend services that run in another data center. They are all contained in one blueprint (so the services part of the blueprint contains two groups) When one data center fails, the other group takes over.
- As an administrator I want Vamp to select the backend service based on historical response times thus balancing the load as optimal as possible. 
- As an administrator I want Vamp to select the best backend service based on the request and historical response times (so, in this case you select the best backend service for that specific request) 
- As an vamp administrator I want to have a possibilty to define a backend service to be down based on the response-body that is given (sometimes a 200 is given with a message in the body that the service isn't available)

**Comment by dragoslav** [comment]
Thank you for suggestions.
Features related to metrics can be addressed by workflows (yet to be announced):
https://github.com/magneticio/vamp/issues/168
https://github.com/magneticio/vamp/issues?utf8=%E2%9C%93&q=+is%3Aissue+label%3Aworkflows
General idea is to have closed feedback loop (i.e. react on deployment/traffic changes).

**Comment by JoshFalken** [comment]
@dragoslav: Cool, very curious to find out how these workflows are going to work! Is the possibility to determine that a backend service has failed based on content rather than on headers also included in a future version? Or is that one not yet on the roadmap?

**Comment by dragoslav** [comment]
For that situation there are few ideas/plans:
- workflows - you can check particular server response and do something afterwards (this can work even now)
- react directly on an event (workflow + Event API) - this requires some additional changes. Any log (e.g. custom log from you application) can trigger an event - plan is to test this using Logstash. So service could log something, Vamp is configured to react on specific custom event and then a workflow action is triggered.
- Vamp API for services - at the moment each service is just a black-box, we could add API so service could interact with Vamp and/or expose health/metrics directly to Vamp 
- Vamp Router could have more features including that one even though we aim to keep it simple (critical part of the system)

**Comment by JoshFalken** [comment]
@dragoslav thanks, looking forward to the documentation on workflows! Some thoughts regarding the Vamp API for services (I'm of course assuming I understand you correctly), I think that the most feasible possibility is that the backend service would provide an entry point that would deliver the needed information to Vamp. Not the other way around. My train of thought is that there usually firewalls in place that allow one application to initiate a request. If the service is outside the firewall (for instance, outside the company) there are security issues with allowing requests to come from outside. 

Furthermore, it's usually easier to build something that exposes the needed than connecting to the Vamp API during some intervals. And last but not least, not reaching the backend-metrics would be a surefire sign that the service is down. The other way around you never know. 

And the most beautiful solution (which is also the hardest) is somehow Vamp could learn what a good response was and act accordingly. Straight out of the box. That's not exactly keeping it simple but that would be the least amount of work from a user perspective. 

But these are just some thoughts.

**Comment by dragoslav** [comment]
Yes, Vamp would request from services health information, metrics etc. In this case services are not anymore black-boxes.

One of simpler use cases for Vamp to know/learn is canary release (similar to A/B testing).
Comparing metrics (e.g. response time, frequency of different response codes...) of different service versions, Vamp could automatically and gradually upgrade service to newer version (e.g. 1% -> 5% -> 10% ... 100% of traffic).

**Comment by JoshFalken** [comment]
@dragoslav: An automated canary release would be very cool. The main challenge is ensuring/checking functional correctness. And challenge is quite the understatement. 

On a side note: when Vamp is going to be used in production it is going to play a central part in accessing the backend services. How scalable is Vamp itself and how much can it prevent to become a single point of failure itself?

One solution I thought of was using Vamp itself to access another Vamp-instance but in my opinion this always leaves a single point of failure (the main Vamp). I don't know enough of the code so maybe it is possible to run two vamp instances that provide the same endpoints and the solution should come from another layer (somewhere in a netwerk component for instance).

**Comment by dragoslav** [comment]
1) Canary release
Vamp can't replace functional correctness, but more as an addition. Let's say you have an e-commerce application and in the new version home page is without footer. No one noticed that, clients don't mind (placing new orders as expected) so Vamp does automatic canary release. It's not good but not that bad either. Imagine now that new version passed all tests but no new order (or less than expected) after it's deployed - Vamp could detect this and reject this new release automatically (traffic back to 0).

2) Vamp as a single point of failure
Vamp is not production ready right now - Router is a single point of failure.
Vamp Core failure (in current implementation) will lead to eventual inconsistency - e.g. Marathon restarts some task but routes are not updated properly.
Plan is to have multiple Router instances running (as an example on different Marathon slaves) and these instances should be able to update routes if needed (e.g. Marathon restarted some task).
There are still some open questions related to implementation (multiple available options/paths we can follow).
Vamp core should be basically stateless - this is not the case mostly because of experimental features.
Work on production ready Vamp release should start in the near future (there is also another big feature https://github.com/magneticio/vamp/issues/167 which may be added before that).

**Comment by JoshFalken** [comment]
@dragoslav :
1) That's a very cool use of Vamp. As an addition it also opens the door for A/B/C/D/.../Z-testing. You deploy a number of versions of the homepage and let Vamp decide which versions has the highest number of orders (or which ever conversion-metric you use). 

2) Thanks for the clarification/explanation. I'm curious to see what the future of Vamp holds on this point.

**Comment by dragoslav** [comment]
Already covered by other issues.
