### ISSUE TITLE
Update weights using sockets first. fallback to reload HAproxy if necessary.

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#293]
HAproxy makes it possible to update weights and ACLS using the sockets. We are not using this now everywhere. This causes short hiccups in the metrics feed. Now the feeds are visualised, this is becoming a problem. 

we should:

- check with every route update if just weight and filters are updated.
- if so, use the socket to change them and also store it to the .json representation of the whole vamp-router state. (Render & Persist, just not update the haproxy proces)
- if not, use the normal update procedure.

**Comment by dragoslav** [comment]
Since 0.8.0 we don't use directly HAProxy statistics but process logs by ELK.
