### ISSUE TITLE
For new Sava images (golang) ports are not set when Docker driver is used

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#297]
With new Sava build docker driver doesn't get the server ports which results in unsuccessful deployment.
This behaviour is observed both before and after new dialect support.
It seems as an old issue related to EXPOSE.

**Comment by tnolet** [comment]
@dragoslav the ports are correctly exposed in the Dockerfile and supplied blueprints. The port has changed to 8080 however, where it was 80 first. We noticed however that if you specify 80 in the blueprint, you get errors in Vamp.
