### ISSUE TITLE
sudo restart service ... vs initctl restart ...

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp#299]
As I gather, the latest release uses upstart instead of services. The documentation (http://vamp.io/installation/ubuntu/) however states that you should use:

```sudo service restart vamp-*``` 

This doesn't work on Ubuntu 14.04. It should probably be: 

```sudo initctl restart vamp-*```

**Comment by plamola** [comment]
I'll verify and update the documentation if needed.

**Comment by tnolet** [comment]
Both options are valid. The correct usage of `service` is:

```bash
sudo service vamp-core restart
```

as noted in the docs. You can use the more basic `initictl` also. They trigger the same script.

**Comment by JoshFalken** [comment]
@tnolet: totally misread that one. There is a lot of debate on which one (service or initctl) is better, more Ubuntu-like and the like. Not really important, both work (just tested myself).
