### ISSUE TITLE
Implement JSON model deserializers/unmarshallers

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#3]
We marshall models to JSON using custom serilalizers, e.g. ignoring some fields, renaming (camelCase to snake_case). We should support backward process as well. This will allow easier implementation of our own or 3rd party REST API client applications.

**Comment by tnolet** [comment]
@dragoslav is this still relevant?

**Comment by dragoslav** [comment]
Not that much, since you can use available readers. It's just for a convenience.

**Comment by dragoslav** [comment]
@plamola is already using an approach for CLI, so if somebody wants to integrate there are available examples.
