### ISSUE TITLE
Docker driver wil not redeploy a container after killing it manually

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#303]
Steps to reproduce

* Deploy a container using Vamp, using the docker driver
* Kill the container via the docker CLI. e.g. `docker rm -f 5702ad8607ae`
* Vamp will instruct the docker driver to deploy it again
* The docker driver checks its internal cached list of containers and finds it.  
* Docker driver assumes the container is still there and won't redeploy it: `[DEPLOY] Container /vamp_498a9670-d508-49f1-a57d-9ad2b0e31c4e_wordpress already exists, no action`
* Vamp keeps trying for a while and finally gives up: `Deployment service error for deployment '498a9670-d508-49f1-a57d-9ad2b0e31c4e' and service 'wordpress'.`

**Comment by tnolet** [comment]
possible duplicate https://github.com/magneticio/vamp/issues/375

**Comment by dragoslav** [comment]
docker driver cache has been removed
