### ISSUE TITLE
Suggestion: check/fix the state of elasticsearch/H2 on startup

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp#304]
During the last week I had some hard crashes (not related to Vamp btw). One of these crashes left the elasticsearch-database in a corrupt state. I had to remove the database of elasticsearch (nodes/0) before it worked again. It would be nice if Vamp would run an consistency check/fix on elasticsearch on startup. I also managed to get an H2-database that was locked in a read-only state. 

I know that you're working on making Vamp more resilliant but I don't know whether or not this feature will be included in that update.

**Comment by tnolet** [comment]
Hi @JoshFalken, at this moment we consider using H2 and Elasticsearch in mem as non-production, one-off ways of doing simple tutorials.

I don't see a future where we would take on the burden of performing consistency checks here. The consistency has to be guarded by the JDBC solution or Elasticsearch itself. Doing that in Vamp would be hugely complex and cross the boundaries of separation between architecture layers a bit too much. Closing this issue for now.

**Comment by JoshFalken** [comment]
@tnolet: understandable.
