### ISSUE TITLE
Using the '@' symbol in a blueprint name makes it impossible to delete 

### ISSUE THREAD

**Issue by danielsneijers** [magneticio/vamp#310]
It might not be a common use case but when using the '@' symbol in a blueprint causes weird behaviour in VAMP. The blueprint will be accepted when created and is also deployable. The deployment works fine, I think because it wel get a hashed ID thus won't have the @ symbol in it's name. When trying to delete the blueprint it gives no error but fails silently. The log however shows this:

10:52:22.040 | ERROR | io.vamp.common.notification.Notification |                                          | Deployment service error for deployment '7ce37de2-f539-400e-9703-e622d2cef52b' and service 'sava:1.0.0'.
10:54:06.253 | ERROR | io.vamp.common.notification.Notification |                                          | Artifact cannot be found: '8d6cf846-39f5-44ee-be97-23423@'.
10:54:13.875 | INFO  | i.v.c.c.docker.DockerDriver              |                                          | docker delete app: /vamp_7ce37de2-f539-400e-9703-e622d2cef52b_6fd83b1fd01f7dd9eb7f
10:54:14.372 | INFO  | i.v.c.router_driver.DefaultRouterDriver  |                                          | router remove: 7ce37de2-f539-400e-9703-e622d2cef52b_9050
2015-08-11 10:54:14,384 CRIT reaped unknown pid 2587)
10:54:25.913 | ERROR | io.vamp.common.notification.Notification |                                          | Artifact cannot be found: '8d6cf846-39f5-44ee-be97-23423@'.
10:54:39.424 | ERROR | io.vamp.common.notification.Notification | akka://vamp-core/user/sla-actor$         | Artifact cannot be found: '8d6cf846-39f5-44ee-be97-23423@'.
10:54:54.330 | ERROR | io.vamp.common.notification.Notification |                                          | Artifact cannot be found: '8d6cf846-39f5-44ee-be97-23423@'.
10:55:56.677 | ERROR | io.vamp.common.notification.Notification |                                          | Artifact cannot be found: '8d6cf846-39f5-44ee-be97-23423@'.
10:56:06.927 | ERROR | io.vamp.common.notification.Notification |                                          | Artifact cannot be found: '8d6cf846-39f5-44ee-be97-23423@'.
10:57:17.790 | ERROR | io.vamp.common.notification.Notification |                                          | Artifact cannot be found: '8d6cf846-39f5-44ee-be97-23423@'.
10:57:21.267 | ERROR | io.vamp.common.notification.Notification |                                          | Artifact cannot be found: '8d6cf846-39f5-44ee-be97-23423@'.
10:58:21.500 | ERROR | io.vamp.common.notification.Notification |                                          | Artifact cannot be found: '8d6cf846-39f5-44ee-be97-23423@'.
10:58:43.032 | ERROR | io.vamp.common.notification.Notification |                                          | Artifact cannot be found: '8d6cf846-39f5-44ee-be97-23423@'.
10:59:52.445 | ERROR | io.vamp.common.notification.Notification |                                          | Artifact cannot be found: '8d6cf846-39f5-44ee-be97-2089168e2b87'.
11:00:13.775 | ERROR | io.vamp.common.notification.Notification |                                          | Artifact cannot be found: 'abda@'.
11:00:21.458 | ERROR | io.vamp.common.notification.Notification |                                          | Artifact cannot be found: 'abda@'.

**Comment by dragoslav** [comment]
@danielsneijers could you add the blueprint you have used?

I've tried the following: 
```YAML
name: dfd30787-92ee-4fb2-bd8a-0c051ac78554@
endpoints:
  sava@.port: '9050'
clusters:
  sava@:
    services:
    - breed:
        name: sava:1.0.0@
        deployable: docker://magneticio/sava:1.0.0
        ports:
          port: 8080/http
```
and indeed found a problem related to route name (too long) and according to the stack trace you gave it's not the same issue you had.

**Comment by danielsneijers** [comment]
I got the error by mashing on the numerical keys while holding shift. The blueprint below can be used to reproduce the error.

```
name: c5469eaf-2c4f-4b33-a815-f9b2961ac5fa@#$%@#$%
endpoints:
  frontend.port: 9040/http
clusters:
  frontend:
    services:
    - breed:
        name: monarch_front:0.1
        deployable: docker://magneticio/monarch:0.1
        ports:
          port: 8080/http
        environment_variables:
          backend[BACKEND]: http://$backend.host:$backend.ports.port/api/message
        constants: {}
        dependencies:
          backend:
            name: monarch_backend:0.1
      scale:
        cpu: 0.5
        memory: 256.0
        instances: 1
      routing:
        weight: 95
        filters:
        - condition: user-agent != ios
      dialects: {}
    - breed:
        name: monarch_front:0.2
        deployable: docker://magneticio/monarch:0.2
        ports:
          port: 8080/http
        environment_variables: {}
        constants: {}
        dependencies: {}
      scale:
        cpu: 0.5
        memory: 256.0
        instances: 1
      routing:
        weight: 5
        filters:
        - condition: user-agent != ios
      dialects: {}
    sla:
      type: response_time_sliding_window
      window:
        interval: 600
        cooldown: 600
      threshold:
        upper: 1000
        lower: 100
      escalations:
      - type: to_one
        escalations:
        - type: scale_instances
          target: backend
          minimum: 1
          maximum: 3
          scale_by: 1
        - type: scale_instances
          target: frontend
          minimum: 1
          maximum: 3
          scale_by: 1
    dialects: {}
  backend:
    services:
    - breed:
        name: monarch_backend:0.1
        deployable: docker://magneticio/monarch:0.2
        ports:
          port: 8080/http
        environment_variables: {}
        constants: {}
        dependencies: {}
      scale:
        cpu: 0.3
        memory: 512.0
        instances: 1
      routing:
        weight: 100
        filters: []
      dialects: {}
    dialects: {}
environment_variables:
  frontend.backend: http://$backend.host:$backend.ports.port/api/message

**Comment by dragoslav** [comment]
if you encode the blueprint name:
```
/api/v1/blueprints/c5469eaf-2c4f-4b33-a815-f9b2961ac5fa%40%23%24%25%40%23%24%25
```
and you get back the result (not an artifact not found error).
