### ISSUE TITLE
Preload Vamp distro's with blueprints

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#313]
Preload the the UI with blueprints hosted on github that define specific stacks & use cases.
- ruby/rails/sinatra
- php
- python/jango
- external service integration
- a/b tests.

Either load them using:
a) curl + vamp cli
```bash
curl https://gist.githubusercontent.com/tnolet/8e6286b83c7027624690/raw/eb8e884d18e01cbd3054a4181b0827b7ca5a465f/monarchs | vamp create blueprint --stdin
```
b) curl + curl
```bash
curl https://gist.githubusercontent.com/tnolet/8e6286b83c7027624690/raw/eb8e884d18e01cbd3054a4181b0827b7ca5a465f/monarchs | curl -X POST -H 'Content-Type: application/x-yaml' -H 'Accept: application/x-yaml' --compressed --data-binary @- http://vamp-local:8080/api/v1/blueprints
```

c) some gui modal/popup asking the user if they want to import the blueprints.

**Comment by faddat** [comment]
+1

I'll submit my blueprints as I get them working.  I think that the blueprint editor could benefit from a non-white background and a fixed-width font, too.

**Comment by dragoslav** [comment]
It's supported in lifter and we may also add it from UI directly as a part of https://github.com/magneticio/vamp-ui/issues/13
