### ISSUE TITLE
vamp-router is moving around in cluster

### ISSUE THREAD

**Issue by buuhsmead** [magneticio/vamp#32]
In the doc there is a screenprint of marathon and deployed vamp-router. You need that screenprint to discover the ip of the deployed router. But that ip is not fixed inside a cluster of mesos-slaves. It started at machine 2 but ended up at machine 0.
But I need a fixed IP to run 
'docker run -d --name=vamp -p 81:80 -p 8081:8080 -p 10002:10001 -p 8084:8083 -e VAMP_MARATHON_URL=http://$MARATHON_MASTER:8080 -e VAMP_ROUTER_URL=http://$VAMP_ROUTER_HOST:10001 -e VAMP_ROUTER_HOST=$VAMP_ROUTER_HOST magneticio/vamp:latest'

So this 'only' works with one slave and not with multiple. Or do I miss something ...

**Comment by tnolet** [comment]
You are 100% correct. This is only due to the "getting started" nature of the docs. In any slightly serious situation you would give the router a dedicated box or a DNS name and maybe even multiple boxes.

We'll make this explicit in the getting started docs.

**Comment by tnolet** [comment]
fixed in docs
