### ISSUE TITLE
Router metrics stop at arbitrary moments

### ISSUE THREAD

**Issue by danielsneijers** [magneticio/vamp#322]
I don't know exactly what is happening but after a deployment stops receiving requests for a while, pulse seems to fail creating events for new requests. Both the SSE streams and Pulse API return empty. Using the 'experimental' docker build which contains 0.7.9 plus the SSE streams.

Also, stack trace of the running vamp instance doesn't log any errors so it might happen under the radar. It seems to be an error in router, checking http://192.168.59.103/:10001/stats/stream returns an empty stream.

**Comment by danielsneijers** [comment]
I noticed when stopping vamp, it does shut down with an error message:

11:46:13.793 | ERROR | io.vamp.common.notification.Notification |                                          | Router response error.
11:46:13.794 | ERROR | io.vamp.common.notification.Notification |                                          | java.net.ConnectException: Connection refused: /127.0.0.1:10001 to http://127.0.0.1:10001/v1/routes
11:46:13.797 | ERROR | i.v.c.o.d.DeploymentSynchronizationActor | e/user/deployment-synchronization-actor$ | Synchronisation not possible

**Comment by danielsneijers** [comment]
Steps for reproducing this:
- deploy a blueprint in vamp
- start apache benchmark on the running deployment
- navigate to the deployment detail screen in vamp-ui (be sure you're using the metrics-sse branch of vamp-ui)
- watch the charts fill with data
- wait for ~5 min
- charts won't update 

from this point on http://192.168.59.103:8080/api/v1/events/stream?tags=metrics&tags=service&tags=services shows an empty stream, so does router at http://192.168.59.103:10001/v1/stats/stream

To fix this I have to restart vamp, stop all containers with docker stop and remove them.

**Comment by tnolet** [comment]
You can see the log message "Metrics parsed in last minute" go from 4880 to 0. That's not good.
```
9:03:09.570 metr NOTI ==>  Metrics parsed in last minute: 4880 
09:03:09.992 api NOTI ==>  HEAD  /v1/stats/stream                                   200      4.571µs 
09:03:10.619 api NOTI ==>  GET   /v1/routes                                         200    558.859µs 
09:03:11.570 api NOTI ==>  GET   /v1/routes                                         200     57.692µs 
09:03:11.716 api NOTI ==>  GET   /v1/info                                           200    700.374µs 
09:03:12.645 api NOTI ==>  GET   /v1/routes                                         200     80.472µs 
09:03:12.673 api NOTI ==>  GET   /v1/info                                           200   2.450024ms 
09:03:13.032 api NOTI ==>  HEAD  /v1/stats/stream                                   200      24.82µs 
09:03:14.018 api NOTI ==>  GET   /v1/routes                                         200     69.452µs 
09:03:14.125 metr NOTI ==>  Added new SSE stream client
09:03:14.549 api NOTI ==>  GET   /v1/routes                                         200     44.581µs 
09:03:15.555 api NOTI ==>  GET   /v1/routes                                         200     44.072µs 
09:03:15.732 api NOTI ==>  GET   /v1/info                                           200   1.956497ms 
09:03:16.049 api NOTI ==>  HEAD  /v1/stats/stream                                   200     66.102µs 
09:03:16.560 api NOTI ==>  GET   /v1/routes                                         200     66.693µs 
09:03:16.794 api NOTI ==>  GET   /v1/info                                           200    537.819µs 
09:03:17.545 api NOTI ==>  GET   /v1/routes                                         200    200.197µs 
09:03:18.545 api NOTI ==>  GET   /v1/routes                                         200     43.312µs 
09:03:19.079 api NOTI ==>  HEAD  /v1/stats/stream                                   200    103.183µs 
09:03:19.574 api NOTI ==>  GET   /v1/routes                                         200     81.043µs 
09:03:20.164 api NOTI ==>  GET   /v1/info                                           200    600.351µs 
09:03:20.532 api NOTI ==>  GET   /v1/routes                                         200     84.283µs 
09:03:21.543 api NOTI ==>  GET   /v1/routes                                         200    150.885µs 
09:03:21.688 api NOTI ==>  GET   /v1/info                                           200    728.025µs 
09:03:22.092 api NOTI ==>  HEAD  /v1/stats/stream                                   200    132.104µs 
09:03:22.576 api NOTI ==>  GET   /v1/routes                                         200     67.263µs 
09:03:23.550 api NOTI ==>  GET   /v1/routes                                         200     40.641µs 
09:03:24.138 api NOTI ==>  GET   /v1/info                                           200    737.735µs 
09:03:24.551 api NOTI ==>  GET   /v1/routes                                         200     60.892µs 
09:03:25.178 api NOTI ==>  HEAD  /v1/stats/stream                                   200    182.367µs 
09:03:25.622 api NOTI ==>  GET   /v1/routes                                         200     67.072µs 
09:03:26.541 api NOTI ==>  GET   /v1/routes                                         200     41.751µs 
09:03:26.691 api NOTI ==>  GET   /v1/info                                           200   1.712632ms 
09:03:27.557 api NOTI ==>  GET   /v1/routes                                         200     41.202µs 
09:03:28.186 api NOTI ==>  GET   /v1/info                                           200   2.216141ms 
09:03:28.235 api NOTI ==>  HEAD  /v1/stats/stream                                   200    129.084µs 
09:03:28.589 api NOTI ==>  GET   /v1/routes                                         200     263.23µs 
09:03:29.551 api NOTI ==>  GET   /v1/routes                                         200     41.452µs 
09:03:30.538 api NOTI ==>  GET   /v1/routes                                         200     43.652µs 
09:03:30.686 api NOTI ==>  GET   /v1/info                                           200    619.593µs 
09:03:31.264 api NOTI ==>  HEAD  /v1/stats/stream                                   200     23.321µs 
09:03:31.570 api NOTI ==>  GET   /v1/routes                                         200     72.882µs 
09:03:32.152 api NOTI ==>  GET   /v1/info                                           200   1.498235ms 
09:03:32.551 api NOTI ==>  GET   /v1/routes                                         200     58.692µs 
09:03:33.540 api NOTI ==>  GET   /v1/routes                                         200     43.312µs 
09:03:34.284 api NOTI ==>  HEAD  /v1/stats/stream                                   200     17.131µs 
09:03:34.568 api NOTI ==>  GET   /v1/routes                                         200    201.267µs 
09:03:34.963 api NOTI ==>  GET   /v1/info                                           200     832.77µs 
09:03:35.545 api NOTI ==>  GET   /v1/routes                                         200     39.471µs 
09:03:36.152 api NOTI ==>  GET   /v1/info                                           200    873.382µs 
09:03:36.540 api NOTI ==>  GET   /v1/routes                                         200     83.973µs 
09:03:37.325 api NOTI ==>  HEAD  /v1/stats/stream                                   200     16.641µs 
09:03:37.568 api NOTI ==>  GET   /v1/routes                                         200     72.162µs 
09:03:38.545 api NOTI ==>  GET   /v1/routes                                         200     41.802µs 
09:03:39.547 api NOTI ==>  GET   /v1/routes                                         200    156.376µs 
09:03:39.714 api NOTI ==>  GET   /v1/info                                           200    694.295µs 
09:03:40.274 api NOTI ==>  GET   /v1/info                                           200   3.364931ms 
09:03:40.345 api NOTI ==>  HEAD  /v1/stats/stream                                   200            0 
```

**Comment by tnolet** [comment]
Initial research:

- inactivity does not have a direct impact.
- the metrics emitter just stops emitting. This is possibly a lock in the channels. 
Making the channels buffered has not solved it yet. Need more research and maybe simplification to fix this.

**Comment by tnolet** [comment]
Removing some unnecessary clutter in the feed handler seems to have the desired effect. Been running for multiple hours with no problems. Problem is that reproduction is till hit or miss.

**Comment by tnolet** [comment]
Running another longevity test with all components connected (Pulse + Core).

**Comment by tnolet** [comment]
Stats channel is unbuffered. This would normally not be a problem, but maybe short interruptions of the metrics flow (due to GC or maybe some other OS level or HAProxy level glitch) can block the channel.

adding buffering should solve this, i.e:
```go
statsChannel := make(chan map[string]map[string]string, 1000000)
```

**Comment by tnolet** [comment]
The simple addition  of "default:" switch seems to have solved the problem. This is slightly unsatisfactory but solves the problem without introducing complexity or hacks.

**Comment by tnolet** [comment]
Still reproducable inside a docker container on GOOS=linux and GOARCH=i386

**Comment by olafmol** [comment]
Interesting: i could keep everything running for 30minutes and more without a glitch when opening the http://192.168.99.100:8080/api/v1/events/stream?tags=metrics&tags=service&tags=services stream in a browser window. Only after underlying and redeploying a 50/50 split blueprint the metrics stopped flowing.

**Comment by olafmol** [comment]
with 0.7.11.1 this behaviour is still there (as expected). I noticed that this message appeared in my log files, might explain why the metrics dissapear suddenly?

**15:10:25.881 | INFO  | io.vamp.core.pulse.PulseActor            | akka://vamp-core/user/pulse-actor        | Percolator successfully removed for 'stream://Actor[akka://vamp-core/user/$q#460136168]'.**
15:10:25.883 | INFO  | akka.actor.ActorSystemImpl               | ActorSystem(vamp-core)                   | http://192.168.99.100:8080/ - Headers: [List(DNT: 1, Accept-Encoding: gzip, deflate, Accept-Language: en-us, User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7, Accept: text/html, application/xhtml+xml, application/xml;q=0.9, */*;q=0.8, Connection: keep-alive, Cookie: mp_3dc73f826819c8e11d0d9898ca4291c8_mixpanel=%7B%22distinct_id%22%3A%20%221502d6fdb8c347-0875d97bd-7a7b3b63-fa000-1502d6fdb8d4cf%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D; vamp_srv=3e054552-8e44-4ccd-acc3-0b9809b93415_9050|Vi5CN|Vi4/O, Cache-Control: max-age=0, Host: 192.168.99.100:8080)]

**Comment by dragoslav** [comment]
If any client (for instance UI) disconnects or because of network issues connection my drop, then you get this message. It's up to client to establish the new connection. We should investigate this.
