### ISSUE TITLE
easier deploy vamp

### ISSUE THREAD

**Issue by buuhsmead** [magneticio/vamp#33]
I created a small naive bash script to run vamp in the background. I think is easier to read than the original.
#!/bin/bash
MARATHON_MASTER=<ip | fqdn marathon master>
VAMP_MARATHON_URL=http://$MARATHON_MASTER:8080
VAMP_ROUTER_HOST=<ip from screen print>
VAMP_ROUTER_URL=http://$VAMP_ROUTER_HOST:10001

docker run -d --name=vamp -p 81:80 -p 8081:8080 -p 10002:10001 -p 8084:8083 -e VAMP_MARATHON_URL=http://$MARATHON_MASTER:8080 -e VAMP_ROUTER_URL=http://$VAMP_ROUTER_HOST:10001 -e VAMP_ROUTER_HOST=$VAMP_ROUTER_HOST magneticio/vamp:latest

**Comment by tnolet** [comment]
Great! Let me see how we can use that in the docs.

**Comment by tnolet** [comment]
used part of the syntax in installation docs
