### ISSUE TITLE
Deploying the same blueprint twice, both with weight 100%

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp#332]
I will take the guide as reference. It's possible to deploy the same blueprint twice, using this curl-statement:

```curl -v -X POST --data-binary @sava_1.0.yaml -H "Content-Type: application/x-yaml" http://192.168.59.103:8080/api/v1/deployments```

When I run this, there are two deployed both with a weight of 100%. So now there are two deployments, both listening on port 9050 and both having a weight of 100%. Although it works, it doesn't seem right. I also don't know what would be a logical response.

**Comment by dragoslav** [comment]
Indeed that would be the strange thing to use the same endpoint for 2 or more deployments.
We already implemented validation for this case #197 (develop branch, will be in following 0.7.10 release).

**Comment by JoshFalken** [comment]
Great! I'll wait for the release.
