### ISSUE TITLE
Deploying a lot of the same blueprints crashes VAMP

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp#333]
Okay, this isn't something you wouldn't do normally but I was fiddling around and wrote the following script:

```#!/bin/bash
for i in {0..1000}
  do
     echo "Welcome $i times"
     curl -v -X POST --data-binary @sava_1_0.yaml -H "Content-Type: application/x-yaml" http://localhost:8080/api/v1/deployments
 done
```

Just to see what would happen. After adding about an hundred, VAMP starts returning 400-errors with the message:

{"message":"The request content was malformed. Internal server error."}

Of course this isn't a normal use case.

**Comment by tnolet** [comment]
@JoshFalken We will investigate!  Thanks for making it reproducable also.

**Comment by JoshFalken** [comment]
@tnolet: you're welcome! looking forward to the 0.7.10-milestone!

**Comment by dragoslav** [comment]
@JoshFalken I couldn't reproduce it using the latest develop branch (with JDBC storage). May try with different setup later.

**Comment by JoshFalken** [comment]
@dragoslav: that's strange... will also retest when 0.7.10 is released.

**Comment by JoshFalken** [comment]
@dragoslav: BTW just tested with deployments on different ports and got the some problem. So it isn't related to being deployed on the same port. Will still wait for release 0.7.10.
