### ISSUE TITLE
Make sure using vamp in team scenario's won't break the user experience

### ISSUE THREAD

**Issue by danielsneijers** [magneticio/vamp#334]
When VAMP is going to be used by teams there will be scenario's where multiple users will be communicating with VAMP from different interfaces. For instance: user A will be editing a blueprint from the UI, user B tries to edit the same blueprint from the cli and user C tries to tweak it with a REST client like postman. Before scenario's like these will be common (e.g. when VAMP enters beta or production) we should think about a logical solution for this problem.

At the moment changes in a blueprint update top-down in the UI. A change will always update a components state, unless I specifically told it not to (like when someone was creating filters in the scala days build). This only solves the problem on the UI part and won't be of any use for users of the cli or rest interface. 

I think it's a good idea to sit down with the team and think of an elegant solution we can build in the future. Possible inspiration: the way git handles changes and merges could be a way in which blueprints could be handled by VAMP.

**Comment by tnolet** [comment]
This is a far larger epic than just an enhancement. This is about users, locking, roles  etc. etc. Closing this for now and will be addressed in a wider ranging epic.
