### ISSUE TITLE
Create integration tests for CLI commands (happy flow)

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#336]
Write integration tests for all of the CLI commands.

Supported commands:
- [ ] create
- [x] deploy
- [ ] generate
- [x] help
- [ ] info
- [ ] inspect
- [ ] list
- [ ] merge
- [ ] remove
- [x] undeploy
- [ ] update
- [x] version

**Comment by dragoslav** [comment]
Closing because of #699
