### ISSUE TITLE
UI doesn't report container driver error

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#337]
I've incorrectly configured Vamp, which results in Vamp Core not being able to communicate with the container driver. In the `/api/v1/info` message, the status of the container driver is reported as:
```json
  "container_driver": {
    "error": "No response."
  }
```

The UI does not report any problems; only the container type field in the settings is empty.
I think it should give feedback, since it won't be possible to deploy anything.

FYI: Using the 0.7.9 release; not tested against latest develop branch

**Comment by danielsneijers** [comment]
fixed, checks for error status now
