### ISSUE TITLE
/api/v1/deployments 'capped'  to 30?

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp#354]
I was fiddling around some more with the API and adding a lot of deployments (now on different ports). But when I call /api/v1/deployments I only seem to receive 30 deployments. I don't know if it has something to do with my test or is this a hard limit set within VAMP?

**Comment by JoshFalken** [comment]
Aaah, I know see there is pagination. I didn't expect that. So that explains a lot :-) Maybe a little remark on the api page of deployments that the requests are capped to 30 by default with a link to the main page?

**Comment by dragoslav** [comment]
Yes, we could update a bit (it applies on all artifacts).
Main note is on the overview page: http://vamp.io/documentation/api-reference/#pagination

**Comment by JoshFalken** [comment]
@dragoslav: Thanks, found it and working with it. I'm surprised that it applies to all artifacts. On http://vamp.io/documentation/api-reference/blueprints/ it says that blueprints delivers all the blueprints without pagination (that was the one that threw me off with the deployments)

**Comment by dragoslav** [comment]
@JoshFalken then definitely we need to update the docs, thanks. It's relatively new feature so missed it.

**Comment by JoshFalken** [comment]
@dragoslav well, that makes two of us :-)

**Comment by JoshFalken** [comment]
@dragoslav: still a small question, maybe I'm still missing something when I run the following command:

```curl -I http://localhost:8080/api/v1/deployments?page=1&per_page=5``` 
(with more than 5 deployments currently in VAMP)

I get the following response:

HTTP/1.1 200 OK
Date: Mon, 24 Aug 2015 19:56:00 GMT
Cache-Control: no-store
Pragma: no-cache
Access-Control-Allow-Origin: *
Content-Encoding: gzip
Content-Type: application/json; charset=UTF-8
Content-Length: 1736

But (I think) these headers should also include 
X-Total-Count: 
Link: 

Should I be using a different way of calling the API?

**Comment by dragoslav** [comment]
I'll recheck this one. It should be with additional headers.

**Comment by dragoslav** [comment]
This is an example response from current develop branch (4 deployments):

```
GET http://localhost:8080/api/v1/deployments?page=1&per_page=3
```
```
Access-Control-Allow-Origin → *
Cache-Control → no-store
Content-Encoding → gzip
Content-Length → 730
Content-Type → application/x-yaml; charset=UTF-8
Date → Tue, 25 Aug 2015 07:17:18 GMT
Link → <http://localhost:8080/api/v1/deployments?page=1&per_page=3>; rel=first, <http://localhost:8080/api/v1/deployments?page=1&per_page=3>; rel=prev, <http://localhost:8080/api/v1/deployments?page=2&per_page=3>; rel=next, <http://localhost:8080/api/v1/deployments?page=2&per_page=3>; rel=last
Pragma → no-cache
X-Total-Count → 4
```

Also tried with different combination of "page" and "per_page" parameters, accept headers (application/json & application/x-yaml) and it worked as expected.
I'll keep this issue open just to retest it once more after the next release.

**Comment by JoshFalken** [comment]
@dragoslav great, thanks for verifying!

**Comment by dragoslav** [comment]
can't find any problem
