### ISSUE TITLE
Very stubborn deployment with incorrect yaml

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp#355]
When I post a deployment using this Yaml (no indentation) below,, I create a deployment that I can't delete using the UI or API. The API returns a 400-error.

---
name: sava:1.0
endpoints:
sava.port: 9050/http
clusters:
sava:
services:
breed:
name: sava:1.0.0
deployable: magneticio/sava:1.0.0
ports:
port: 8080/http
scale:
cpu: 0.2       
memory: 256  
instances: 1

**Comment by dragoslav** [comment]
This seems the same as #311 - it's already fixed in develop branch (0.7.10)
Deployment without services shouldn't be accepted, but will recheck it.

**Comment by dragoslav** [comment]
Yes, in the current develop branch and following 0.7.10 release this request is not accepted: "The request content was malformed. Expected at least one service."
