### ISSUE TITLE
Investigate usage of docker with Travis CI

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#363]
For automatic publishing of the VAMP docker images & automated integration testing. 

See: http://docs.travis-ci.com/user/docker/

**Comment by plamola** [comment]
## General
- Travis CI has docker 1.7 available

## vamp-test
- vamp-test has a `.travis.yml`
- it runs the latest docker images of  vamp-core / vamp-pulse / vamp-router
- it installs the Vamp CLI debian package
- The deployment of blueprints fail, might be due to vamp-core not being able to talk to the docker host

This setup tests the docker / debian images we already released, so it is a bit pointless. For a proper test setup, we would need to publish docker / debian images after every development build. This can be done, with the knowledge of the vamp-dist projects.

## vamp-dist
For releasing our docker images via vamp-dist, we need to supply credentials for the docker login; this might be done in a similar way as is been done with the Bintray credentials. It would be quite easy to setup. On the other hand, publishing the docker images by hand only takes a couple of minutes per release.

**Comment by dragoslav** [comment]
Closing since we are working on having self-hosted solution.
