### ISSUE TITLE
Performance enhancement: refactor Flux stores with immutable data structures

### ISSUE THREAD

**Issue by danielsneijers** [magneticio/vamp#366]
Performance on deployment detail screens isn't as snappy as we would like it to be. This is mainly caused by the amount of render calls made by implementing SSE streams.

While decreasing the amount of render calls in small components is easy (use the shouldComponentUpdate method of a React component), decreasing it in the Master.jsx file is near impossible because of the attached router. Basically what happens is this: every update from the API (SSE, polls, user interaction) triggers a render of the master page and all it's children. But the rendering of these children can also trigger new renderings of the master page, which causes a snowball effect.

Working with immutable data structures solves a lot of these problems as comparing objects (this.props !== nextProps) with regular javascript objects almost always results in 'false'. For more details you can [read this article](http://adripofjavascript.com/blog/drips/object-equality-in-javascript.html).

**Comment by dragoslav** [comment]
Not relevant because of new UI implementation.
