### ISSUE TITLE
Uri as an endpoint?

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp#376]
As I understand it, the endpoint of a service is always a docker image. This also seems logical from the design of Vamp. First of all: Is this correct? Second, if it's correct: are there any plans in the future to make it possible to define an endpoint by an uri, so just to pass on a http-request?

**Comment by tnolet** [comment]
@JoshFalken 

1: You are almost correct: next to Docker containers we also support any other deployable Mesos/Marathon supports. I'm currently working on a setup at a client who just deploys zipfiles and JAR's with Marathon. This works by using the [Marathon dialect](http://vamp.io/documentation/using-vamp/blueprints/#dialects)

2: Yes, we have plans to split Vamp Router into backend routing and an API gateway. This means you could basically redirect traffic anywhere you want. Please see this https://github.com/magneticio/vamp/issues/167

Does this help?

**Comment by JoshFalken** [comment]
@tnolet: yes, it does! Thanks! I've subscribed to #167.

**Comment by tnolet** [comment]
@JoshFalken great!
