### ISSUE TITLE
Feature proposal: Services-service

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp#377]
I was working on a the specs of a new service for Vamp, which is called service. The goal of this service is to make it as easy as possible for new users to use Vamp. This is a first version of the service in which I wanted to make the use of Vamp as easy as posible for a new user and handle 80% of the use cases.

## List services

Lists all services (mind the pagination)

### GET /api/v1/services

Get a single service

### GET /api/v1/services/:id

Gets a service by id

Things to note:

* The service also reports the url on which it can be accessed.

### POST /api/v1/services

Accepts JSON or YAML formatted breeds. Set the Content-Type request header to application/json or application/x-yaml accordingly.

Example in JSON:
```json
{
    "handlers": [{
				"published_port": "integer",
				"port": "integer",
				"uri": "string",
				"critical_response_time": "integer",
				"weight": "integer"
			}],
        }
    }
}
```

Things to note:

* Uri can be a docker image or other deployable that Mesos/Marathon supports. In the future also an url. It is of course 'deployable' in the services-specification
* VAMP is responsible for setting the limits on CPU/memory/deployment in attaining the critical_response_time. 
* port is the port on which the handler exposes it interface

## Update a service

Updates the content of a specific service.

#### PUT /api/v1/services/:id

```json
{
    "handlers": [{
			
				"published_port": "integer",
				"port": "integer",
				"uri": "string",
				"critical_response_time": "integer",
				"weight": "integer"
			}],
        }
    }
}
```

Things to note:
 
* This action adds an handler to the service denoted by ID and 'steals' the weight from the first service. For instance: when you've created a service with handler A and a weight 100 and now add handler B  with weight 50, the weight of handler A is decreased by 50. When you add handler C with weight 50, handler A is no longer being used. 

### Delete a service

Deletes a service.

## DELETE /api/v1/services/:id

- Delete the service denoted by id

**Comment by olafmol** [comment]
Hi Josh, tnx for your valuable input! Could you describe your business-case and/or use-case for your specific proposal? This would help us a lot! tnx :)

**Comment by dragoslav** [comment]
This is covered by:
- deployments and services within deployments - deployment is practically a namespace, i.e. only one service of specific breed can exists within one deployment.
- gateways - weight, etc.
- workflows - example of A, B and C services (100%, 50%, 50%)

In addition UI should support wizards for easier usage, instead of using immediately only the API.
