### ISSUE TITLE
Allow deletion of services in Deployment detail screen

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#378]
As a user, I would like to be able to delete services in the deployment detail screen. Any deletion should be confirmed with a dialog box. We need this feature because it finishes the user story of canary releasing.

Delete API is described here: http://vamp.io/documentation/api-reference/deployments/#delete-a-deployment-using-a-blueprint

**Comment by danielsneijers** [comment]
@tnolet altough it seems simple, I've got a couple of questions:

##### 1: Is the delete button always visible or only if there is more than one service in a cluster 
I'd assume the latter

##### 2: Is the delete button visible when there is traffic routed to the service, or only when the service has 0 weight? 
Both options are legit: if it's always visible, the user should get a warning that services can only be deleted if it has no traffic routed to it. On the other hand: why should the button be shown if it doesn't do anything, as services with traffic routed to them can't be deleted. But it might be confusing for users when the option suddenly pops up. 

In my opinion it makes more sense to only show the delete option when services have no traffic, but I'd like to hear your thoughts before implementing this.

**Comment by tnolet** [comment]
@danielsneijers 

awesome questions:

1: an empty cluster is illegal, so you are right. It should not be possible to delete the last service.
2: the delete request is only accepted when indeed a service is at 0% weight.

In both cases, I think we should show the button, but disable it. Don't remove it.

**Comment by danielsneijers** [comment]
Done! It's in the dev-branch, will push to master if you like.

**Comment by tnolet** [comment]
@danielsneijers AWESOME. Not sure about the button type and location, though. Maybe just a 'X' in the upper right corner? Or a little cogwheel in some corner that folds out a set of buttons?

**Comment by dragoslav** [comment]
It should be possible to remove the last service from a cluster - it means removal of the cluster. If some other cluster depends on that cluster action won't be successful (backend check).

**Comment by tnolet** [comment]
@dragoslav @danielsneijers This means the delete action should handle errors in the same way other synchronous actions handle errors.
