### ISSUE TITLE
Reset API call does not delete all endpoints

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#379]
If a deployment has multiple endpoints, it only removes the first one from the routes. This is a minor bug as the reset command will be deprecated anyway. However, it can leave router in an inconsistent state which makes troubleshooting difficult

**Comment by dragoslav** [comment]
This is probably not related to reset call (it just marks all deployments to be undeployed), but actual implementation of undeployment and endpoint removal itself.
This issue should be addressed together with Gateway API implementation (0.8.x, x > 0)
