### ISSUE TITLE
Add documentation to Vamp UI

### ISSUE THREAD

**Issue by danielsneijers** [magneticio/vamp#380]
To make understanding the UI easier for newcomers, a PDF explaining the meaning of the information presented in the UI must be added to the repository. This file can also be used for presentations or as a general reference card. It is located in the [assets folder in the vamp-ui repository](https://github.com/magneticio/vamp-ui/tree/master/assets/docs)

@tnolet The file is present but I'm not 100% sure all the information is correct. Olaf also suggested that it might be used somewhere in the docs on vamp.io, but I'll leave that decision to you. One thing to consider: the file is pretty large (in dimensions, not file size), so we might want to tweak it a bit before doing so.

**Comment by tnolet** [comment]
@danielsneijers for the site we would not use a PDF. That makes no sense. We would just use html and images. I'll check the PDF for correctness

**Comment by JoshFalken** [comment]
My two cents: when I was a newcomer to Vamp, I learned the most about the UI by the moving screenshots (for lack of a better word) in the tutorial. This static page doesn't show how to add a blueprint, the moving screenshots did just that. Maybe a tab can be added to Vamp showing 'common tasks', that integrate part of the tutorial.

I would integrate the information of the PDF in the UI. As I envision this: a question mark you can click and than the elements that have extra information highlight, clicking them or hovering over them shows what they are.

**Comment by dragoslav** [comment]
https://github.com/magneticio/vamp-ui/issues/13
