### ISSUE TITLE
Router is using a lot of CPU

### ISSUE THREAD

**Issue by jgordijn** [magneticio/vamp#382]
When looking at `top` of the virtual machine I see a constant load of near 100% CPU by `vamp-router`.
This is even the case when nothing is deployed.

To reproduce:
$ docker run  -d --net=host magneticio/vamp-router:0.7.10
$ docker-machine ssh default
$ top

**Comment by tnolet** [comment]
Good catch! And already solved. Please see https://github.com/magneticio/vamp-router/issues/23
A patched version should be available.

**Comment by jgordijn** [comment]
Couldn't find the issue, so created this one :-)

I can confirm that 0.7.10.1 does not have this issue anymore.

**Comment by tnolet** [comment]
@jgordijn great!

**Comment by olafmol** [comment]
should we close this one?
