### ISSUE TITLE
Router crashes after adding gogs blueprint

### ISSUE THREAD

**Issue by faddat** [magneticio/vamp#387]
This happens.....
![image](https://cloud.githubusercontent.com/assets/7142025/10293174/5e01f7e6-6bdd-11e5-87f6-e863e45b55b0.png)

After adding this:

![image](https://cloud.githubusercontent.com/assets/7142025/10293208/7ff925b8-6bdd-11e5-81a4-ad87bdb5a269.png)

**Comment by Ozzadar** [comment]
I will add that this happens whenever you create an invalid endpoint. I remember reading somewhere that creating bad routing takes down HAproxy and takes vamp-router with it.

Removing the apps causing the problem usually solves the routing issues automatically; though it seems to have gotten even more FUBAR'd than usual with the gogs we tried to deploy. 

Something caused our router to go down permanently and cause undeploys to fail to undeploy. (Disappear and reappear shortly afterwards)

**Comment by faddat** [comment]
additonally: gogs needed 2 endpoints, and I think that this may have had
something to do with it.  It has an http endpoint and an ssh endpoint
for git.

-Jake

**Comment by plamola** [comment]
Might have something to do with ports on Linux below 1024 are privileged.
If vamp-router is not running as root, it would fail setting up the routing.

Setting the gogs.shh endpoint above 1023 could solve your issue.

**Comment by olafmol** [comment]
@faddat did you have succes with @plamola suggestion about setting gogs.ssh endpoint above 1023? tnx!
