### ISSUE TITLE
Make Vamp logo on magnetic.io website clickable

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#389]
Would be nice to have the big Vamp logo on the magnetic.io website clickable and direct to the vamp.io website. This is how people act on websites ;) Tried to do it myself but when wrapping the IMG inside a href tags it moves to the left instead of staying centered. As i'm not a CSS guru i'm creating this low-prio ticket ;)

**Comment by dragoslav** [comment]
fixed it, also increased opacity for member photos (less foggy).
