### ISSUE TITLE
Router does not stay in sync

### ISSUE THREAD

**Issue by jgordijn** [magneticio/vamp#390]
When a docker crashes and is started again, it is started with a different port. VAMP does not seem to notice this. As a result the application stops working until the service is undeployed and deployed again.

Driver: marathon.
Version 0.7.10

**Comment by dragoslav** [comment]
Could you check the develop branch? I have fixed the issue like that and could be the same.

**Comment by jgordijn** [comment]
Are there nightly builds I can use? I installed it all using 'yum'.

**Comment by dragoslav** [comment]
We plan to release 0.7.11 soon (today/tomorrow).

**Comment by jgordijn** [comment]
Confirmed it is working now.
