### ISSUE TITLE
Make DSL parser strict

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#392]
At the moment when parser doesn't recognize something it just ignores it. This leads also common errors in syntax (e.g. wrong nesting), ignoring misspelled fields etc. Parser should reject any document (YAML/JSON) that is not semantically valid (well formed). Later we may provide support for custom DSL extensions for handling non-default DSL.

**Comment by olafmol** [comment]
we need to feedback the errors/reason(s) for rejecting the blueprint, preferably in a JSON structure, so we can also display it nicely formatted in the GUI
