### ISSUE TITLE
Remove Pulse

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#393]
Pulse is used only for getting SSE from router and storing events to Elasticsearch. It can be replaced by Logstash.

https://www.elastic.co/guide/en/logstash/1.5/deploying-and-scaling.html
http://nathanleclaire.com/blog/2015/04/27/automating-docker-logging-elasticsearch-logstash-kibana-and-logspout/
http://blog.tutum.co/2014/08/07/using-cadvisor-to-monitor-docker-containers/

**Comment by olafmol** [comment]
Could the new "beats" daemons from Elastic be a relevant way to provide metrics to ELK? https://www.elastic.co/products/beats

**Comment by dragoslav** [comment]
It could be - having any other way to get data is welcome. 
For now we collect HAProxy metrics but we shouldn't be restricted to that of course (e.g. custom app logs).
