### ISSUE TITLE
Vamp architecture update - making it lean and (more) robust

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#396]
#### Current architecture

![vamp-old](https://cloud.githubusercontent.com/assets/7957524/10451322/c0e33858-719f-11e5-83dc-d37f1a04547f.png)

* Vamp Core - main API endpoint, business logic and service coordinator. Talks to the configured container manager (Docker, Marathon etc.) and synchronizes it with Vamp Router. Reads metrics from Vamp Pulse and archives life cycle events to Vamp Pulse. Uses a standard JDBC database for persistence (H2 and MySQL are tested).
* Vamp Pulse - **consumes** metrics from Vamp Router (using SSE or Kafka feeds) and **consumes** events from Vamp Core through REST. Makes everything **searchable** and **actionable**. Uses Elasticsearch.
* Vamp Router - controls HAproxy, **creates** data feeds from routing information. Gets instructions from Vamp Core through **REST** and **offers** SSE and/or Kafka feeds of metric data to Vamp Pulse.

#### Proposed architecture

![vamp-new](https://cloud.githubusercontent.com/assets/7957524/10451333/ce9e287c-719f-11e5-99ac-24eb657d6ef2.png)

* Removing Vamp Pulse:

  * consuming metrics - it can be done by proven solutions like Logstash (not on the diagram)
  * makes everything searchable and actionable - use just plain Elasticsearch

* Vamp Router - keeping it slim and highly available:

  * should update HAProxy configuration - in practice it can get configuration from ZooKeeper (Mesos), or any other similar way (e.g. message broadcasting).
  * **should** be highly available - it can be run as a Marathon app - 1 or many tasks/instances (on different slaves).
  * **could** provide basic health feedback (e.g. HAProxy can't accept configuration). This is not done in the current implementation. It can be done as simple Rest API (Vamp Core can discover all instances using Marathon), message broadcast etc. Simple Rest API is sufficient. Note that *talking* directly to HAProxy can be an option as well.
  * **should not** provide *heavy* Rest API - otherwise is more error prone. Let Core to do this.
  * **should not** create data feeds (e.g. Logstash instead) - otherwise is more error prone and doing something that can be done in better way.

* Vamp Core:

  * should manage Vamp Router instances via Marathon. It should not require *direct* (pre-configured) connection to the Vamp Router(s). HAProxy configuration should be *updated* indirectly (e.g. ZooKeeper). 
  * could be a plain Marathon app. Event though this could have some nice implications (automatic update etc.), it's not shown on the digram (trying to avoid "dream within a dream" impression).

Marathon is used as a reference however everything can be supported by other container managers or even by Docker setup in simple (limited) dev mode. Similar goes for HAPRoxy, Vamp could support NGINX as well.
Ironically current Vamp setup suffers from problems it tries to solve for other applications.

**Comment by plamola** [comment]
Vamp-router  is a REST wrapper for HAProxy.
Could it be another component (alternative to HAProxy), or is HAProxy the only possible solution for this.

**Question**: Could the implementation of Vamp router have a 'router driver', to make it possible to plugin another solution?

This would be analog to the Marathon/Docker container driver in Vamp-Core.

**Comment by olafmol** [comment]
Would make sense from an agnostic point of view, just like the container-drivers. For inspiration: 

- http://traefik.github.io
- https://github.com/ehazlett/interlock/tree/master/plugins/haproxy
- https://github.com/HubSpot/Baragon

**Comment by dragoslav** [comment]
Router may not even exists as an agent. 
Mapping Vamp Route API to HAProxy conf should be done in Core.

For instance if we can update HAProxy (NGINX etc.) configuration (files, sockets) via ZooKeeper (available due to Mesos) or something similar then Vamp Core will be responsible to create (publish) configuration (using specific router driver).

http://comments.gmane.org/gmane.comp.web.haproxy/17394

**Comment by plamola** [comment]
I like the direction this is heading. 

Setup beyond the initial 'Xbox' experience will probably be little more complex, but that would be fine.
 
I guess you'd still need some kind of plugin or agent inside the container management environment to get HAproxy metrics back into Elastic Search. Without metrics, no SLA support.
