### ISSUE TITLE
Cannot get Vamp GUI running with Docker 1.8

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#399]
Someone reports: 

Hi Olaf,

I tried to get vamp up today, but am having trouble.

Docker 1.8 have given me a lot of problems, but most of them I have been able to work around so far.

I followed the quickstart and tried this:
docker run --net=host -v ~/.docker/machine/machines/default:/certs -e "DOCKER_TLS_VERIFY=1" -e "DOCKER_HOST=`docker-machine url default`" -e "DOCKER_CERT_PATH=/certs" magneticio/vamp-docker:0.7.10
The logs look ok and end with
15:48:04.608 api NOTI ==>  HEAD  /v1/stats/stream                                   200     13.009µs 

But I was not able to visit 
http://{docker-machine ip default}:8080/

Then I went into the container and saw that nothing was running on 8080.

➜  ~  docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS               NAMES
559a8360dafb        magneticio/vamp-docker:0.7.10   "/usr/bin/supervisord"   29 seconds ago      Up 28 seconds                           grave_bartik
➜  ~  docker exec -it 559 bash    
root@dev:/# curl localhost:8080
curl: (7) Failed to connect to localhost port 8080: Connection refused
root@dev:/# netstat -lptu      
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 *:1988                  *:*                     LISTEN      22/haproxy      
tcp        0      0 *:ssh                   *:*                     LISTEN      -               
tcp6       0      0 [::]:2376               [::]:*                  LISTEN      -               
tcp6       0      0 [::]:9200               [::]:*                  LISTEN      9/java          
tcp6       0      0 [::]:10001              [::]:*                  LISTEN      10/vamp-router  
tcp6       0      0 [::]:8083               [::]:*                  LISTEN      9/java          
tcp6       0      0 [::]:9300               [::]:*                  LISTEN      9/java          
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN      -               
udp6       0      0 [::]:54328              [::]:*                              9/java          

I also tried running this outside of docker-machine, because I am using a Linux host.

**Comment by dragoslav** [comment]
Will investigate this with new quick start image and 1.9.

**Comment by dragoslav** [comment]
Just updated docs for running on Linux http://vamp.io/documentation/installation/quick_start/.
Didn't test it on older 0.7.x releases, however before the official 0.8.0, there is for instance `magneticio/vamp-docker:0.8.0-RC4` which should run well.
