### ISSUE TITLE
doc installation: re-order sequence of actions

### ISSUE THREAD

**Issue by buuhsmead** [magneticio/vamp#41]
On the website the installation document mentioned a sequence of first pulling vamp , then do something with the router and then again with vamp.
Option 2: Run Vamp with an external Mesos cluster
action 1: pull vamp image

action 1 would be better placed just before action 4.
action 4 is related to vamp.
action 2 en 3 are related to vamp-router

**Comment by tnolet** [comment]
good catch. We've adjust the order of the steps. Should be live any minute.
