### ISSUE TITLE
Investigate ElasticSearch / Logstash 2.0 support

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#412]
ES 2.0 and Logstash 2.0 are released: https://www.elastic.co/blog/release-we-have?blade=tw

We need to investigate future support for these.

For the future we can investigate beats support for docker metrics: https://github.com/Ingensi/dockerbeat
, or see how cAdvisor can integrate with ELK: https://github.com/google/cadvisor/issues/634

**Comment by dragoslav** [comment]
Since 0.8.0 we use ES and Logstash 2.0 (Kibana 4.2). Beats support other things can be investigated separately.
