### ISSUE TITLE
Run command for OSX using docker toolbox seems wrong

### ISSUE THREAD

**Issue by bpasson** [magneticio/vamp#431]
When running the docker based install on OSX using

>docker run --net=host -v ~/.docker/machine/machines/default:/certs -e "DOCKER_TLS_VERIFY=1" -e "DOCKER_HOST=\`docker-machine ip default\`" -e "DOCKER_CERT_PATH=/certs" magneticio/vamp-docker:0.7.11.1

the docker container driver stays in error. I found if i changed the command to

>docker run --net=host -v ~/.docker/machine/machines/default:/certs -e "DOCKER_TLS_VERIFY=1" -e "DOCKER_HOST=tcp://\`docker-machine ip default\`:2376" -e "DOCKER_CERT_PATH=/certs" magneticio/vamp-docker:0.7.11.1

the docker container driver did not show up as an error any more. It might be worth fixing this on the Quick Start pages.

**Comment by olafmol** [comment]
thanks for reporting, will update it!

**Comment by dragoslav** [comment]
@bpasson Thanks! Page is updated `docker-machine url default` instead of `docker-machine ip default`
