### ISSUE TITLE
Disallow HTTP filters for TCP gateways 

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#438]
It's possible to set filters regardless of gateway (port) type. In case of HTTP filters and TCP gateways, the filters will be silently ignored. We should not accept these blueprints (i.e. validation error).

**Comment by olafmol** [comment]
maybe a warning would be better?

**Comment by dragoslav** [comment]
If you configure filters, you expect them to be applied. 
This is quite similar to #392 in effect/experience. People just expect something and then why it's not there...
Also we don't support warning right now, we could add them in response headers, but even then this is more an error/misconfiguration.

**Comment by olafmol** [comment]
ok agreed.
