### ISSUE TITLE
docker / libapparmor.so.1: cannot open shared object file - problem with quick start

### ISSUE THREAD

**Issue by jekalM** [magneticio/vamp#449]
Hi,

I've just tried run vamp following quick start from: http://vamp.io/documentation/installation/quick_start/, version with marathon.

Unfortunately I was not able deploy application. The whole process run well, but on marathon, the app was still in deployment. After checking mesos panel, I figured out that there is no mesos-slave available (0 resources of cpu, mem, etc).

After going into docker container (docker exec -it __containerid__ /bin/bash) I have tried run /usr/local/marathon/mesos-slave.sh. Then I saw reason of no slaves: "libapparmor.so.1: cannot open shared object file". After checking a few options I found solution for this problem:

apt-get update
apt-get install lxc

After that supervisor started mesos-slave and now I can go to next step of quick tutorial.

I think it would be nice to rebuild image and push it to docker hub.

Regards,

**Comment by dragoslav** [comment]
Hi @jekalM thanks for reporting this. What is your host OS and Docker version? I'll definitely rebuild the image.

**Comment by jekalM** [comment]
Hi, it's:

17:53 $ docker --version
Docker version 1.9.0, build 76d6bc9
17:53 $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

I have also found some problems with second image(docker). After running I saw in log information about problems with zookeeper (no host found?). But I didn't investigated problem. If you are not able reproduce problem, I think I could try spend some time on it.

Regards,

**Comment by dragoslav** [comment]
Thanks, I'll investigate the both of them.

**Comment by dragoslav** [comment]
Yes, indeed, managed to reproduce it for Marathon image running on Ubuntu 14.04 and Docker 1.9. The correct image is already pushed on docker hub. Didn't have any problem with other image a part of an undelivered notification message during start.

**Comment by olafmol** [comment]
@jekalM could you confirm if it works for you now so we can close this issue. Tnx!

**Comment by jekalM** [comment]
Hi, 

@olafmol : yep, can confirm that now, after removing whole image and pulling it once again everything works fine. I have also checked the second image (without marathon) and it works also ok. 

Thanks!

**Comment by olafmol** [comment]
great, thanks for reporting!
