### ISSUE TITLE
Update Sava images

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#455]
* debug mode: show service id (e.g. sava 1.0) and instance id (UUID) - sticky session show case
* additional port (e.g. simple metrics/health) for routing on more than one port

**Comment by olafmol** [comment]
Suggestion to use cAdvisor or Coda Hale's metrics for additional health port:

https://github.com/google/cadvisor

http://metrics.dropwizard.io/3.1.0/getting-started/
