### ISSUE TITLE
Document logged metrics from Vamp gateway agent

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#458]
For our documentation we need to document and explain all the metrics we log from VAMP Gateway agent. Right now we are using the default HAProxy (single-character) metric-names, we also might use more descriptive labeling for easier understanding and creation of logstash queries/kibana dashboards.

**Comment by dragoslav** [comment]
Just added #459
Users could use any labeling they wish and for possible parameters they can check the official HAProxy documentation.
Vamp Gateway Agent doesn't generate any other custom log and if we change that, then we will provide list of additional parameters.

**Comment by dragoslav** [comment]
Closing this since #459 is done.
