### ISSUE TITLE
docker pull magneticio/vamp:0.7.0-RC3 is not latest

### ISSUE THREAD

**Issue by buuhsmead** [magneticio/vamp#46]
Maybe on purpose but 'docker pull magneticio/vamp:latest' gives version 0.7.0-RC2 and not 0.7.0-RC3
This is the output of 'docker images' 
REPOSITORY                  TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
docker.io/magneticio/vamp   0.7.0-RC3           e5f9ea57179c        8 days ago          941.3 MB
magneticio/vamp             0.7.0-RC2           8972e9dafa43        2 weeks ago         941.2 MB
magneticio/vamp             latest              8972e9dafa43        2 weeks ago         941.2 MB
docker.io/magneticio/vamp   0.7.0-RC2           8972e9dafa43        2 weeks ago         941.2 MB
docker.io/magneticio/vamp   latest              8972e9dafa43        2 weeks ago         941.2 MB

**Comment by tnolet** [comment]
will check the latest push to docker hub. My local "latest" version is the RC3 version. We build the RCx versions first and then retag them as latest. Maybe something went wrong with the push.

**Comment by tnolet** [comment]
@buuhsmead. The image was already pushed. So something else must have been wrong. See the output of `docker push`

```
Sending image list
Pushing repository magneticio/vamp (1 tags)
511136ea3c5a: Image already pushed, skipping 
f3c84ac3a053: Image already pushed, skipping 
a1a958a24818: Image already pushed, skipping 
9fec74352904: Image already pushed, skipping 
d0955f21bf24: Image already pushed, skipping 
23349001223b: Image already pushed, skipping 
6c2617291f44: Image already pushed, skipping 
c510b5fa9855: Image already pushed, skipping 
d8a81e277706: Image already pushed, skipping 
709d157e1738: Image already pushed, skipping 
d68e2305f8ed: Image already pushed, skipping 
b87155bee962: Image already pushed, skipping 
0e984c360c11: Image already pushed, skipping 
a1d56bd82569: Image already pushed, skipping 
641112daf4b0: Image already pushed, skipping 
29ef457baf01: Image already pushed, skipping 
8994f43c01f6: Image already pushed, skipping 
ad7378612677: Image already pushed, skipping 
dfaa922241fc: Image already pushed, skipping 
c6c9c4e605b9: Image already pushed, skipping 
efe5f103d08c: Image already pushed, skipping 
72416711a987: Image already pushed, skipping 
4160fe06ad31: Image already pushed, skipping 
b3c0381ca43a: Image already pushed, skipping 
e5f9ea57179c: Image already pushed, skipping 
Pushing tag for rev [e5f9ea57179c] on {https://cdn-registry-1.docker.io/v1/repositories/magneticio/vamp/tags/latest}
```

We have retagged it, so the current correct rev is [e5f9ea57179c].
