### ISSUE TITLE
Implement simple metrics aggregation agent

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#479]
At the moment we aggregate metrics (e.g. response time) in Vamp itself (recurring task).
Better way is to handle this job by an agent - in general we need to have aggregated data but how they are aggregated should not be part of the core Vamp implementation.

Scope of this issue:
- gateway rate
- gateway response time

**Comment by olafmol** [comment]
Some suggestions to investigate:

https://collectd.org
http://techblog.netflix.com/2014/12/introducing-atlas-netflixs-primary.html and https://github.com/Netflix/atlas/wiki/Overview
https://developers.soundcloud.com/blog/prometheus-monitoring-at-soundcloud
