### ISSUE TITLE
Support for Tutum ?

### ISSUE THREAD

**Issue by mfilotto** [magneticio/vamp#490]
Hi there,
Do you plan to have a support for Tutum ?
Thanks

PS : your tool seems very nice

**Comment by olafmol** [comment]
Hi Mathieu, thanks for the interest and kind words, much appreciated! :) 

Currently there are no plans for Tutum support. As Tutum is SaaS/PaaS, and VAMP is focused on delivering higher-level canary-testing&releasing features on top of "self-built/managed container clouds" using container-schedulers like Mesos/Marathon and Kubernetes, it's complex to see how VAMP and Tutum would work together. The Tutum API might be a possible solution, or Tutum would need to add and integrate the VAMP framework to it's stack. 

I'm curious to hear about your use-case, could you tell us more so we can help you. cheers!

**Comment by mfilotto** [comment]
Hi @olafmol 
I'm using Tutum and I very like it.
But release worklows like those bring by Vamp are not available.
As Tutum is now a Docker Inc product I hope that it shoulb become docker-compose and docker-swarm compliant soon.
Does Vamp works well with standard docker management ? (compose and swarm

**Comment by olafmol** [comment]
Vamp has drivers for Docker. Docker Swarm has the same API as Docker, so theoretically it Vamp should also work with Docker swarm. I'm not sure in how far Tutum exposes the underlying Docker API's to it's clients. You could ask Tutum how Vamp could integrate with their platform of course.

**Comment by mfilotto** [comment]
Thanks @olafmol 
I asked the question on their slack. i'll let you know their answer

**Comment by olafmol** [comment]
@mfilotto hi Mathieu, did you get any answer from Tutum on your question?

**Comment by mfilotto** [comment]
@olafmol no answers yet. I ask again and let you know

**Comment by olafmol** [comment]
closing this issue, please re-open if still relevant @mfilotto
