### ISSUE TITLE
Support for multiple combined routing ACL rules (API gateway related)

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#491]
Use-case: i want to be able to create a condition where i rewrite a URL/Path to route to a specific VAMP endpoint. To do rewriting i need to setup at least 2 ACL rules that are working together:

http://www.haproxy.com/doc/aloha/7.0/haproxy/http_rewriting.html
http://stackoverflow.com/questions/24784517/haproxy-route-and-rewrite-based-on-uri-path
http://stackoverflow.com/questions/11140021/haproxy-match-various-conditions-in-use-backend

Example gateway blueprint:

---
name: sava
port: 9070/http
routes:
  sava:1.0/sava/port:
    weight: 100 
  sava:1.1/sava/port:
    weight: 0
    filters:
    - condition: "rule_api_path path_beg -i /api/v11"
    - condition: "http-request set-path /%[path] if rule_api_path"

The problem right now is that conditions are parsed as individual ACL rules, and cannot be combined.

**Comment by dragoslav** [comment]
```yaml
filters:
- condition: User-Agent = Firefox
- condition: User-Agent != Chrome
```
will be resolved to:
```yaml
acl af3 hdr_sub(user-agent) Firefox
acl 81b hdr_sub(user-agent) Chrome
use_backend 9711cc3907 if af3 !81b
```
This doesn't solve the redirect because proxy keyword `http-request` should be used instead of `use_backend`.
Generic solution is to support HAProxy dialects with variables (e.g. for backend names) or for this particular issue #495
