### ISSUE TITLE
Write tutorial / doc how to connect local dev to remote prod environment

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#509]
To better on-board new developers it's necessary to describe in a easy-to-follow tutorial how to setup a local Vamp development environment (using the QuickStart docker version f.e.), then how to setup a Vamp production environment (for relatively simple LAMP/PHP, Ruby/Rails, Node.js websites/apps), and how to connect local dev to remote prod using the deployments of blueprints to the "remote" Vamp environments.

**Comment by aliteff** [comment]
+1

**Comment by olafmol** [comment]
Hi @aliteff if we can help you in the meantime just let us know! you can use our gitter for chat: https://gitter.im/magneticio/vamp or just post here. Tnx for supporting Vamp!

**Comment by olafmol** [comment]
Moved to Trello
