### ISSUE TITLE
Create more detailed mixpanel metrics

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#510]
for market-research and product-roadmap design we need more/better mixpanel metrics (like version running, aggregated events, number of clusters/gateways/deployables/services/breeds in blueprints to get a feeling of size of use).

After implementing #473 we can use these metrics to post these to mixpanel. Metrics that need to show up in mixpanel:

- Vamp version
- driver-type (docker, mesos/marathon)
- number of blueprints
- number of total clusters
- number of total services
- number of total breeds
- number of deployments
- number of gateways

We can use mixpanel to calculate totals.

**Comment by dragoslav** [comment]
This depends directly on #473 (`/statistics` endpoint).
This should go to the backlog unless #473 is also scheduled.

**Comment by dragoslav** [comment]
closing because is related to UI and there is already an issue for that.
