### ISSUE TITLE
Tutorial: Doing a canary release causes exceptions

### ISSUE THREAD

**Issue by diversit** [magneticio/vamp#521]
Trying out Vamp using Docker according to the Getting Started guide.
On a MacPro, using a docker-machine with 4 cpu and 8GB memory.

Deploying the blueprint (step 1) was successful.
When doing a canary release, after updating the deployment blueprint (via deployments --> <deployment id> --> 'edit deployment'), the logs shows several errors (NPE, AskTimeout) and 'null' messages being sent. Vamp seems to 'hang'. The deployment view cannot be updated anymore. The new 1.1.0 release is not show. And even the app, on port 9050, is not accessible anymore.

**Comment by olafmol** [comment]
@diversit Which version of Vamp quickstart are you using? Guessing 0.8.2 Vamp-Marathon quickstart?

**Comment by diversit** [comment]
Yes. Latest and greatest ;-)

Joost

**Comment by olafmol** [comment]
yeah, rub it in some more @diversit ;)

**Comment by olafmol** [comment]
we'll let you know when 0.8.3 is released. For now you could use 0.8.1 but then you have to modify the example blueprints a little-bit to make them validate again.

**Comment by petervandenabeele** [comment]
On 0.8.3, I tested step 1, step 2 and step 3 (on Mac with docker-machine on docker 1.9.0) and all worked fine :-)

**Comment by olafmol** [comment]
@petervandenabeele that's great to hear! Docker 1.10.x introduced some breaking changes in the networking-implementation, so we've been focusing on making VAMP more robust working with all recent versions of Docker.
