### ISSUE TITLE
Support SoftwareDefinedNetworking (SDN) configs

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#524]
Right now we use Docker HOST. To make Vamp run in SDN setups we should also support different ways of IP address allocation/network-overlays.

(Suggestion would be to investigate with starting support of Weave as can run with Docker, Mesos/Marathon and Kubernetes ao. This is also interesting to achieve a "unified container networking overlay":  http://www.weave.works/cni-for-docker-containers/)

**Comment by faddat** [comment]
Weave is fantastic.  It's a great choice.

**Comment by olafmol** [comment]
Moved to Trello
