### ISSUE TITLE
Add health endpoint

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#527]
Related to #426
Health can be defined on gateways and deployments:
```
/api/v1/health/gateways/$gateway
/api/v1/health/gateways/$gateway/routes/$route

/api/v1/health/deployments/$deployment
/api/v1/health/deployments/$deployment/clusters/$cluster
/api/v1/health/deployments/$deployment/clusters/$cluster/services/$service
/api/v1/health/deployments/$deployment/clusters/$cluster/services/$service/instances/$instance
```

Scope of this issue is the RESTful endpoint, not analytic engine that calculate the health response.

**Comment by olafmol** [comment]
We have to make sure that at minimum we can comply to common health-check patterns like:

- Kubernetes: http://kubernetes.io/v1.1/docs/user-guide/liveness/
- Marathon: https://mesosphere.github.io/marathon/docs/health-checks.html
- Rancher: http://docs.rancher.com/rancher/concepts/health-checks/
- Consul: https://www.consul.io/intro/getting-started/checks.html
