### ISSUE TITLE
Add metrics endpoint 

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#528]
Scope of this issue is the RESTful endpoint, not analytic engine that calculate the metrics.
Metrics can be defined on gateways and deployment ports:
```
/api/v1/metrics/gateways/$gateway/$metrics
/api/v1/metrics/gateways/$gateway/routes/$route/$metrics

/api/v1/metrics/deployments/$deployment/clusters/$cluster/ports/$port/$metrics
/api/v1/metrics/deployments/$deployment/clusters/$cluster/services/$service/ports/$port/$metrics
/api/v1/metrics/deployments/$deployment/clusters/$cluster/services/$service/instances/$instance/ports/$port/$metrics
```

Example: `/api/v1/metrics/deployments/sava/clusters/frontend/ports/api/response-time`

Custom business metrics still need to be per port (may be changed later):
`/api/v1/metrics/deployments/sava/ports/api/conversion-rate`

**Comment by olafmol** [comment]
At minimum provide compatibility with Coda Hale's metrics library: https://dropwizard.github.io/metrics/3.1.0/getting-started/
