### ISSUE TITLE
Support for Shipyard ?

### ISSUE THREAD

**Issue by mfilotto** [magneticio/vamp#538]
Hi there,
Do you plan to have a support for Shipyard ?
As Shipyard  is 100% Docker, Vamp + Shipyard could be a very good mix
What do you think ?
Thanks

**Comment by olafmol** [comment]
@mfilotto if Shiphard is Docker compatible it would be trivial to integrate Vamp with it. The same is true for any other supported Vamp scheduler/cloud-driver like Mesos/Marathon and Kubernetes (coming up). For example there currently is a project to integrate Vamp with Rancher, as Rancher is also using the Docker API.

So yes, that would be entirely possible. Could you describe your use-case and requirements in more detail, so we can help you flesh out the details?

**Comment by mfilotto** [comment]
@olafmol Thanks for your answer, I'm try to make it work together.
My requirements is to have a complete platform for my containers and their deployment life cycle

**Comment by olafmol** [comment]
Hi @mfilotto sounds like a cool plan! We're very open for pull requests and forms of opensource collaboration. Let me know if you want to discuss this further.

**Comment by olafmol** [comment]
closing this issue, please re-open if still relevant @mfilotto
