### ISSUE TITLE
Remove host and scale configuration parameters from dictionary module

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#541]
Main use of Dictionary would be:

- managing Vamp configuration at runtime - some parameters may still be updated only after the restart
- overriding custom artifact values, e.g. passwords etc.

We keep gateway `host` and default `scale` in dictionary right now even though these parameters are related to `gateway-driver` and `operation` modules. On the other hand `dictionary` should manage all other parameters as well.
Idea is to keep only dictionary related parameters in dictionary configuration and later implement the core dictionary features (related to #283 as well).

**Comment by olafmol** [comment]
would this also be related to #440 ?

**Comment by dragoslav** [comment]
#440 yes, but only to full implementation of dictionary service. 
This issue is just about some clean up.
