### ISSUE TITLE
Error when deleting obsolete configurations following VAMP tutorial..

### ISSUE THREAD

**Issue by capitanbatata** [magneticio/vamp#547]
When following the tutorial at the [VAMP guide](http://vamp.io/documentation/guides/getting-started-tutorial/4-merge-delete/) I cannot delete the obsolete parts of the deployment.

Either using the exported yaml file via:

    curl -X GET -H "Accept: application/x-yaml" http://localhost:8080/api/v1/deployments/d30a4d43-5010-42a2-863c-7a2403722f06?as_blueprint=true | gunzip > blueprint.yaml

or by copying and pasting the cleaned up version into a local yaml file, I get the following error:

    curl -XDELETE http://localhost:8080/api/v1/deployments/d30a4d43-5010-42a2-863c-7a2403722f06 -d @blueprint.yaml -H "Content-type: application/x-yaml"
    {"message":"The request content was malformed. Error: mapping values are not allowed here\n in 'reader', line 1, column 23:\n    name: sava:1.2clusters:  sava:    services:      breed ... \n                          ^\n"}

I don't know if this is an error in the way I'm performing the deletion or an error in VAMP.

**Comment by dragoslav** [comment]
Hi @capitanbatata could you post the `blueprint.yaml` file? Which Vamp version do you use?

**Comment by capitanbatata** [comment]
This is the version I copied from the tutorial

    name: sava:1.2
    clusters:
      sava:
        services:
          breed:
            ref: sava-frontend:1.2.0
      backend1:
        services:
          breed:
            ref: sava-backend1:1.2.0
      backend2:
        services:
          breed:
            ref: sava-backend2:1.2.0
    
Vamp version is 0.8.3 (Docker image from the tutorial, running on Linux).

**Comment by dragoslav** [comment]
Basically new lines from `blueprint.yaml` were removed by curl. Could you try `--data-binary` instead of `-d`: 
```
curl -XDELETE http://localhost:8080/api/v1/deployments/sava --data-binary @blueprint.yaml -H "Content-type: application/x-yaml" --compressed 
```

`--compressed` just to decompress the response

**Comment by capitanbatata** [comment]
That solved the problem, namely my lack of familiarity with the curl flags :). Thanks @dragoslav.
