### ISSUE TITLE
When specifying multiple gateways in a deployment, only the second one is shown in the UI, but both work

### ISSUE THREAD

**Issue by basbl** [magneticio/vamp#567]
Given the following blueprint:

```
---
name: project
gateways:
  9065: service1/port
  9066: service2/port
# rest of blueprint...
```

Only the first defined gateway is visible in the graph on the deployment detail view. I'd expect some way to switch views.

**Comment by olafmol** [comment]
Hi @basbl the current GUI is not up-to-date/feature-parity with our Rest API anymore. We're currently working on a new (angularJS 2 based) GUI that will be much better and has feature-parity with the API. For now we advise using the GUI as a introductionary/learning/demo-tool, and use the REST API for production use.
