### ISSUE TITLE
Release vamp-core and vamp-pulse as multiple artifacts

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#59]
The different modules of vamp-core and vamp-pulse should be released as separate packages and be published on Bintray. Currently, core and pulse are released as a single big assembly.

To accomplish this:
* Create packages on Bintray
* Change the build.sbt
* Push the new build.sbt to github, to force a build by Travis CI
* Request inclusion of each package in JCenter

**Comment by plamola** [comment]
For vamp-core:
* Restructured the build.sbt, so modules have less dependencies.
* Configured each module to have a separate name & description
* Added travis-ci build step for publishing artifacts
* Requested JCenter inclusion for all new core packages

Not sure what to do with Vamp-Pulse at this moment.

**Comment by dragoslav** [comment]
Pulse is the similar: 3 modules (client, model, server).
We will change structure if we move to Logstash.

**Comment by plamola** [comment]
All JCenter inclusions are approved.
