### ISSUE TITLE
Create Docker compose files for setting up a Vamp opinionated stack on online (test) environments  

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#600]
Background: The step from running the single-container Quickstart to evaluating VAMP on a test/production (online) environment is difficult, as the Quickstart is not useful for this, and it’s not clear how to set this up on typical architectures.

We need to provide a next-step tutorial and corresponding installer scripts (Docker compose? Terraform?) to easily install all the necessary VAMP components and their dependencies (inside separate Docker containers). 

Typical containers would be: Vamp(core), VGA(including HAproxy), ELK, Consul(or Zookeeper?).

We should be able to work with (or have scripts for) several container-management systems: Mesos/marathon, DCOS, Docker Swarm, Kubernetes. We expect these to be installed and running already.

**Comment by dragoslav** [comment]
This is compose file for Vamp + Marathon https://github.com/magneticio/vamp-docker/blob/master/compose/vamp-marathon.yml

**Comment by dragoslav** [comment]
A part of tutorials mentioned in the previous comment we have more specific issues like https://github.com/magneticio/vamp/issues/509
Since this issue is more generic, closing it - if there is need for concrete tutorials then it should be a specific issue for it.
