### ISSUE TITLE
API delete gateway returns 405 (method not allowed)

### ISSUE THREAD

**Issue by treaz** [magneticio/vamp#605]
I'm trying to delete a gateway and I'm failing. I'm following the documentation from [here](http://vamp.io/documentation/api-reference/gateways/)

Doing a ` GET http://192.168.99.100:8080/api/v1/gateways` returns
```javascript
[
  ...
  {
    "name": "90ea1a50-4e98-4e43-9455-e20e77be51b9/27017",
    "lookup_name": "4db7827ddfbfca8729fdcb36684b2555eb1a8b13",
    "port": "27017",
    "deployed": true,
    "sticky": "none",
    "routes": {
      "90ea1a50-4e98-4e43-9455-e20e77be51b9/mongo/port": {
        "weight": "100%",
        "filters": [],
        "rewrites": []
      }
    }
  }
...
]
```

I'm trying to delete gateway with name _90ea1a50-4e98-4e43-9455-e20e77be51b9/27017_
`DELETE http://192.168.99.100:8080/api/v1/gateways/90ea1a50-4e98-4e43-9455-e20e77be51b9/27017` returns
`HTTP method not allowed, supported methods: GET`

I have no idea how I would be able to delete a gateway ([CLI doesn't work either](https://github.com/magneticio/vamp/issues/604))

**Comment by olafmol** [comment]
Did you try Url encoding the slash?

**Comment by treaz** [comment]
URL encoding the slash did the trick. Thank you!

**Comment by olafmol** [comment]
BTW, if you are creating explicit gateways (like described here: http://vamp.io/documentation/using-vamp/gateways/) (instead of gateways implicitly created by Vamp deployments) it will use the name in your gateway POST yaml, so you don't have generated slashes etc in the name.

**Comment by dragoslav** [comment]
In the following release we will include also https://github.com/magneticio/vamp/issues/587
