### ISSUE TITLE
Cannot click blueprint in blueprints page

### ISSUE THREAD

**Issue by treaz** [magneticio/vamp#607]
Happens in 0.8.4.

Reproduction steps
Go to the blueprints page. 
Create at least 2 blueprints.
Click on one of the blueprints to start editing it.
Click cancel to exit edit mode.

Trying to hover or click on deploy on the second blueprint does not work.

**Comment by olafmol** [comment]
We're aware the GUI is kind of buggy. We're currently finishing up a new opensource UI. Please bear with us.
