### ISSUE TITLE
Quick start with Marathon on Windows - Docker Quickstart Terminal

### ISSUE THREAD

**Issue by fabrii** [magneticio/vamp#615]
I dont know if this is the proper place for posting this. I apologize if it isn't.

When running:

![win](https://cloud.githubusercontent.com/assets/18692157/14840759/8d8d9a3a-0c0d-11e6-852c-a5561b5bc401.jpg)

i get the following error:
C:\Program Files\Docker Toolbox\docker.exe Error parsing reference "Files/Docker" is not a valid repository/tag.

What am i doing wrong?

Btw, Kitematic isnt supported right?.
Thanks.

**Comment by olafmol** [comment]
Hi @fabrii txn for reporting, we're investigating the issue! We're aware that Windows support is somewhat flaky with Docker toolbox, we will try to get this improved asap.

**Comment by olafmol** [comment]
@fabrii i did check with the latest docker toolbox 1.11.1 on windows 10 and the current vamp-marathon quickstart version (0.8.5) and it worked for me. Can you confirm?

**Comment by fabrii** [comment]
Hi @olafmol. With docker toolbox 1.11.1 worked like a charm. It didnt with 1.11.0.
Thanks for your time!

**Comment by olafmol** [comment]
good to hear @fabrii ! closing this issue now.
