### ISSUE TITLE
Json format for environment_variables, constants, dependencies

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp#638]
When I add a breed with two environment variables and request this breed, I get the following Json:

[{"name":"sava:1.0.0","deployable":"docker://magneticio/sava:1.0.0","ports":{"port":"8080/http"},"environment_variables":{"testKey":"testValue","testKey2":"testValue2"},"constants":{},"arguments":[],"dependencies":{}}]

But what I expected (for the part of the environment_variables) was:
[{"testKey":"testValue"},{"testKey2":"testValue2"}]

Why isn't this formatted like an array? It would make the parsing a whole lot easier.

**Comment by dragoslav** [comment]
Thanks @JoshFalken, this issue should be addressed in https://github.com/magneticio/vamp/issues/684

**Comment by JoshFalken** [comment]
Thanks @dragoslav : looking forward to it!

**Comment by dragoslav** [comment]
Closing because of #684
