### ISSUE TITLE
Kibana dashboard generation as a workflow

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#646]

**Comment by olafmol** [comment]
Is the kibana dashboard generation still relevant? I never use it.

**Comment by dragoslav** [comment]
It should not be part of Vamp, because:
- postpones starting Vamp - waiting Kibana to be up
- it's just a showcase of possibilities

So, as a workflow:
- Vamp can start when data store is ready (ES)
- showcase is till there - just running as a workflow - and we can present that also as a nice example of workflow API
