### ISSUE TITLE
Update current (master) DC/OS docs

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#662]
- [ ] Create disclaimers in documentation about how to modify/extend the above into a HA/production setting (f.e. by extending to 3 public nodes to run 3 VGA's for HA; or installing VAMP on private node and expose it through a Marathon-LB or VGA mapping)
- [x] Add reference in docs that VAMP is available as a Universe package

**Comment by iamtew** [comment]
The following configurations work with both DC/OS 1.7 and 1.8 and will bring Vamp up in a healthy state to deploy services on.

### Elasticsearch + Logstash + Kibana

This is our standard ELK image from https://github.com/magneticio/elastic, which we run with 1GB memory. 

```JSON
{
  "id": "elasticsearch",
  "instances": 1,
  "cpus": 0.2,
  "mem": 1024.0,
  "container": {
    "docker": {
      "image": "magneticio/elastic:2.2",
      "network": "HOST",
      "forcePullImage": true
    }
  }
}
```

### Vamp

The main Vamp application using the latest Katana images. New things:
- Running in bridge mode with automatic port mapping
- Providing UI link from inside DC/OS, see labels `DCOS_SERVICE_NAME`, `DCOS_SERVICE_SCHEME` and `DCOS_SERVICE_PORT_INDEX`
- Simple TCP port health check
- Adding an VIP using the Minuteman L4 load balancer. This is necessary for internal communication with Vamp.
- Overriding defaults from the docker images to align with running in DC/OS, including setting the default Vamp URL to the Minuteman VIP.

```JSON
{
  "id": "vamp/vamp",
  "instances": 1,
  "cpus": 0.5,
  "mem": 1024,
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "magneticio/vamp:katana-dcos",
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 8080,
          "hostPort": 0,
          "name": "vip0",
          "labels": {
            "VIP_0": "10.20.0.100:8080"
          }
        }
      ],
      "forcePullImage": true
    }
  },
  "labels": {
    "DCOS_SERVICE_NAME": "vamp",
    "DCOS_SERVICE_SCHEME": "http",
    "DCOS_SERVICE_PORT_INDEX": "0"
  },
  "healthChecks": [
    {
      "protocol": "TCP",
      "gracePeriodSeconds": 30,
      "intervalSeconds": 10,
      "timeoutSeconds": 5,
      "portIndex": 0,
      "maxConsecutiveFailures": 0
    }
  ],
  "env": {
    "VAMP_LIFTER_ARTIFACT_FILES": "[]",
    "VAMP_WAIT_FOR": "http://elasticsearch.marathon.mesos:9200/.kibana",
    "VAMP_PERSISTENCE_DATABASE_ELASTICSEARCH_URL": "http://elasticsearch.marathon.mesos:9200",
    "VAMP_GATEWAY_DRIVER_LOGSTASH_HOST": "elasticsearch.marathon.mesos",
    "VAMP_WORKFLOW_DRIVER_VAMP_URL": "http://10.20.0.100:8080",
    "VAMP_PULSE_ELASTICSEARCH_URL": "http://elasticsearch.marathon.mesos:9200"
  }
}
```

### Vamp Gateway Agents

Using the latest Katana images, this does:
- Run on all nodes, public and private
- Overriding defaults from the docker images to align with running in DC/OS
- Simple TCP health check on the HAproxy status page

```JSON
{
  "id": "vamp/vamp-gateway-agent",
  "instances": 3,
  "cpus": 0.2,
  "mem": 256.0,
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "magneticio/vamp-gateway-agent:katana",
      "network": "HOST",
      "privileged": true,
      "forcePullImage": true
    }
  },
  "args": [
    "--storeType=zookeeper",
    "--storeConnection=zk-1.zk:2181",
    "--storeKey=/vamp/gateways/haproxy/1.6",
    "--logstash=elasticsearch.marathon.mesos:10001"
  ],
  "acceptedResourceRoles": [
    "slave_public",
    "*"
  ],
  "constraints": [
    [
      "hostname",
      "UNIQUE"
    ]
  ],
  "healthChecks": [
    {
      "protocol": "TCP",
      "gracePeriodSeconds": 30,
      "intervalSeconds": 10,
      "timeoutSeconds": 5,
      "port": 1988,
      "maxConsecutiveFailures": 0
    }
  ]
}
```

**Comment by iamtew** [comment]
Documentation has been updated as part of https://github.com/magneticio/revamp.io/issues/103
