### ISSUE TITLE
Vamp 0.9.0 and DC/OS Universe v3

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#682]
- [x] We should use `leader.mesos` instead of `master.mesos` https://dcos.io/docs/1.7/usage/service-discovery/mesos-dns/troubleshooting/#-a-name-leader-a-what-is-the-difference-between-leader-mesos-and-master-mesos-
- [x] Replace all IP's with hostnames: ZooKeeper, Elasticsearch, Logstash
- [x] Support new universe: https://github.com/mesosphere/universe/pull/433#issuecomment-226956012
- [ ] For smooth evaluation/onboarding make sure VAMP and VGA/Logstash containers are deployed on the default public node (https://docs.mesosphere.com/1.7/usage/tutorials/public-app/ : "acceptedResourceRoles":["slave_public”]) to they are publicly available 
- [ ] both 'single' click and Vamp only Docker images

**Comment by olafmol** [comment]
could we also make this one single container package so it can be a self-contained "single-click" DCOS installation

**Comment by iamtew** [comment]
#781

**Comment by iamtew** [comment]
Installing ES at the same time as of our Vamp package won't work in the current situation, as we can only install one service at a time. Once this ticket has been resolved and made available in DC/OS we should be able to update our package to do this: https://dcosjira.atlassian.net/browse/DCOS-91
