### ISSUE TITLE
Vamp should expose a health endpoint

### ISSUE THREAD

**Issue by harmw** [magneticio/vamp#687]
For obvious reasons, Vamp should contain some health endpoint on which tools like Marathon and/or Consul can query. This way we can have Marathon deploy a new container whenever the Vamp container dies.
This could be as simple as an endpoint that either returns 200 on _ok_ and something else when _not-ok_.

**Comment by dragoslav** [comment]
`/api/v1/info` can be used for this. As of 0.9.1 and https://github.com/magneticio/vamp/issues/706 it is also possible to get just a Vamp JVM status: `/api/v1/info?for=jvm` without querying 3rd parties (less relevant for health status).
