### ISSUE TITLE
Use Adminrouter for Vamp UI in DC/OS

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#694]
To expose the Vamp dashboard on DC/OS, use the adminrouter: see https://github.com/dcos/adminrouter and https://github.com/dcos/adminrouter/blob/master/mesosstatecache.lua#L63 as an example

Relevant labels in Marathon are: DCOS_SERVICE_NAME, DCOS_SERVICE_SCHEME,  and DCOS_SERVICE_PORT_INDEX

good info on how to apply this: https://www.weave.works/my-first-dcos-app/

**Comment by iamtew** [comment]
See #662.

It has updated JSON files that will setup the appropriate proxy routes.
