### ISSUE TITLE
Vamp quickstart restarts on DC/OS AWS default installation

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#695]
When running default DC/OS on AWS (https://dcos.io/docs/1.7/administration/installing/cloud/aws/) and applying the VAMP DC/OS instructions, Vamp cannot install VGA on the public_node, and Vamp seems to restart itself every 30s. 

Vamp and at least one VGA should run on the public node to be able to accessible from the outside, unless we can use adminrouter to expose the dashboard as a public service, and make the VGA(+HAproxy) accessible from the outside using one of the default available DC/OS options

**Comment by iamtew** [comment]
Since magneticio/vamp#781 this is no longer an issue. Closing.
