### ISSUE TITLE
Lifecycle checks

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#72]
When deploying a series of containers, dependent on each other, Vamp checks if a container is running, before deploying the next one. However, the fact that the container is running does not automatically mean the service in the container is also available. For example, a tomcat instance takes quite some time to boot up, deploy and start applications.

A service can also fail, without taking down the container it is running in. In a perfect world, this should be handled inside the container itself. Until we live in a perfect world, Vamp could help, by checking the state of services delivered by the containers, during, and possibly after, deployment.

## Feature 1 - At deployment time
Check is the the actual service inside the container is available, before deploying dependent containers.

## Feature 2 - Health check
Kill and restart containers, when the service inside the container has failed.

**This needs to be further detailed, if deemed a valid feature**

FYI, this is how maestro-ng does it: https://maestro-ng.readthedocs.org/en/latest/#lifecycle-checks

**Comment by bsideup** [comment]
:+1: Vamp is awesome but it really missing health system :)

**Comment by dragoslav** [comment]
The easiest way to support this right now is to add hooks in DSL and use Vamp [workflows](https://github.com/magneticio/vamp/issues?utf8=%E2%9C%93&q=+is%3Aissue+label%3Aworkflows). I agree that this would be very beneficial feature.

**Comment by dragoslav** [comment]
https://github.com/magneticio/vamp/issues/709
