### ISSUE TITLE
Quickstart on fresh Debian 8 fails (with custom blueprint)

### ISSUE THREAD

**Issue by RubieV** [magneticio/vamp#721]
After starting a fresh Debian 8 VM on Softlayer, installing Docker using https://get.docker.com/, and starting VAMP 0.8.5 quickstart, sava(or similar blueprint) deployment fails.

I've included the Docker logs, it might be this specific exception:
```
[2016-07-26 21:01:21,790] INFO 127.0.0.1 - - [26/Jul/2016:21:01:21 +0000] "PUT //localhost:9090/v2/apps//b489c526-29fd-4377-ba23-1d210a91b0b8/hackable-1-0-0-d90e4ff813f0c8a92fec HTTP/1.1" 400 145 "-" "Dispatch/0.11.1-SNAPSHOT" 1 (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$c944d01c:qtp438493423-29)
21:01:21.791 | ERROR | io.vamp.common.http.RestClient$          |                                          | rsp [PUT http://localhost:9090/v2/apps//b489c526-29fd-4377-ba23-1d210a91b0b8/hackable-1-0-0-d90e4ff813f0c8a92fec] - unexpected status code: 400
21:01:21.793 | ERROR | io.vamp.common.notification.Notification |                                          | Container response error.
21:01:21.793 | ERROR | io.vamp.common.notification.Notification |                                          | {"message":"Please specify data in JSON format","details":"No content to map due to end-of-input\n at [Source: [B@1d1c9139; line: 1, column: 1]"}
io.vamp.common.http.RestClientException: {"message":"Please specify data in JSON format","details":"No content to map due to end-of-input\n at [Source: [B@1d1c9139; line: 1, column: 1]"}
        at io.vamp.common.http.RestClient$$anon$1.onCompleted(RestClient.scala:78) ~[vamp.jar:0.8.5]
        at com.ning.http.client.AsyncCompletionHandler.onCompleted(AsyncCompletionHandler.java:63) ~[vamp.jar:0.8.5]
```
...cut...

**Blueprint**
---
name: hackable
gateways:
  9050: hackable/port
clusters:
  hackable:
    routing:
      routes:
        hackable:1.0.0:
          weight: 0%  # weight in percentage
        hackable:1.1.0:
          weight: 100%
    services: # services is now a list of breeds
      -
        breed:
          name: hackable:1.0.0
          deployable: rubenvanvreeland/hackable-audited:latest
          ports:
            port: 80/http
        scale:
          cpu: 0.1
          memory: 64MB
          instances: 1
      -
        breed:
          name: hackable:1.1.0 # a new version of our service
          deployable: rubenvanvreeland/hackable-devops:latest
          ports:
            port: 80/http
        scale:
          cpu: 0.1
          memory: 64MB
          instances: 1

Complete log:
[vamp-bitsensor.txt](https://github.com/magneticio/vamp/files/385616/vamp-bitsensor.txt)

**Comment by RubieV** [comment]
Same issue running VAMP 0.8.0 quickstart with both sava and hackable.

**Comment by RubieV** [comment]
After running VAMP on bare metal, the quickstart works fine, my blueprint does not. The only difference I can spot is the port number of the breed and the latest tag. 

Both rubenvanvreeland/hackable-devops:latest and rubenvanvreeland/hackable-audited:latest are running fine in Docker with port 80 exposed.

**Comment by dragoslav** [comment]
Can you access Marathon UI on `localhost:9090`? Based on logs that should not be possible, also there is no Mesos slaves running. `DOCKER_HOST_IP` should be set to docker-machine IP or IP accessible by processes both from inside and outside of the container (`--net=host`).

**Comment by RubieV** [comment]
DOCKER_HOST_IP is set to the private network's ip, eth0. I do have Marathon running at 9090.

**Comment by RubieV** [comment]
Marathon says this:

Last Task Failure

Task id
    8cccf4ee-0c69-4e09-8e21-9a3b31cf14b7_hackable-1-1-0-6d6a5f48a72492ac9dff.49d9f82f-5405-11e6-8eee-0242c35bdd03 
State
    TASK_FAILED 
Message
    Failed to launch container: Unable to create image: Unexpected Env format for 'ContainerConfig.Env' 
Host
    10.68.171.71 
Timestamp
    2016-07-27T14:20:37.409Z (a few seconds ago)
Version
    2016-07-27T14:20:03.944Z (a few seconds ago)
Mesos Details
    link

**Comment by dragoslav** [comment]
When you go to Mesos UI DOCKER_HOST_IP:5050, do you see any Mesos slave?

**Comment by RubieV** [comment]
I have two slaves indeed. I also have frameworks: marathon and chronos-2.4.0

**Comment by olafmol** [comment]
Hi @RubieV could you try your blueprint with another Docker container? Maybe a very simple hello-world?

**Comment by RubieV** [comment]
10.68.171.71 is the IP used, which is the Softlayer internal network ip 
Seems to are connection issues, this is what Mesos says:
Failed to connect to slave 'undefined' on '10.68.171.71:5052'.
Potential reasons:
The slave's hostname, '10.68.171.71', is not accessible from your network
The slave's port, '5052', is not accessible from your network
The slave timed out or went offline

**Comment by RubieV** [comment]
The sava blueprint is working fine:
---
name: sava:1.0
gateways:
  9050: sava/port
clusters:
  sava:
    routing:
      routes:
        sava:1.0.0:
          weight: 50%  # weight in percentage
        sava:1.1.0:
          weight: 50%
    services: # services is now a list of breeds
      -
        breed:
          name: sava:1.0.0
          deployable: magneticio/sava:1.0.0
          ports:
            port: 8080/http
        scale:
          cpu: 0.2
          memory: 64MB
          instances: 1
      -
        breed:
          name: sava:1.1.0 # a new version of our service
          deployable: magneticio/sava:1.1.0
          ports:
            port: 8080/http
        scale:
          cpu: 0.2
          memory: 64MB
          instances: 1

**Comment by RubieV** [comment]
Mesos repeatedly logs:
I0727 20:20:32.368239   114 master.cpp:3947] Processing ACKNOWLEDGE call ab0953eb-4b10-4aa8-9362-122adb1fff29 for task 8cccf4ee-0c69-4e09-8e21-9a3b31cf14b7_hackable-1-0-0-d90e4ff813f0c8a92fec.914b3be0-5437-11e6-8eee-0242c35bdd03 of framework b95d1295-780f-40d2-9b5b-c47330861c24-0001 (marathon) at scheduler-946e3f1a-085f-4fad-a129-dc774150e187@37.58.72.23:33402 on slave b95d1295-780f-40d2-9b5b-c47330861c24-S1
I0727 20:20:32.368309   114 master.cpp:6511] Removing task 8cccf4ee-0c69-4e09-8e21-9a3b31cf14b7_hackable-1-0-0-d90e4ff813f0c8a92fec.914b3be0-5437-11e6-8eee-0242c35bdd03 with resources cpus(*):0.2; mem(*):512; ports(*):[31172-31172] of framework b95d1295-780f-40d2-9b5b-c47330861c24-0001 on slave b95d1295-780f-40d2-9b5b-c47330861c24-S1 at slave(1)@37.58.72.23:5051 (10.68.171.71)
I0727 20:20:32.368505   114 master.cpp:5350] Sending 1 offers to framework b95d1295-780f-40d2-9b5b-c47330861c24-0000 (chronos-2.4.0) at scheduler-f9dd0703-e5ad-43bc-ae0f-ee5b4659b7b8@37.58.72.23:34498
I0727 20:20:32.368626   114 master.cpp:5350] Sending 1 offers to framework b95d1295-780f-40d2-9b5b-c47330861c24-0001 (marathon) at scheduler-946e3f1a-085f-4fad-a129-dc774150e187@37.58.72.23:33402
I0727 20:20:32.368708   114 master.cpp:4789] Status update TASK_FAILED (UUID: 9c4e6150-fd1d-4751-8b0e-0af357683287) for task 8cccf4ee-0c69-4e09-8e21-9a3b31cf14b7_hackable-1-1-0-6d6a5f48a72492ac9dff.914b14cf-5437-11e6-8eee-0242c35bdd03 of framework b95d1295-780f-40d2-9b5b-c47330861c24-0001 from slave b95d1295-780f-40d2-9b5b-c47330861c24-S1 at slave(1)@37.58.72.23:5051 (10.68.171.71)
I0727 20:20:32.368736   114 master.cpp:4837] Forwarding status update TASK_FAILED (UUID: 9c4e6150-fd1d-4751-8b0e-0af357683287) for task 8cccf4ee-0c69-4e09-8e21-9a3b31cf14b7_hackable-1-1-0-6d6a5f48a72492ac9dff.914b14cf-5437-11e6-8eee-0242c35bdd03 of framework b95d1295-780f-40d2-9b5b-c47330861c24-0001
I0727 20:20:32.368799   114 master.cpp:6445] Updating the state of task 8cccf4ee-0c69-4e09-8e21-9a3b31cf14b7_hackable-1-1-0-6d6a5f48a72492ac9dff.914b14cf-5437-11e6-8eee-0242c35bdd03 of framework b95d1295-780f-40d2-9b5b-c47330861c24-0001 (latest state: TASK_FAILED, status update state: TASK_FAILED)
E0727 20:20:32.370374   116 process.cpp:1966] **Failed to shutdown socket with fd 25: Transport endpoint is not connected**

**Comment by olafmol** [comment]
So the sava containers can be deployed correctly? If so, could you check if you can run your hackable containers on a docker host without mesos/marathon?

**Comment by RubieV** [comment]
Both running fine with port 80 exposed. Available at https://hub.docker.com/r/rubenvanvreeland/ for test.

**Comment by olafmol** [comment]
Ok that's good. Did you test running the hackable containers through the Marathon UI?

**Comment by RubieV** [comment]
I'm currently trying that, to no avail. After deployment it is "waiting", then restarts deployment. Action is RestartApplication. 

## Mesos logs:
I0727 20:57:08.127756    33 http.cpp:503] HTTP GET for /master/slaves from 127.0.0.1:42324 with User-Agent='Dispatch/0.11.1-SNAPSHOT'
I0727 20:57:08.129005    28 http.cpp:503] HTTP GET for /master/frameworks from 127.0.0.1:42324 with User-Agent='Dispatch/0.11.1-SNAPSHOT'
I0727 20:57:09.699797    35 master.cpp:5350] Sending 1 offers to framework b7de93e1-5f01-4699-a970-342ced226f6f-0001 (chronos-2.4.0) at scheduler-78dfc68d-d879-4c4e-b490-7dd6736147b3@37.58.72.23:46668
I0727 20:57:09.701079    34 master.cpp:3673] Processing DECLINE call for offers: [ b7de93e1-5f01-4699-a970-342ced226f6f-O306 ] for framework b7de93e1-5f01-4699-a970-342ced226f6f-0001 (chronos-2.4.0) at scheduler-78dfc68d-d879-4c4e-b490-7dd6736147b3@37.58.72.23:46668
I0727 20:57:11.701160    34 master.cpp:5350] Sending 1 offers to framework b7de93e1-5f01-4699-a970-342ced226f6f-0001 (chronos-2.4.0) at scheduler-78dfc68d-d879-4c4e-b490-7dd6736147b3@37.58.72.23:46668
I0727 20:57:11.702441    28 master.cpp:3673] Processing DECLINE call for offers: [ b7de93e1-5f01-4699-a970-342ced226f6f-O307 ] for framework b7de93e1-5f01-4699-a970-342ced226f6f-0001 (chronos-2.4.0) at scheduler-78dfc68d-d879-4c4e-b490-7dd6736147b3@37.58.72.23:46668
I0727 20:57:12.168750    29 http.cpp:503] HTTP GET for /master/slaves from 127.0.0.1:42324 with User-Agent='Dispatch/0.11.1-SNAPSHOT'
I0727 20:57:12.169888    33 http.cpp:503] HTTP GET for /master/frameworks from 127.0.0.1:42324 with User-Agent='Dispatch/0.11.1-SNAPSHOT'
I0727 20:57:14.703677    30 master.cpp:5350] Sending 1 offers to framework b7de93e1-5f01-4699-a970-342ced226f6f-0001 (chronos-2.4.0) at scheduler-78dfc68d-d879-4c4e-b490-7dd6736147b3@37.58.72.23:46668
I0727 20:57:14.704942    28 master.cpp:3673] Processing DECLINE call for offers: [ b7de93e1-5f01-4699-a970-342ced226f6f-O308 ] for framework b7de93e1-5f01-4699-a970-342ced226f6f-0001 (chronos-2.4.0) at scheduler-78dfc68d-d879-4c4e-b490-7dd6736147b3@37.58.72.23:46668
I0727 20:57:16.127216    29 http.cpp:503] HTTP GET for /master/slaves from 127.0.0.1:42324 with User-Agent='Dispatch/0.11.1-SNAPSHOT'
I0727 20:57:16.128360    33 http.cpp:503] HTTP GET for /master/frameworks from 127.0.0.1:42324 with User-Agent='Dispatch/0.11.1-SNAPSHOT'
I0727 20:57:16.704900    34 master.cpp:5350] Sending 1 offers to framework b7de93e1-5f01-4699-a970-342ced226f6f-0001 (chronos-2.4.0) at scheduler-78dfc68d-d879-4c4e-b490-7dd6736147b3@37.58.72.23:46668
I0727 20:57:16.706185    30 master.cpp:3673] Processing DECLINE call for offers: [ b7de93e1-5f01-4699-a970-342ced226f6f-O309 ] for framework b7de93e1-5f01-4699-a970-342ced226f6f-0001 (chronos-2.4.0) at scheduler-78dfc68d-d879-4c4e-b490-7dd6736147b3@37.58.72.23:46668
I0727 20:57:19.707320    32 master.cpp:5350] Sending 1 offers to framework b7de93e1-5f01-4699-a970-342ced226f6f-0001 (chronos-2.4.0) at scheduler-78dfc68d-d879-4c4e-b490-7dd6736147b3@37.58.72.23:46668
I0727 20:57:19.708745    31 master.cpp:3673] Processing DECLINE call for offers: [ b7de93e1-5f01-4699-a970-342ced226f6f-O310 ] for framework b7de93e1-5f01-4699-a970-342ced226f6f-0001 (chronos-2.4.0) at scheduler-78dfc68d-d879-4c4e-b490-7dd6736147b3@37.58.72.23:46668

## VAMP logs
[2016-07-27 20:59:06,792] INFO Received resource offers (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:82)
[2016-07-27 20:59:06,792] INFO No tasks scheduled or next task has been disabled.
 (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:131)
[2016-07-27 20:59:06,792] INFO Declining unused offers. (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:89)
[2016-07-27 20:59:06,792] INFO Declined unused offers with filter refuseSeconds=5.0 (use --decline_offer_duration to reconfigure) (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:97)
[2016-07-27 20:59:07,755] INFO 127.0.0.1 - - [27/Jul/2016:20:59:07 +0000] "GET //localhost:9090/v2/apps?embed=apps.tasks HTTP/1.1" 200 1081 "-" "Dispatch/0.11.1-SNAPSHOT"  (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$c944d01c:qtp2089578710-83)
[2016-07-27 20:59:08,134] INFO 127.0.0.1 - - [27/Jul/2016:20:59:08 +0000] "GET //localhost:9090/v2/info HTTP/1.1" 200 872 "-" "Dispatch/0.11.1-SNAPSHOT"  (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$c944d01c:qtp2089578710-88)
2016-07-27 20:59:08,134 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@197] - Accepted socket connection from /127.0.0.1:44746
2016-07-27 20:59:08,135 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@827] - Processing stat command from /127.0.0.1:44746
2016-07-27 20:59:08,135 [myid:] - INFO  [Thread-207:NIOServerCnxn$StatCommand@663] - Stat command output
2016-07-27 20:59:08,135 [myid:] - INFO  [Thread-207:NIOServerCnxn@1007] - Closed socket connection for client /127.0.0.1:44746 (no session established for client)
[2016-07-27 20:59:08,145] INFO 127.0.0.1 -  -  [27/Jul/2016:20:59:08 +0000] "GET /scheduler/jobs HTTP/1.1" 200 2 "-" "Dispatch/0.11.1-SNAPSHOT" (mesosphere.chaos.http.ChaosRequestLog:15)
[2016-07-27 20:59:09,109] INFO 82.173.116.165 - - [27/Jul/2016:20:59:09 +0000] "GET //37.58.72.23:9090/v2/deployments HTTP/1.1" 200 290 "http://37.58.72.23:9090/ui/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"  (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$c944d01c:qtp2089578710-85)
[2016-07-27 20:59:09,257] INFO 82.173.116.165 - - [27/Jul/2016:20:59:09 +0000] "GET //37.58.72.23:9090/v2/apps//8cccf4ee-0c69-4e09-8e21-9a3b31cf14b7/hackable-1-1-0-6d6a5f48a72492ac9dff?embed=app.taskStats HTTP/1.1" 404 108 "http://37.58.72.23:9090/ui/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"  (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$c944d01c:qtp2089578710-34)
[2016-07-27 20:59:09,259] INFO 82.173.116.165 - - [27/Jul/2016:20:59:09 +0000] "GET //37.58.72.23:9090/v2/queue HTTP/1.1" 200 1003 "http://37.58.72.23:9090/ui/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"  (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$c944d01c:qtp2089578710-29)
[2016-07-27 20:59:09,259] INFO 82.173.116.165 - - [27/Jul/2016:20:59:09 +0000] "GET //37.58.72.23:9090/v2/deployments HTTP/1.1" 200 290 "http://37.58.72.23:9090/ui/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"  (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$c944d01c:qtp2089578710-82)
[2016-07-27 20:59:09,265] INFO 127.0.0.1 -  -  [27/Jul/2016:20:59:09 +0000] "GET /scheduler/jobs HTTP/1.1" 200 2 "-" "Dispatch/0.11.1-SNAPSHOT" (mesosphere.chaos.http.ChaosRequestLog:15)
[2016-07-27 20:59:09,793] INFO Received resource offers (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:82)
[2016-07-27 20:59:09,794] INFO No tasks scheduled or next task has been disabled.
 (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:131)
[2016-07-27 20:59:09,794] INFO Declining unused offers. (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:89)
[2016-07-27 20:59:09,794] INFO Declined unused offers with filter refuseSeconds=5.0 (use --decline_offer_duration to reconfigure) (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:97)
[2016-07-27 20:59:10,755] INFO 127.0.0.1 - - [27/Jul/2016:20:59:10 +0000] "GET //localhost:9090/v2/apps?embed=apps.tasks HTTP/1.1" 200 1081 "-" "Dispatch/0.11.1-SNAPSHOT"  (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$c944d01c:qtp2089578710-92)

**Comment by olafmol** [comment]
Ok, did you fix that slave issue mentioned above? If there aren't enough resources in the cluster then Marathon will not deploy the container.

**Comment by RubieV** [comment]
## Resources
CPUs	Mem	Disk
Total	4	8.0 GB	128.0 GB
Used	0	0 B	0 B
Offered	0	0 B	0 B
Idle	4	8.0 GB	128.0 GB

## ps aux
root       396  0.0  0.0  19620  3300 ?        S    15:44   0:00 bash /usr/local/marathon/mesos-master.sh
root       397  0.0  0.0  19628  3332 ?        S    15:44   0:00 bash /usr/local/marathon/mesos-slave.sh 2
root       411  0.2  0.3 1127984 31912 ?       Sl   15:44   0:08 mesos-master --registry=in_memory --cluster=VAMP --quorum=1 --zk=zk://127.0.0.1:2181/mesos --work_dir=/var/lib/mesos --hostname=37.58.72.23 --log_dir=/var/log/mesos
root       539  0.4  0.3 962736 30328 ?        Sl   15:44   0:15 mesos-slave --launcher=posix --containerizers=docker,mesos --executor_registration_timeout=5mins --docker_stop_timeout=10secs --isolation=cgroups/cpu,cgroups/mem --master=zk://127.0.0.1:2181/mesos --work_dir=/var/run/mesos/slave2 --log_dir=/var/log/mesos/slave2 --port=5052 --resources=cpus(*):2; mem(*):4096; disk(*):65536; ports(*):[31000-32000] --hostname=37.58.72.23
root       579  1.2  5.6 6466868 457876 ?      Sl   15:44   0:49 java -Djava.library.path=/usr/local/lib:/usr/lib:/usr/lib64 -Djava.util.logging.SimpleFormatter.format=%2$s%5$s%6$s%n -Xmx512m -cp /usr/bin/marathon mesosphere.marathon.Main --master zk://37.58.72.23:2181/mesos --zk zk://37.58.72.23:2181/marathon --task_launch_timeout 300000 --http_port 9090 --hostname 37.58.72.23
root       580  2.1  4.0 6234412 332392 ?      Sl   15:44   1:22 java -Djava.library.path=/usr/local/lib:/usr/lib64:/usr/lib -Djava.util.logging.SimpleFormatter.format=%2$s %5$s%6$s%n -Xmx512m -cp /usr/bin/chronos org.apache.mesos.chronos.scheduler.Main --http_port 4400 --zk_hosts localhost:2181 --master zk://127.0.0.1:2181/mesos --hostname 37.58.72.23
root       648  0.0  0.0  19628  3384 ?        S    15:44   0:00 bash /usr/local/marathon/mesos-slave.sh 1
root       668  0.4  0.3 962736 32020 ?        Sl   15:44   0:15 mesos-slave --launcher=posix --containerizers=docker,mesos --executor_registration_timeout=5mins --docker_stop_timeout=10secs --isolation=cgroups/cpu,cgroups/mem --master=zk://127.0.0.1:2181/mesos --work_dir=/var/run/mesos/slave1 --log_dir=/var/log/mesos/slave1 --port=5051 --resources=cpus(*):2; mem(*):4096; disk(*):65536; ports(*):[31000-32000] --hostname=37.58.72.23
root      4201  0.0  0.0  15292  2060 pts/0    S+   16:49   0:00 grep --color=auto mesos

**Comment by RubieV** [comment]
Deployment failed after two hours of retrying with Marathon showing the following exception:
```
Task id
    8cccf4ee-0c69-4e09-8e21-9a3b31cf14b7_hackable-1-1-0-6d6a5f48a72492ac9dff.1c3b6053-5432-11e6-8eee-0242c35bdd03 
State
    TASK_FAILED 
Message
    Failed to launch container: Unable to create image: Unexpected Env format for 'ContainerConfig.Env' 
Host
    10.68.171.71 
Timestamp
    2016-07-27T19:41:28.467Z (4 hours ago)
Version
    2016-07-27T14:20:03.944Z (9 hours ago)
```

**Comment by olafmol** [comment]
This might be related to this Mesos issue: https://issues.apache.org/jira/browse/MESOS-4587 or https://issues.apache.org/jira/browse/MESOS-4594
It seems Mesos is using Docker inspect to check docker environment (ENV) variables. Are you using some typical ones in your container, f.e. with an equal sign etc??

**Comment by RubieV** [comment]
I saw the issue, but it seems not applicable?

## Dockerfile
`FROM tutum/lamp:latest
RUN rm -rf /app
COPY ./app /app
EXPOSE 80
CMD ["/run.sh"]`

## Dockerfile tutum/lamp
`FROM ubuntu:trusty
MAINTAINER Fernando Mayo <fernando@tutum.co>, Feng Honglin <hfeng@tutum.co>

# Install packages
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
  apt-get -y install supervisor git apache2 libapache2-mod-php5 mysql-server php5-mysql pwgen php-apc php5-mcrypt && \
  echo "ServerName localhost" >> /etc/apache2/apache2.conf

# Add image configuration and scripts
ADD start-apache2.sh /start-apache2.sh
ADD start-mysqld.sh /start-mysqld.sh
ADD run.sh /run.sh
RUN chmod 755 /*.sh
ADD my.cnf /etc/mysql/conf.d/my.cnf
ADD supervisord-apache2.conf /etc/supervisor/conf.d/supervisord-apache2.conf
ADD supervisord-mysqld.conf /etc/supervisor/conf.d/supervisord-mysqld.conf

# Remove pre-installed database
RUN rm -rf /var/lib/mysql/*

# Add MySQL utils
ADD create_mysql_admin_user.sh /create_mysql_admin_user.sh
RUN chmod 755 /*.sh

# config to enable .htaccess
ADD apache_default /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite

# Configure /app folder with sample app
RUN git clone https://github.com/fermayo/hello-world-lamp.git /app
RUN mkdir -p /app && rm -fr /var/www/html && ln -s /app /var/www/html

#Environment variables to configure php
ENV PHP_UPLOAD_MAX_FILESIZE 10M
ENV PHP_POST_MAX_SIZE 10M

# Add volumes for MySQL 
VOLUME  ["/etc/mysql", "/var/lib/mysql" ]

EXPOSE 80 3306
CMD ["/run.sh"]`

**Comment by olafmol** [comment]
It might be an option to first install DC/OS (which includes mesos/marathon) and see if you can spin up your docker container on DC/OS: https://dcos.io/install/

**Comment by RubieV** [comment]
Closing this one, I don't see a way forward without being able to debug that is time efficient. Running VAMP on Vagrant DC/OS now.
