### ISSUE TITLE
DC/OS Vamp clean install throws 500 on REST

### ISSUE THREAD

**Issue by RubieV** [magneticio/vamp#723]
On a fresh install, VAMP will throw HTTP 500 on any request:

GET http://localhost:9090/api/v1/breeds
500: {"message":"The request content was malformed."}

GET http://localhost:9090/api/v1/blueprints
500: {"message":"The request content was malformed."}

GET http://localhost:9090/api/v1/deployments
500: {"message":"The request content was malformed."}

This is solved by deploying a blueprint.

**Comment by RubieV** [comment]
ES/Metrics are still unable to load:

POST /api/v1/events/get HTTP/1.1
Host: localhost:9090
Connection: keep-alive
Content-Length: 137
Origin: http://localhost:9090
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Content-type: application/json
Accept: */*
Referer: http://localhost:9090/
Accept-Encoding: gzip, deflate
Accept-Language: nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4
Cookie: dcos-acs-auth-cookie=abc123; dcos-acs-info-cookie=abc123; mp_3dc73f826819c8e11d0d9898ca4291c8_mixpanel=%7B%22distinct_id%22%3A%20%2215631fcc2db254-07b7251b28e65a-3f65450b-151800-15631fcc2dcb0%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D; mp_mixpanel__c=0; PHPSESSID=2d335b56pja7ssr3sk2e7a9ft5; security=impossible

{"tags":["gateways","gateways:a3402e5d_0010_47d5_9a42_169e490599f3_9051____","metrics","metrics:responseTime"],"timestamp":{"lte":"now"}}

**Comment by dragoslav** [comment]
What happened is that ES indices (aliases etc.) are not set properly. This is done by Vamp during startup - module that does this will be eventually moved out to separate installer. Reason for this could be that Vamp started before Elasticsearch was ready.
So, in case of reading artifacts there will be an error until index is created - done by ES on first document. In case of metrics, without aliases, no search can be performed.

**Comment by RubieV** [comment]
With dcos ES is installed (and I assume started) before vamp. I heard 090
will bring more stability. Happy to debug and ship logs!

Op wo 3 aug. 2016 23:40 schreef dragoslav <notifications@github.com>:

**Comment by olafmol** [comment]
@RubieV is this still relevant with the latest Vamp versions? Closing for now, please re-open if still an issue.
