### ISSUE TITLE
Remove /reset endpoint

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#735]
There is no need for this anymore - UI can be used for quick cleanup.

**Comment by olafmol** [comment]
I use this API call quiet often for demo and debug purposes and would like to have it available.

**Comment by dragoslav** [comment]
`/reset` was implemented as a workaround and had these issues:
- not removing workflows
- not removing gracefully gateways - multiple calls in short period could cause problems
- not removing other artifacts

Also, it's very uncommon to find this feature in mature products (API). On the other hand something like that can be found in clients (CLI, UI), e.g. undeploy all etc.

Suggestion 1:
- part of UI - `reset all` button, or `undeploy all`, `reschedule all` (workflows)
- in case of presentation/debug you would need to make no more than few clicks and it can be even one

Suggestion 2:
- proper backend implementation - it should be part of `lifter` module - Vamp installation, upgrade etc.
- full reset should also drop index/db

**Comment by olafmol** [comment]
agreed. It might be good to have a workflow or lifter module that can do an INIT state from a running deploy, basically removing and cleaning everything first. I agree we don't need to build it in the API
