### ISSUE TITLE
When removing filter-condition string through UI the routing should not stay effective

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#739]
When doing steps 1 and 2 of the quickstart guide, and then adding a filter-conditon "User-agent = Chrome" with 100% strength to the new Sava 1.1 version, this works as expected.

But when removing the filter-condition string using the UI, the filter-condition stays effective, disregarding condition-strenght settings.

It seem to have something to do with the fact that without any condition (ie initial state) it say "null" as a condition, while after removing the string through the UI it becomes condition: "" instead of null. Confirming that editing the gateway YAML and replacing to null makes the routing behave as expected again.

[{
    "name": "sava/sava/port",
    "lookup_name": "dbf8e0353af7d589a3fd7098df83a6bf303eff87",
    "port": "40000/http",
    "inner": true,
    "service": {
        "host": "192.168.99.100",
        "port": "40000/http"
    },
    "deployed": true,
    "sticky": "none",
    "virtual_hosts": ["port.sava.sava.vamp"],
    "routes": {
        "sava/sava/sava:1.0.0/port": {
            "weight": "100%",
            "balance": "default",
            "condition": null,
            "condition_strength": "0%",
            "rewrites": [],
            "instances": [{
                "name": "sava_sava-1-0-0-6fd83b1fd01f7dd9eb7f.506534da-6480-11e6-b1e2-02428a519afa",
                "host": "192.168.99.100",
                "port": 31741
            }
            ]
        },
        "sava/sava/sava:1.1.0/port": {
            "weight": "0%",
            "balance": "default",
            "condition": {
                "condition": ""
            },
            "condition_strength": "100%",
            "rewrites": [],
            "instances": [{
                "name": "sava_sava-1-1-0-2e2fc6ab8a1cdbe79dc3.8274c21b-6480-11e6-b1e2-02428a519afa",
                "host": "192.168.99.100",
                "port": 31096
            }
            ]
        }
    }
}, {
    "name": "sava/9050",
    "lookup_name": "4877cc92ae2ba1bbc96f0aea0572b725ce47d9fb",
    "port": "9050",
    "inner": false,
    "service": {
        "host": "192.168.99.100",
        "port": "9050/http"
    },
    "deployed": true,
    "sticky": "none",
    "virtual_hosts": ["9050.sava.vamp"],
    "routes": {
        "sava/sava/port": {
            "weight": "100%",
            "balance": "default",
            "condition": null,
            "condition_strength": "0%",
            "rewrites": [],
            "instances": [{
                "name": "sava/sava/port",
                "port": 40000
            }
            ]
        }
    }
}
]

**Comment by dragoslav** [comment]
Do you suggest that an empty string should be interpreted as no value (`null`)? That is fine, or this issue is regarded as a UI bug?

**Comment by olafmol** [comment]
i think interpreting an empty condition string as (null) would be the most robust solution.
