### ISSUE TITLE
Give clearer when if quickstart is running 

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#742]
right now we see a lot of verbose messages, warnings etc from all quickstart components, and its not clear when Vamp is up&running correctly. It would be more convenient if the default logging level would be much less info, and only show either errors or succes-info, and also show a clear message that Vamp is up & running and where to point the browser to, all in the terminal.

**Comment by dragoslav** [comment]
Most of logs are not from Vamp but Mesos, Marathon etc. so disabling logging of all of them would work in this case.

**Comment by dragoslav** [comment]
https://github.com/magneticio/vamp-docker/commit/74847b4c123c8184d0d3262f0a67cd4c7ddc7e23 @olafmol you need to rebuild clique-* images first and then the quick start.
