### ISSUE TITLE
haproxy sending wrong PROXY to backend unix socket

### ISSUE THREAD

**Issue by harmw** [magneticio/vamp#759]
I'm loading the haproxy bits from _Consul_ into our own haproxy config, this all works out fine using _consul-template_ but it produces the following error when trying a **GET** against my newly deployed service:

```
2016/09/15 22:07:52 socat[73] E write(6, 0x7f58ab35a020, 187): Broken pipe
> 2016/09/15 22:07:54.742424  length=15 from=0 to=14
PROXY UNKNOWN\r
< 2016/09/15 22:07:54.742565  length=187 from=0 to=186
HTTP/1.0 400 Bad request\r
Cache-Control: no-cache\r
Connection: close\r
Content-Type: text/html\r
\r
<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>
```

This was extracted using `socat`:
```
socat -t100 -v UNIX-LISTEN:/usr/local/vamp/d79bc7302e19bc65e3a9977c17c9d91ef15532d0.sock,mode=777,reuseaddr,fork UNIX-CONNECT:/usr/local/vamp/d79bc7302e19bc65e3a9977c17c9d91ef15532d0.sock.orig
```

Obviously, the **accept-proxy** that's configured on the local socket listener isn't playing nice with the server descriptor that sets the **send-proxy**. Anything specific I could be missing from the original Vamp haproxy.cfg? IIRC it should be enough to just set accept-proxy and send-proxy.

**Comment by dragoslav** [comment]
How easy is for you to validate that configuration? Template file (default is https://github.com/magneticio/vamp/blob/master/gateway_driver/src/main/resources/io/vamp/gateway_driver/haproxy/template.twig) can be overriden by `vamp.gateway-driver.haproxy.template` configuration entry or by `VAMP_GATEWAY_DRIVER_HAPROXY_TEMPLATE` environment variable. Only problem is that URL can't be used, so if you run Vamp Docker image then you would need to build a new one (e.g. based on your current).

**Comment by harmw** [comment]
Ah great, Ill take a look at the vamp haproxy.cfg to make sure mine isn't missing anything.

**Comment by harmw** [comment]
Looks like I also need to look at https://github.com/magneticio/vamp-gateway-agent/blob/master/haproxy.basic.cfg.

**Comment by dragoslav** [comment]
That is the default base configuration if VGA is used, so it may help as well.

**Comment by harmw** [comment]
crap, might be I've been falsely alarmed by haproxy checking the backends....
```
> 2016/09/16 11:02:30.447619  length=224 from=0 to=223
PROXY TCP4 172.17.0.5 172.17.0.5 56316 40000\r
GET / HTTP/1.1\r
Host: canary.blaze\r
User-Agent: curl/7.50.2\r
Accept: */*\r
X-Forwarded-For: 172.17.42.1\r
Connection: close\r
X-Forwarded-Port: 2002\r
X-Forwarded-For: 172.17.0.5\r
\r
< 2016/09/16 11:02:30.447942  length=212 from=0 to=211
HTTP/1.0 503 Service Unavailable\r
Cache-Control: no-cache\r
Connection: close\r
Content-Type: text/html\r
\r
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```
Doesn't look like a problem, so soemthing else must be causing the 503.

**Comment by harmw** [comment]
my backend block is missing servers 👎 💩
