### ISSUE TITLE
Configuring a log target per vhost

### ISSUE THREAD

**Issue by harmw** [magneticio/vamp#760]
The config that's put into Consul is fitted with a `log-format` which gets applied on each vhost frontend. We have defined a single log endpoint, but that's not fitted for this format - it's configured to receive logging from some other frontend definitions in our haproxy.cfg.

Is it possible to have a log target specified per frontend, just like it's done with the log-format?

```
[..]
# HAProxy 1.6, Frontends & Backends managed by Vamp

# Virtual hosts

frontend virtual_hosts

  bind 0.0.0.0:2002
  mode http

  option httplog
  log-format {\"ci\":\"%ci\",\"cp\":%cp,\"t\":\"%t\",\"ft\":\"%ft\",\"b\":\"%b\",\"s\":\"%s\",\

  # destination: blaze-canary-service/canary
  acl b0b7a12984f9cd10 hdr(host) -i canary.blaze-canary-service.vamp
  use_backend 89f26c345ee42c0c9bb9f6dc4f1cef13f705fae8  if b0b7a12984f9cd10

  # destination: blaze-canary-service/canary
  acl 204e52c1ce4989b4 hdr(host) -i canary.blaze
  use_backend 89f26c345ee42c0c9bb9f6dc4f1cef13f705fae8  if 204e52c1ce4989b4
[..]
```

This is what we have at the _default_ level:

```
log 172.17.42.1:5170 local0 warning
```

With fluentd listening on the other end, but I'd like to configure a different endpoint for VAMP's haproxy stuff.

**Comment by dragoslav** [comment]
Would you use the same value for all frontends? In that case you could just override the default HAProxy template.

**Comment by olafmol** [comment]
@harmw you can update the template in v093 and change these things. Closing it for now, please re-open if needed.
