### ISSUE TITLE
Create local DNS lookup for local resolving of virtual hostnames in docker bridge mode

### ISSUE THREAD

**Issue by iamtew** [magneticio/vamp#773]
_From @olafmol on September 27, 2016 11:54_

we need to have a DNS resolver for virtual hostnames that can resolve from within a docker BRIDGE container to the correct gateway IP, and can be updated dynamically when Vamp adds/changes/removes gateways with virtual hostnames. 

Possible candidates to investigate/trial: DNSMasq

_Copied from original issue: magneticio/Vamp-090-DCOS-1.8-integration#10_

**Comment by iamtew** [comment]
Is this specifically for DC/OS or more in general? If it's a general improvement, we should move this ticket away from this project and in to the main Vamp project.

In DC/OS Mesos-DNS is usable from within the Docker bridge network:
```
core@ip-10-0-1-153 ~ $ docker exec 8fcb32693e47 ping -c3 leader.mesos
PING leader.mesos (10.0.6.103): 56 data bytes
64 bytes from 10.0.6.103: seq=0 ttl=63 time=0.314 ms
64 bytes from 10.0.6.103: seq=1 ttl=63 time=0.280 ms
64 bytes from 10.0.6.103: seq=2 ttl=63 time=0.322 ms

--- leader.mesos ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.280/0.305/0.322 ms
```

**Comment by olafmol** [comment]
How to test a working implementation of this:

- create a Vamp gateway with a custom virtual host name (documented in http://vamp.io/documentation/using-vamp/virtual-hosts/)
- deploy a container in BRIDGE mode on some cluster node
- the service inside the container should be able to resolve the custom virtual host name to the nearest HAProxy instance (probably the one running on the same node, i.e. localhost)

**Comment by iamtew** [comment]
Clarification of issue:

The VGA's HAproxy virtual-hosts should also be resolveable hostnames that points to the VGA's, something like a round-robin DNS record. 

Ugly work arounds include adding the hostname to `/etc/hosts`, this is fragile and we can't expect to have this control over the container, or have the application set the `Host` header accordingly:

```bash
$ curl --resolve awesome.example.vamp:80:${VGA_IP} http://awesome.example.vamp
```

```
$ telnet ${VGA_IP} 80
GET / HTTP/1.1
Host: awesome.example.vamp
<Return>
<Return>
```

Proper solution would have to manage our own DNS zone, populating it with the same information we use to populate the HAproxy configuration.

Both Kubernetes and Rancher have internal DNS services where we should be able to add arbitrary records, but this is yet to be confirmed. Also according to @olafmol this might not be necessary in those setups.

In the case of DC/OS we have Mesos-DNS but we can't manage our own zones with it. Running a Vamp service that hosts DNS should be fairly trivial, however to expose it through the wider cluster have some challenges, such as not being able to update the Mesos-DNS configuration to use our own NS as an upstream resolver, from inside Vamp.

*Everything's a freaking DNS problem...*

**Comment by olafmol** [comment]
- [ ] run DNSMasq container in docker HOST mode on a single node (1 instance)
- [ ] populate DNSMasq with all VHOSTS information
- [ ] keep DNSMasq VHOSTS information up to date (reading/polling for updates
- [ ] use Runner recipe http with dependencies with virtual host name to test
- [ ] package it for automatic deployment when Vamp (re)starts

**Comment by iamtew** [comment]
Changes has been pushed to the dnsmasq branch on the VGA project, https://github.com/magneticio/vamp-gateway-agent/tree/dnsmasq

Need to fully test and verify before merging in to master.

**Comment by iamtew** [comment]
Functionality has been merged in to master branch: https://github.com/magneticio/vamp-gateway-agent/commit/ac23c396f219297c950400cee69aa25a6309744d

Following environment can be configured in the VGA breed to enable this functionality:
VAMP_VGA_DNS_ENABLE - Set to non-empty value to enable
VAMP_VGA_DNS_PORT   - Any number will be used as listening port

**Comment by iamtew** [comment]
Updated VGA readme to include this functionality: https://github.com/magneticio/vamp-gateway-agent/commit/e4062f9fc7c5a9e0f82401fdba877726fdcfda20
