### ISSUE TITLE
Improve blueprint save validation message for dependencies and environment vars

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#777]
When saving a blueprint that refers to environment variables but doesn't have a "dependencies" entity set, there is a validation error. This error doesn't tell the reason why the blueprint cannot be saved. It should say that there is a reference to environment variables but no dependency is set, to give the user more guidance in the reason for the validation error.

**Comment by dragoslav** [comment]
Addition to this: https://github.com/magneticio/vamp/issues/802
