### ISSUE TITLE
adding a directive to clean persistence data when deploying Vamp

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#778]
when (re)installing Vamp (f.e. using documentation/installation/dcos/) it seems to ignore the "VAMP_LIFTER_ARTIFACT_FILES" configuration, and seems to pick up the persistence data from the last installation. Ie. not setting the VGA workflow in the artifact files is ignored and the VGA workflow is still started. It would be helpful to have a way to reset/clean the persistence data when starting Vamp

**Comment by dragoslav** [comment]
And then when Vamp it's restarted by for instance Marathon all data should be reset? Lifter add aliases/artifacts etc. and if they already exists nothing will be touched:
- Vamp installer/lifter as an external app - you could also use it for resetting the state 
- do it manually, e.g. by script

**Comment by olafmol** [comment]
closing it, moving it to an installer tool
