### ISSUE TITLE
On DC/OS 1.7 the VGA throw errors

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#779]
it works in DC/OS 1.8, but on 1.7 i see this error in the VGA log:

12:30:07.711 main INFO ==> Reading from ZooKeeper path /vamp/haproxy/1.6: zk: node does not exist [0m]

**Comment by dragoslav** [comment]
It's an info message not an error - VGA usually starts before Vamp because Vamp waits for ES, so VGA can't read HAProxy configuration because it's not yet created.

**Comment by olafmol** [comment]
The error in DC/OS 1.7 is related to Vamp-Katana and the fact that Vamp Katana/0.9.1 uses zookeeper for persistence storage. Therefore closing this issue.
