### ISSUE TITLE
Create single-click install Vamp universe package for DC/OS 1.8

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#781]
create a single container with everything inside (including the new Vamp ES package) so we can install a Vamp setup with one click through the DC/OS 1.8 universe

**Comment by iamtew** [comment]
Potentially useful: https://gist.github.com/mhausenblas/bb967625088902874d631eaa502573cb

**Comment by iamtew** [comment]
https://github.com/mesosphere/universe/pull/804

**Comment by iamtew** [comment]
According to @ryadav88 the pull request should be reviewed today.

**Comment by iamtew** [comment]
Updated [pull request 804](https://github.com/mesosphere/universe/pull/804) for Universe package.

Added examples documentation as requested under: https://github.com/dcos/examples/pull/8

**Comment by iamtew** [comment]
Pull requests have been closed, Vamp is now available in DC/OS Universe.

**Comment by olafmol** [comment]
closing this as current DCOS package implementation doesn't enable us to spin up dependencies like custom ES before Vamp itself. Will need to re-investigate when new versions of DCOS universe are released.
