### ISSUE TITLE
GUIDES "3. Splitting the monolith into services" doesn't work?

### ISSUE THREAD

**Issue by bufferings** [magneticio/vamp#786]
sava-frontend-1-2-0 stay "Waiting" status on Marathon.

I deployed apps by this blueprint.
http://vamp.io/documentation/guides/getting-started-tutorial/3-splitting-services/

The result is like this:
![2016-10-10_0745](https://cloud.githubusercontent.com/assets/763849/19224268/86816edc-8ebd-11e6-9380-6d1fa2ab3951.png)

Both backends seem to be deployed, but frontend doesn't finish deploying.

Then, I checked "Deployment" on Vamp and found Environment reference doesn't seem to work?
![2016-10-10_0749](https://cloud.githubusercontent.com/assets/763849/19224296/2665220e-8ebe-11e6-963c-795ffc43f349.png)

Could you please tell me what to do?

## my environment
Vamp Info

```
Hi, I'm Vamp! How are you?

Running since
21:54:10 09-10-2016

Version:
0.9.0-41-gcbf3f55

UI version:
0.9.0-10-ga8b48ff

Persistence:
key-value

Key value store:
zookeeper

Gateway driver:
haproxy 1.6.x

Container driver:
marathon

Workflow driver:
marathon
```

Marathon Version 1.1.2-dcos-1

on DC/OS v.1.7.3

on Azure Container Service

**Comment by bufferings** [comment]
Just FYI, I used this scripts to install Vamp on DC/OS, because the official site's script doesn't work.

#662

**Comment by olafmol** [comment]
Could you check in mesos what the the reason is that the container is not starting? It could be a lack of mesos resources maybe?

**Comment by bufferings** [comment]
Ah! Thank you. The CPU of private agent is 100% used.

**Comment by olafmol** [comment]
Good to hear! If there's anything else we can help with let us know!
