### ISSUE TITLE
host and port reference doesn't work in GUIDES 3

### ISSUE THREAD

**Issue by bufferings** [magneticio/vamp#788]
Regarding this tutorial:
http://vamp.io/documentation/guides/getting-started-tutorial/3-splitting-services/

After I succeeded to deploy apps thanks to #786 , I found that the front app didn't seem to call backend services. I thought the cause was host and port reference, because both Vamp and Marathon have invalid environment variables like this: 
![2016-10-11_2230](https://cloud.githubusercontent.com/assets/763849/19272154/6931773c-9002-11e6-8731-1cd7988e6fec.png)

Then I guessed several things and finally following reference in blueprint works fine.
```
# BACKEND_1: http://$backend1.host:$backend1.ports.port/api/message
BACKEND_1: http://$backend1.hosts.host:$backend1.ports.webport/api/message
```

![2016-10-11_2239](https://cloud.githubusercontent.com/assets/763849/19272465/9c2efd20-9003-11e6-8b9c-3c203e8f0c54.png)

My question is whether this is the right way or not. Or should I follow other solution?
I mean, is it right to use `$backend1.hosts.host` instead of `$backend1.host` and use `$backend1.ports.webport` instead of `$backend1.ports.port`? If it's right, I'm glad if you kindly update the tutorial.

## my environment
Vamp Info

```
Hi, I'm Vamp! How are you?

Running since
21:54:10 09-10-2016

Version:
0.9.0-41-gcbf3f55

UI version:
0.9.0-10-ga8b48ff

Persistence:
key-value

Key value store:
zookeeper

Gateway driver:
haproxy 1.6.x

Container driver:
marathon

Workflow driver:
marathon
```

Marathon Version 1.1.2-dcos-1

on DC/OS v.1.7.3

on Azure Container Service

**Comment by dragoslav** [comment]
Hi @bufferings  thanks, you are right. We have recently renamed `port` to `webport` to make it less confusing (it's a custom name) and we missed that update. `http://$backend1.host:$backend1.ports.webport/api/message` should work (you don't need additional `hosts`. These blueprints are not part of our automated tests like this one https://github.com/magneticio/vamp-runner/blob/master/recipes/http-deployment-dependency/deploy.yml

**Comment by olafmol** [comment]
updated in all relevant YAML files

**Comment by olafmol** [comment]
reponing, as on DCOS (1.8) with Vamp Katana (0.9.0-41-gcbf3f55) the ENV var's are correctly set, but the backend services don't seem to receive any requests. With the same blueprint on Vamp Docker quickstart on a local linux machine, this works fine

**Comment by bufferings** [comment]
Thank you @dragoslav @olafmol 

I'm sorry, but In this morning(JST) I told olafmol that $backend1.host doesn't work, but now I tried it again and found it works. Maybe I mistakenly update deployment yaml?

Thank you for your support. Now your tutorial works perfectly.

**Comment by olafmol** [comment]
great to hear @bufferings 👍
