### ISSUE TITLE
vamp-workflow-agent in an offline on-premise install

### ISSUE THREAD

**Issue by stefanvangastel** [magneticio/vamp#806]
Using the [pr-pending Rancher catalog entry for Vamp](https://github.com/rancher/community-catalog/pull/307) in an on-premise offline install all components start (changed the image-urls to private registry url's).

Though the three workflow-agents (health, kibana and metrics) keep restarting due to the following error:

```
26-10-2016 10:26:49[32m08:26:49.116 main NOTI ==> Starting Vamp Workflow Agent [0m
26-10-2016 10:26:4908:26:49.116 main INFO ==> Key-value store type          : consul [0m
26-10-2016 10:26:4908:26:49.116 main INFO ==> Key-value store connection    : consul:8500 [0m
26-10-2016 10:26:4908:26:49.116 main INFO ==> Key-value store root key path : /vamp/workflow/health [0m
26-10-2016 10:26:4908:26:49.116 main INFO ==> Workflow file path            : /usr/local/vamp [0m
26-10-2016 10:26:4908:26:49.116 main INFO ==> Reading workflow from         : /vamp/workflow/health/workflow [0m
26-10-2016 10:26:4908:26:49.116 main INFO ==> Initializing Consul connection: consul:8500 [0m
26-10-2016 10:26:4908:26:49.116 main INFO ==> Consul getting '/vamp/workflow/health/workflow' key value. [0m
26-10-2016 10:26:52[35m08:26:52.125 main CRIT ==> Can't read the workflow: Get http://consul:8500/v1/kv/vamp/workflow/health/workflow: dial tcp 10.42.46.30:8500: getsockopt: no route to host [0m
26-10-2016 10:26:52panic: Can't read the workflow: Get http://consul:8500/v1/kv/vamp/workflow/health/workflow: dial tcp 10.42.46.30:8500: getsockopt: no route to host
26-10-2016 10:26:52
26-10-2016 10:26:52goroutine 1 [running]:
26-10-2016 10:26:52panic(0x96ad00, 0xc8201193e0)
26-10-2016 10:26:52    /usr/local/opt/go/libexec/src/runtime/panic.go:481 +0x3e6
26-10-2016 10:26:52github.com/op/go-logging.(*Logger).Panic(0xc8201005d0, 0xc8200fff18, 0x2, 0x2)
26-10-2016 10:26:52    /Users/dragoslav/workspace/go/src/github.com/op/go-logging/logger.go:182 +0x187
26-10-2016 10:26:52main.main()
26-10-2016 10:26:52        /Users/dragoslav/workspace/go/src/github.com/magneticio/vamp-workflow-agent/main.go:70 +0x8ad
```

Changing the entry-point of e.g. the vamp-workflow-kibana service/container to `/bin/sh -c 'ping consul'` returns a proper response. 

Only thing I could think of is the way I start the three agents 'manually' in the [docker-compose](https://github.com/stefanvangastel/community-catalog/blob/master/templates/vamp/0/docker-compose.yml#L59) and don't let Vamp start them. I changed this because of the fact that when Vamp starts them, the images used are the default Docker hub images (magneticio/vamp-workflow-agent) and not my private registry copied images.

Any thoughts? At this time this is the only thing holding us from testing Vamp on-premise.

**Comment by stefanvangastel** [comment]
The issue seems to be the Consul keys not being populated when starting the workflow-agents from docker-compose.

Temp workaround: stop/delete the three health, kibana and metrics services, restart Vamp so the keys are populated. Start the three services.

**Comment by iamtew** [comment]
Do you want me to focus on this instead of the VGA+dnsmasq improvement I'm
currently doing?

**Comment by iamtew** [comment]
It does indeed look like an ordering problem here. I was hoping we could use the [depends_on](https://docs.docker.com/compose/compose-file/#/dependson) option, but it's not supported it seems:

```
time="2016-10-27T15:43:34Z" level=error msg="Could not parse config for project vamp : Unsupported config option for vamp-workflow-health service: 'depends_on'\nUnsupported config option for vamp-workflow-kibana service: 'depends_on'\nUnsupported config option for vamp-workflow-metrics service: 'depends_on'" 
time="2016-10-27T15:43:34Z" level=error msg="Stack Create Event Failed: Unsupported config option for vamp-workflow-health service: 'depends_on'\nUnsupported config option for vamp-workflow-kibana service: 'depends_on'\nUnsupported config option for vamp-workflow-metrics service: 'depends_on'" eventId=7d14db05-b899-4e54-8b65-8673af6004de resourceId=1e1 
```

If we can't spin up containers in specific order, or wait for Vamp to be fully started then we could perhaps skip the workflow's from the `docker-compose.yaml` and use the lifter functionality to have Vamp itself deploy the workflows. 
We do similar things when running on DC/OS, see http://vamp.io/documentation/installation/dcos/

I will play around a bit with this and see what we can come up with...

**Comment by stefanvangastel** [comment]
Thanks, that is a solution and also was the first version of the Catalog's
docker-compose file. The issue then is the lifter as you call it launching
the workflow container from docker hub. We have an on-premise setup with no
internet connection and all our images tagged in a private registry.

Being able to overwrite te workflow agent's image url with an env var on
Vamp container launch could do the trick I think.

Op do 27 okt. 2016 17:47 schreef Mikael Sörlin <notifications@github.com>:

**Comment by olafmol** [comment]
tnx Stefan, makes sense to make the location of the vamp workflow container configurable, including private repos. Will add an issue for this.

**Comment by iamtew** [comment]
You should already be able to overwrite the URL. Looking at the config at https://github.com/magneticio/vamp-docker/blob/master/vamp-rancher/application.conf it's defined in the workflow stanza.

Setting VAMP_WORKFLOW_DRIVER_WORKFLOW_DEPLOYABLE_DEFINITION to something like "registry.example.com/magneticio/vamp-workflow-agent:katana" should pull it from your own registry. I will test this myself just to make sure I'm not telling lies :)

**Comment by stefanvangastel** [comment]
Thanks, I'm going to give it a try!

Op vr 28 okt. 2016 10:42 schreef Mikael Sörlin <notifications@github.com>:

**Comment by iamtew** [comment]
I've tested a few different scenarios:

- Adding private repository in VAMP_WORKFLOW_DRIVER_WORKFLOW_DEPLOYABLE_DEFINITION. Not much happened, it seemed like the other image definitions overwrote that and it pulled it the regular way.
- Updating all the image definitions to point to my own registry, seemed OK but it would never complete. Unsure if this actually works or I configured my registry badly.
- Tried to change the order and dependencies using `links` in the docker-compose.yml file, with no success. Even if the workflow agents starts up after Vamp and Consul is fully started, it throws the same error.

So, so far no luck, unfortunately.

@olafmol : you mentioned that there was someone from the Rancher project who could help us?

**Comment by stefanvangastel** [comment]
@all: I think making your first scenario work is the way to go.

So make Vamp accept the
VAMP_WORKFLOW_DRIVER_WORKFLOW_DEPLOYABLE_DEFINITION env setting.


Op vr 28 okt. 2016 17:24 schreef Mikael Sörlin <notifications@github.com>:

I've tested a few different scenarios:

   - Adding private repository in
   VAMP_WORKFLOW_DRIVER_WORKFLOW_DEPLOYABLE_DEFINITION. Not much happened, it
   seemed like the other image definitions overwrote that and it pulled it the
   regular way.
   - Updating all the image definitions to point to my own registry, seemed
   OK but it would never complete. Unsure if this actually works or I
   configured my registry badly.
   - Tried to change the order and dependencies using links in the
   docker-compose.yml file, with no success. Even if the workflow agents
   starts up after Vamp and Consul is fully started, it throws the same error.

So, so far no luck, unfortunately.

@olafmol <https://github.com/olafmol> : you mentioned that there was
someone from the Rancher project who could help us?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/magneticio/vamp/issues/806#issuecomment-256948105>, or mute
the thread

**Comment by rawmind0** [comment]
Hi guys.....

syncronization or dependencies management between microservices have to be managed from the containers itself. I mean, if one piece needs consul, you need to check connection from that piece or check the healthcheck and when it connects, then it start the service...

Links doesn't manage that stuffs...Links only assure that the containers are deployed in one specific order, but doesn't wait until the service is working....In kubernetes or mesos/marathon you don't have links for example....

For example, in rancher if vamp stack/service needs consul stack/service, you have to tell vamp that his consul service is consul (from the catalog). Vamp could check the healthcheck of consul through the rancher metadata server, and if it's ok, start..

**Comment by stefanvangastel** [comment]
I think your statement is right, though the issue at hand is the fact that
a dockerhub image is used (set in image config) and there is no way to set
a private registry image source.

Op do 3 nov. 2016 21:12 schreef Raúl Sánchez <notifications@github.com>:

**Comment by olafmol** [comment]
You can configure the path to the docker containers. @stefanvangastel please re-open if still an issue.
