### ISSUE TITLE
Saving changes to breed fails due to "Server timeout"

### ISSUE THREAD

**Issue by iamtew** [magneticio/vamp#807]
Sometimes when saving a breed it refuses and shows an error:

> Save of 'vga'failed.
> Server timeout.

It's not clear where this timeout occurs, and there's nothing in the logs of Vamp when this happens.

Vamp version 0.9.0-65-g1ccc425
DC/OS version 1.8.6

**Comment by dragoslav** [comment]
If you use `key-value` storage, this may happen now and then.
