### ISSUE TITLE
Metrics for every Vamp agent

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#811]
for use case like this https://github.com/magneticio/vamp/issues/809 and possible implementation https://github.com/magneticio/vamp/issues/774#issuecomment-266304556

**Comment by harmw** [comment]
FYI: a prometheus exporter for NodeJS can be found here:
https://github.com/siimon/prom-client

**Comment by olafmol** [comment]
Add metricbeat to all Vamp components (VGA, VWA, Vamp) so we can collect system and docker metrics from all running components.

**Comment by olafmol** [comment]
added filebeat, metricbeat and httpbeat to Vamp components to store runtime metrics.
