### ISSUE TITLE
DC/OS 1.8 uninstall Vamp universe package keeps VGA and workflows running

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#818]

**Comment by iamtew** [comment]
This happens because Vamp is managing these containers, not the Universe package. Need to add additional uninstall instructions on how to clean this up, to the documentation.

**Comment by olafmol** [comment]
as there currently is no DCOS uninstall hook/API method, we're not able to programmatically do this. So closing this issue for now.
