### ISSUE TITLE
Vamp 091 on Google Container Engine doesn't show UI

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#820]
error message "The requested resource could not be found."

Katana (14nov) also has this issue. Vamp 090 works correctly.

**Comment by iamtew** [comment]
HTTP UI path's weren't set correctly. Adjusted under: https://github.com/magneticio/vamp-docker/commit/b00b22dfe210c63532171c842dd3843fe47df2cd

**Comment by iamtew** [comment]
This seems to be related to configuration options that we broke in the [0.9.1 release](https://github.com/magneticio/vamp/releases/tag/0.9.1):

>    BREAKING CHANGE: In the Vamp configuration the “rest-api” section has changed to “http-api”. When running Vamp 0.9.1 you need to change this setting accordingly. NB REST and websockets are both a part of our HTTP API. Check the Vamp configuration examples.

The following configuration options need to be specified:
```
http-api.ui {
  directory = "/usr/local/vamp/ui"
  index = ${vamp.http-api.ui.directory}"/index.html"
}
```

**Comment by harmw** [comment]
Please note that (at least) I am seeing this issue on the 0.9.1 image, not a specific mesos/k8s tag. Given the commit @iamtew just referenced which is specific to k8s.

**Comment by iamtew** [comment]
Following images have been updated with the new configuration and pushed to docker hub:

- 0.9.1-kubernetes
- 0.9.1-rancher
- katana-kubernetes
- katana-rancher

**Comment by iamtew** [comment]
Need to check with @dragoslav is we should update the default settings as well: https://github.com/magneticio/vamp/blob/master/bootstrap/src/main/resources/reference.conf#L132-L135
