### ISSUE TITLE
Metrics endpoint on VAMP itself

### ISSUE THREAD

**Issue by harmw** [magneticio/vamp#824]
Preferably a `/metrics` endpoint with _Prometheus_-style metrics to keep an eye on resource consumption (since I'm currently seeing VAMP crash without reason).

**Comment by harmw** [comment]
Adding to this, VAMP is launched with 1GB memory but still manages to get `killed`:

```
Docker container run error: Container exited on error: exited with status 137
```

**Comment by olafmol** [comment]
related to #3

**Comment by dragoslav** [comment]
Closing this as it should be part of https://github.com/magneticio/vamp/issues/855.
https://github.com/magneticio/vamp/issues/855 also requires additional refinements especially if/how we are going to handle agent metrics (probably keeping it separate).
