### ISSUE TITLE
Custom log target per frontend

### ISSUE THREAD

**Issue by harmw** [magneticio/vamp#825]
Currently our haproxy setup is using a `global` _log_ parameter, which disables logging. Since all frontends from VAMP are using this entry, metrics are essentially zeroed out.

https://github.com/magneticio/vamp/blob/master/gateway_driver/src/main/resources/io/vamp/gateway_driver/haproxy/template.twig

Can we get a configurable item for this so we can change the level/target?
```
    log 172.17.42.1:5170 local0 info
```

**Comment by dragoslav** [comment]
Is it possible to use custom template for this? Vamp can configured to load template.twig from custom location instead to use default one.

**Comment by olafmol** [comment]
@harmw in 093 you can update the config through the UI template editor. Please re-open if still an issue.
