### ISSUE TITLE
Inconsistent Deployment Issues when Blueprint Contains more than 10 services

### ISSUE THREAD

**Issue by rafarhat** [magneticio/vamp#827]
Stack Version
Vamp: vamp:0.9.1-dcos
DCOS on Azure (ACS): 1.8.4

We are currently using vamp to deploy a set of micro services, our current approach is to use 1 blueprint with each service being defined as cluster in blueprint something similar to this ([test2.json.txt](https://github.com/magneticio/vamp/files/618007/test2.json.txt)).

We have seen a few issues crop up as the number of services increased.

1- Stuck Deployments - Services above the 10th are not deployed in marathon even though there are resources in the cluster. Increasing the below variable to 50 seems to have sorted this out  "VAMP_OPERATION_MAILBOX_MAILBOX_CAPACITY": "50"

2- Random VAMP container crashes

3- Canary releases  of the entire set of services similar to [test3.json.txt](https://github.com/magneticio/vamp/files/618008/test3.json.txt) will not work consistently.  Sometimes gateway ports gets stuck in deployment, sometimes they are reported as failing but the deployment gets stuck in in deploying state. During this time the external gateway will actually be down for both old and new versions of the service.

For example the logs will show 

Deployment service error for deployment 'sava:3.0' and service 'sava:1.1.0'.

And UI shows 

![image](https://cloud.githubusercontent.com/assets/6476033/20695164/dc917134-b59e-11e6-9a32-14b8e7bb428a.png)

Repro:

1- You can deploy https://github.com/magneticio/vamp/files/618007/test2.json.txt to get deployment with 12 services.
2- You can update the deployment above with https://github.com/magneticio/vamp/files/618007/test3.json.txt  to a new version of each service 9 of 10 ten times this will fail.

Is there any guidance on how large a blueprint can get , and whether we should batch things up or not? Currently the reason we went with one blueprint is it just make the continuous integration scenario easier we update the the entire set of services  with new version , run or test, and switch over traffic treating the entire set as one deployment.

**Comment by olafmol** [comment]
@rafarhat tnx for reporting. We are currently stress-testing the latest Vamp release and will improve, fix and report back on limits of deployments and blueprints asap.

**Comment by rafarhat** [comment]
Thanks @olafmol I've attached the logs.

[stdout (1).1.txt](https://github.com/magneticio/vamp/files/620166/stdout.1.1.txt)
[stdout (2).2.txt](https://github.com/magneticio/vamp/files/620168/stdout.2.2.txt)
[errout.txt](https://github.com/magneticio/vamp/files/620169/errout.txt)
[stdout.1.txt](https://github.com/magneticio/vamp/files/620170/stdout.1.txt)
[vampaftercrash.txt](https://github.com/magneticio/vamp/files/620171/vampaftercrash.txt)

**Comment by olafmol** [comment]
Tnx @rafarhat the logs seem to indicate some issue with an overloaded ES cluster. We will investigate further.

**Comment by olafmol** [comment]
@rafarhat is still an issue with Vamp 092? tnx!

**Comment by rafarhat** [comment]
@olafmol  Issues 1 and 2 are gone. I've been successfully deploying over 20 services at a time with 0.9.2 and its is much more stable than the older version so kudos for the hard work. I am still seeing some random race condition like situations (in 5 out of 20 deployments when we update a route to 100% new service from an older version and when i attempt to delete the old set it fails because the new traffic weights really set even though deployment status is complete)  but i think we can close this one I can open another issue with more detail.

**Comment by olafmol** [comment]
@rafarhat that's great to hear! Do you get UI time-out messages when trying to undeploy? If so, this could be due to a known web socket issue we're currently addressing. In any case, please open a new issue with all relevant information for these race conditions so we can investigate and solve this. Tnx!

**Comment by rafarhat** [comment]
@olafmol thanks, yes we are still seeing ui timeoutson action like undeploy from teh ui on  but since our deployments/rollback are scripted through the rest api those are stable.

**Comment by olafmol** [comment]
@rafarhat yes using the API should always be stable, good to hear!

**Comment by olafmol** [comment]
BTW, the upcoming 093 release will have some nice UI features for larger deployments, like list view and filter/search on them.
