### ISSUE TITLE
Internal server error posting upper case event-type to events API 

### ISSUE THREAD

**Issue by gggina** [magneticio/vamp#830]
Seems type cannot have uppercase because of elasticsearch limitations
----
{
  "tags": [
    "test_key:test_value",
  ],
  "type": "name:helloAPI",
}

-----

{
  "message": "Internal server error."
}

-----

13:09:37.244 | ERROR | io.vamp.common.notification.Notification |                                          | {"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [vamp-pulse-name:helloAPI-2016-12-01], must be lowercase","index":"vamp-pulse-name:helloAPI-2016-12-01"}],"type":"invalid_index_name_exception","reason":"Invalid index name [vamp-pulse-name:helloAPI-2016-12-01], must be lowercase","index":"vamp-pulse-name:helloAPI-2016-12-01"},"status":400}
io.vamp.common.http.HttpClientException: {"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [vamp-pulse-name:helloAPI-2016-12-01], must be lowercase","index":"vamp-pulse-name:helloAPI-2016-12-01"}],"type":"invalid_index_name_exception","reason":"Invalid index name [vamp-pulse-name:helloAPI-2016-12-01], must be lowercase","index":"vamp-pulse-name:helloAPI-2016-12-01"},"status":400}

**Comment by dragoslav** [comment]
Only alphanumeric, '_' and '-' are allowed after the change.
