### ISSUE TITLE
Make Logstash port configurable

### ISSUE THREAD

**Issue by iamtew** [magneticio/vamp#831]
Currently we can only configure the Logstash host, but not the port.

Should add option `vamp.gateway-driver.logstash.port`.

https://github.com/magneticio/vamp-docker/blob/master/vamp-dcos/artifacts/breeds/vga.js#L30
https://github.com/magneticio/vamp-docker/blob/master/vamp-dcos/application.conf#L23

**Comment by dragoslav** [comment]
resolved by https://github.com/magneticio/vamp-docker/commit/10fba2c8e201b69184e714b7e6f12fb2f15cb22e
