### ISSUE TITLE
Vamp docker quickstart katana 0.9.1-6-gfe664ba cannot start Kibana workflow

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#839]
errors:

--container="mesos-f4d1d246-cf48-4cb6-8f8e-977473642bc1-S1.13a5d89b-ae5d-475e-b738-b526341ec827" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --launcher_dir="/usr/libexec/mesos" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/var/run/mesos/slave1/slaves/f4d1d246-cf48-4cb6-8f8e-977473642bc1-S1/frameworks/f4d1d246-cf48-4cb6-8f8e-977473642bc1-0001/executors/vamp_workflow-kibana.7330fb75-bba0-11e6-a481-024237d3526a/runs/13a5d89b-ae5d-475e-b738-b526341ec827" --stop_timeout="10secs"
--container="mesos-f4d1d246-cf48-4cb6-8f8e-977473642bc1-S1.13a5d89b-ae5d-475e-b738-b526341ec827" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --launcher_dir="/usr/libexec/mesos" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/var/run/mesos/slave1/slaves/f4d1d246-cf48-4cb6-8f8e-977473642bc1-S1/frameworks/f4d1d246-cf48-4cb6-8f8e-977473642bc1-0001/executors/vamp_workflow-kibana.7330fb75-bba0-11e6-a481-024237d3526a/runs/13a5d89b-ae5d-475e-b738-b526341ec827" --stop_timeout="10secs"
Registered docker executor on 192.168.99.100
Starting task vamp_workflow-kibana.7330fb75-bba0-11e6-a481-024237d3526a
[32m10:40:48.748 main NOTI ==> 
██╗   ██╗ █████╗ ███╗   ███╗██████╗
██║   ██║██╔══██╗████╗ ████║██╔══██╗
██║   ██║███████║██╔████╔██║██████╔╝
╚██╗ ██╔╝██╔══██║██║╚██╔╝██║██╔═══╝
 ╚████╔╝ ██║  ██║██║ ╚═╝ ██║██║
  ╚═══╝  ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝
                       workflow agent
                       version katana
                       by magnetic.io
                                       [0m
[35m10:40:48.748 main CRIT ==> Execution period must be specified and it must be equal or greater than 0. [0m
  ╚═══╝  ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝
                       workflow agent
                       version katana
                       by magnetic.io
                                       [0m
[35m10:40:48.748 main CRIT ==> Execution period must be specified and it must be equal or greater than 0. [0m
t must be equal or greater than 0. [0m

and:

I1206 10:40:48.439956 19654 exec.cpp:134] Version: 0.27.0
I1206 10:40:48.476902 19659 exec.cpp:208] Executor registered on slave f4d1d246-cf48-4cb6-8f8e-977473642bc1-S1
panic: Execution period must be specified and it must be equal or greater than 0.

goroutine 1 [running]:
panic(0x8cf080, 0xc42000bfe0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
github.com/op/go-logging.(*Logger).Panic(0xc4200fe6f0, 0xc420037d90, 0x1, 0x1)
	/Users/dragoslav/workspace/go/src/github.com/op/go-logging/logger.go:182 +0x160
main.checkInt(0xc42000bd50, 0x9cbe06, 0x19, 0x9d880e, 0x4a)
	/Users/dragoslav/workspace/go/src/github.com/magneticio/vamp-workflow-agent/main.go:111 +0x1d1
main.main()
	/Users/dragoslav/workspace/go/src/github.com/magneticio/vamp-workflow-agent/main.go:57 +0x15b

**Comment by dragoslav** [comment]
Just tried with the newest `katana` and it works. There was a typo in env name in workflow agent and that is fixed as well. Pull the latest katana quick start and workflow agent.
