### ISSUE TITLE
UI graphs report NONE in katana when running apache bench with over circa500 requests

### ISSUE THREAD

**Issue by gggina** [magneticio/vamp#857]
ab -k -c 15 -n 500 http://\`docker-machine ip default\`:9050/

Sava remains available.
Once apache bench has stopped running, refreshing sava appears to start wverything working normally again (a bit slowly)

12:06:04.282 main INFO ==> WORKFLOW API GET /gateways [0m
12:06:04.339 main INFO ==> WORKFLOW API GET /deployments [0m
12:06:04.619 main INFO ==> WORKFLOW API GET /config [0m
12:06:04.637 main INFO ==> WORKFLOW API GET /config [CACHED] [0m
[32m12:06:04.783 main NOTI ==> Workflow process is killed as timeout reached. [0m
[32m12:06:05.776 main NOTI ==> Executing workflow by Node.js. [0m
[32m12:06:09.790 main NOTI ==> Workflow process is killed as timeout reached. [0m

**Comment by dragoslav** [comment]
Root cause was https://github.com/magneticio/vamp-node-client/issues/5
