### ISSUE TITLE
Update VGA environment variables

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#868]
Since https://github.com/magneticio/vamp-gateway-agent/issues/25 and https://github.com/magneticio/vamp-gateway-agent/issues/7 we can't use command line arguments for VGA.
For metrics (e.g. https://github.com/magneticio/vamp-gateway-agent/issues/4) we still need to define environment variables but for `confd` these are:
```
VAMP_KEY_VALUE_STORE_TYPE <=> confd -backend
VAMP_KEY_VALUE_STORE_CONNECTION <=> confd -node
VAMP_KEY_VALUE_STORE_PATH <=> key used by confd
```

An example https://github.com/magneticio/vamp-docker/blob/master/clique-zookeeper-marathon/supervisord.conf

Files that need to updated for sure are (not exclusively):
- https://github.com/magneticio/vamp-docker/blob/master/vamp-dcos/artifacts/breeds/vga.js
- https://github.com/magneticio/vamp-docker/blob/master/vamp-kubernetes/vga.yml

Additional:
- `VAMP_PERSISTENCE_STORE_CONNECTION` - should be renamed as well, e.g. `VAMP_ELASTICSEARCH_URL`

**Comment by iamtew** [comment]
New links: 
- https://github.com/magneticio/vamp-artifacts/blob/master/breeds/vga.js
- https://github.com/magneticio/vamp-artifacts/blob/master/workflows/vga.yml

Other places:
- https://github.com/magneticio/vamp-docker-images/search?utf8=%E2%9C%93&q=--storeType
- https://github.com/magneticio/vamp.io/search?utf8=%E2%9C%93&q=--storeType

**Comment by iamtew** [comment]
@dragoslav could you confirm the "elasticsearch" placeholder will actually expand correctly under K8s? Looking at our docs it should, but I want a second pair of eyes on it.

See:
- https://github.com/magneticio/vamp-docker-images/commit/9d40c3ae75be50f046571cd4cf22312e71cf4f66
- http://vamp.io/documentation/installation/kubernetes/#manual-deployment
