### ISSUE TITLE
How to use haproxy templates

### ISSUE THREAD

**Issue by jpwesselink** [magneticio/vamp#882]
I'm trying to find a way to keep SSE connections open. Since there is an option to provide a custom template I think this is the first road to be travelled. Is there an example on how to do this?

**Comment by dragoslav** [comment]
If you are using the latest 0.9.2 release:
- take a look at default template (0.9.2) https://github.com/magneticio/vamp/blob/0.9.2/gateway_driver/src/main/resources/io/vamp/gateway_driver/haproxy/template.twig and create your own
- override `template` with file path to the template https://github.com/magneticio/vamp/blob/0.9.2/gateway_driver/src/main/resources/io/vamp/gateway_driver/haproxy/template.twig (setting the template path can be done via environment variables but template must be provided as a file).
- restart Vamp

Latest snapshot (`katana`) - there is possibility to update the template directly in Vamp UI (still needs some styling https://github.com/magneticio/vamp-ui/issues/201). This feature will be officially in the next 0.9.3 (~ end of January).
