### ISSUE TITLE
Persistence operation failure

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#9]
It should not be an error (works for in memory implementation).

error:
{
"message": "The request content was malformed. Unsupported deployment request. Reason: PersistenceOperationFailure(org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: \"idx_environment_variables ON PUBLIC.\"\"environment_variables\"\"(\"\"name\"\", \"\"parent_id\"\", \"\"parent_type\"\")\"; SQL statement:\ insert into \"environment_variables\" (\"deployment_fk\",\"name\",\"trait_scope\",\"trait_group\",\"alias\",\"env_value\",\"env_direction\",\"parent_id\",\"parent_type\") values (?,?,?,?,?,?,?,?,?) [23505-166])"
}

blueprint: https://github.com/magneticio/sava/blob/master/blueprints/1.2_fe_be.yaml

**Comment by plamola** [comment]
All environment variables where stored without a deployment id. This would cause environment variables from blueprints and deployments to collide, thus triggering the unique constraint.

Also found a problem with child artifacts with the same name within a deployment.

**Please drop your database**.
The updates are not compatible with the previous database schema.

**Comment by plamola** [comment]
Fixed the foreign key; scope was missing
