### ISSUE TITLE
With Vamp configured and working, Vamp Runner will reliably crash Vamp after a few hours

### ISSUE THREAD

**Issue by pvcon13** [magneticio/vamp#905]
**Vamp** (Marathon) 0.92 - **Ranche**r 1.3.3 - **Docker** 1.12.6
Default **Mesos** (Catalog version) 0.28.1 - Default **Marathon** (Catalog version) v1.1.1
**Vamp Runner**: latest

**Please reference:** Vamp in Marathon on Rancher builds into Elastic Search on startup and then errors out **#894**

**Issue**:  Even if you never use Vamp Runner, once loaded it will eventually crash Vamp and force a respawn to another mesos slave controlled system host. At that point it does not correctly recover and without a script to clear out Elastic search, cannot be live reconfigured to keep working.

**Procedure:** 
Loading Rancher with Mesos default system with Marathon and then Vamp, load latest version of Vamp Runner. 
Observe that the deployment and the two gateways are showing good data and good health.
Do not use any features or functions of Vamp runner at all
Leave Vamp on a non-interactive page in GUI (not showing dynamic health) and then close GUI

With a few hours Vamp will crash. 

Logging in to that new Vamp host (could not get in (GUI would not respond)). 

Reset in Marathon with corrected ENV variables, and then was able to launch GUI. 

In both cases, Vamp still shows the deployment of Vamp Runner as "failed". 

Using Vamp, Failed Vamp Runner will not delete (errors on screen in red). 

Then using Marathon, can delete Vamp runner but Vamp continues to report Vamp Runner as failed and will not delete. 

Only way to clear the error is to remove all of vamp, and most especially Elastic Search and redeploy again.

Would like to test this with Vamp version 0.9.3.
Let me know how I can test this for you further
Thanks as always

**Comment by olafmol** [comment]
can you post the logs from Vamp when it has crashed? tnx!

**Comment by olafmol** [comment]
closing this as we will handle this with solving #955
