### ISSUE TITLE
time based workflow does not run

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#921]
when defining the workflow (in Vamp docker quickstart 093 on Mac OS X) like this:

schedule:
  time:
    period: PT5S

i don't see the expected activity (i would expect to see something every 5seconds?)

**Comment by dragoslav** [comment]
It was related to https://github.com/magneticio/vamp/issues/911, also there could be an unexpected behavior due to https://github.com/magneticio/vamp-workflow-agent/issues/17
