### ISSUE TITLE
Docker-compose to Blueprint Converter

### ISSUE THREAD

**Issue by ThomasMeijers** [magneticio/vamp#928]
Add a new endpoint that can convert a docker-compose yaml definition to a Blueprint.

**Comment by dragoslav** [comment]
This https://github.com/magneticio/vamp/commit/74baa94e6560cf19bfdb7ebcb15132cc8234528d#diff-0fdcfd6bfadb22d7cb9555d80a64dd04R101 should be a separate route.

**Comment by ThomasMeijers** [comment]
I will close this issue, since this can also include some other importing and exporting use cases. See #948.
