### ISSUE TITLE
updates to workflow environment variables not saved

### ISSUE THREAD

**Issue by gggina** [magneticio/vamp#932]
updates made to workflow environment variables are not saved.

- Message states "saved successfully"
- archive:update event value contains the original environment variable setting
- reopening the workflow shows the original environment variables

Same behaviour in running and suspended workflows
Restarting the workflow does not cause "invisible" changes to be applied

quickstart v093

**Comment by gggina** [comment]
Hello World quickstart v093, running on macOS 10.12.3 with docker version 1.12.0.

Following the tutorial "Create a workflow that generates events". 
This occurs when following the steps at "UPDATE THE RUNNING WORKFLOW" http://vamp.io/documentation/tutorials/create-a-workflow/#update-the-running-workflow

Workflow YAML:

name: hello_workflow
breed: hello_workflow
environment_variables:
  VAMP_WORKFLOW_EXECUTION_PERIOD: '5' 
  VAMP_WORKFLOW_EXECUTION_TIMEOUT: '4'  # should be less than VAMP_WORKFLOW_EXECUTION_PERIOD
schedule: daemon

**Comment by dragoslav** [comment]
resolved by https://github.com/magneticio/vamp/issues/939
