### ISSUE TITLE
Vamp Runner gives "failing" message in UI, but runs correctly in DCOS marathon

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#935]
with Vamp 093 and Vamp Runner 093 (using blueprint and http://10.20.0.100:8080/api/v1 for API URL) on DCOS Azure after some time Vamp Runner deployment reports a failing state, but the container itself runs correctly. The error in the Vamp logs shows:

```
[0;39m[36m18:58:28.727[0;39m [34m| INFO  | i.v.c.marathon.MarathonDriverActor       | kka://vamp/user/marathon-driver-actor-23 | marathon update service: vamp-runner / magneticio/vamp-runner:0.9.3
[0;39m[36m18:58:31.647[0;39m [1;31m| ERROR | io.vamp.common.notification.Notification |                                          | Deployment service error for deployment 'vamp-runner' and service 'vamp-runner:0.9.3'.
[0;39m
```

It's unclear how to reproduce this, leaving Vamp Runner run for some time seems to be an issue though.

**Comment by pvcon13** [comment]
Same happens with Vamp Runner on Marathon/Mesos without DCOS (just deployment to AWS). The actually sequence for me is Runner deploys and works, then something happens to Vamp and Vamp Runner stops working, then you correct it and Runner works again but Vamp continues to report failed, and a cannot be deleted and/or reloaded by Vamp. Marathons reported state of Vamp and Vamp runner is always correct during these sequences. Only way to clear is to clear out elastic search in some way, the usual way is just to delete and reinstall elastic search

**Comment by olafmol** [comment]
Some more details: re-scaling the Vamp-Runner deployment seems to fix the "failing state". At some point i had 10 Vamp-Runner instances active/running, while the status was failing in Vamp UI, but the instances details where correctly displayed in the UI. 

This situation could possible happen because of Marathon restarting a container (in this case Vamp-Runner) for some reason, and then Vamp and Marathon becoming out of sync regarding the state-data.

The "failure" status in Vamp UI is appearing after a time-out (10min) of Vamp not being able to achieve the situation it wants to achieve.

**Comment by olafmol** [comment]
closing this as duplicate of #955
