### ISSUE TITLE
report error message when marathon doesn't have enough resources

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#938]
a big issue with deploying containers on marathon is that there will be no error message when there aren't enough resources available on the cluster. Marathon will simply go into "waiting" mode and queue the container until enough resources become available. Users expect something else: a direct message why the container is not being deployed, (and maybe an interactive option to decide to queue it anyway, or cancel the deployment)

If possible it would solve a lot of frustration if Vamp could check the available resources and/or the reason for "waiting" containers when deploying a blueprint, and give feedback to the user about this.

**Comment by ThomasMeijers** [comment]
Created a solution in https://github.com/magneticio/vamp-ui/commit/d0ebdaefe1b13063527c08ac2979da73fe11de02. This solution shows a warning when there are not enough resources available on a new deployment. The feature will be split off to different issues for warning on scaling and merging deployments, in the [vamp-ui](https://github.com/magneticio/vamp-ui) repository. See https://github.com/magneticio/vamp-ui/issues/309 https://github.com/magneticio/vamp-ui/issues/310 respectively.
