### ISSUE TITLE
Vamp fails after a few hours. Api gives internal error.

### ISSUE THREAD

**Issue by RoelVanNyen** [magneticio/vamp#943]
I'm running magneticio/vamp:0.9.3-dcos on DC/OS 1.8.8
I'm running magneticio/elastic:2.2

This problem happens reliable every few hours.
After a while vamp does goes into internal error mode and the gateway does not work anymore.

When you access the api you get: 
{
"message": "Internal server error."
}

UI is not showing anything except in the events window it says:
persistence:ERROR info HttpClientException

All my deployments and blueprints etc are not shown anymore (probably because the api fails)

Logs:

vamp.vamp:
I0314 12:42:31.946285 12296 exec.cpp:161] Version: 1.0.3
I0314 12:42:31.951241 12302 exec.cpp:236] Executor registered on agent 8ec7a43e-3c4a-450c-9448-32b085e7f36a-S2
I0314 12:42:31.952524 12298 docker.cpp:815] Running docker -H unix:///var/run/docker.sock run --cpu-shares 512 --memory 1073741824 -e MARATHON_APP_VERSION=2017-03-14T12:42:19.839Z -e HOST=10.0.1.84 -e MARATHON_APP_RESOURCE_CPUS=0.5 -e MARATHON_APP_LABEL_DCOS_SERVICE_SCHEME=http -e MARATHON_APP_RESOURCE_GPUS=0 -e MARATHON_APP_LABEL_DCOS_SERVICE_NAME=vamp -e MARATHON_APP_DOCKER_IMAGE=magneticio/vamp:0.9.3-dcos -e VAMP_WAIT_FOR=http://elasticsearch.marathon.mesos:9200/.kibana -e MESOS_TASK_ID=vamp_vamp.a9cea5bb-08b3-11e7-8d6b-70b3d5800002 -e PORT=26966 -e MARATHON_APP_LABEL_DCOS_SERVICE_PORT_INDEX=0 -e MARATHON_APP_RESOURCE_MEM=1024.0 -e VAMP_WORKFLOW_DRIVER_VAMP_URL=http://10.20.0.100:8080 -e PORTS=26966 -e VAMP_ELASTICSEARCH_URL=http://elasticsearch.marathon.mesos:9200 -e MARATHON_APP_RESOURCE_DISK=0.0 -e PORT_VIP0=26966 -e MARATHON_APP_LABELS=DCOS_SERVICE_NAME DCOS_SERVICE_SCHEME DCOS_SERVICE_PORT_INDEX -e PORT_8080=26966 -e MARATHON_APP_ID=/vamp/vamp -e PORT0=26966 -e LIBPROCESS_IP=10.0.1.84 -e MESOS_SANDBOX=/mnt/mesos/sandbox -e MESOS_CONTAINER_NAME=mesos-8ec7a43e-3c4a-450c-9448-32b085e7f36a-S2.910381b1-c8f2-4785-8d81-70826de35b2d -v /var/lib/mesos/slave/slaves/8ec7a43e-3c4a-450c-9448-32b085e7f36a-S2/frameworks/8ec7a43e-3c4a-450c-9448-32b085e7f36a-0001/executors/vamp_vamp.a9cea5bb-08b3-11e7-8d6b-70b3d5800002/runs/910381b1-c8f2-4785-8d81-70826de35b2d:/mnt/mesos/sandbox --net bridge -p 26966:8080/tcp --name mesos-8ec7a43e-3c4a-450c-9448-32b085e7f36a-S2.910381b1-c8f2-4785-8d81-70826de35b2d magneticio/vamp:0.9.3-dcos
W0314 12:42:31.952524 12297 logging.cpp:91] RAW: Received signal SIGTERM from process 11269 of user 0; exiting

workflow-kibana.vamp:
[31m12:47:43.020 main ERRO ==> WORKFLOW (node:1520) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: getaddrinfo ENOTFOUND elasticsearch.marathon.mesos elasticsearch.marathon.mesos:9200 [0m
[31m12:47:43.020 main ERRO ==> WORKFLOW (node:1520) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. [0m
[32m12:47:43.021 main NOTI ==> Workflow execution took:  198.471784ms [0m
[32m12:47:43.021 main NOTI ==> Workflow exit status code:  0 [0m

workflow-allocation.vamp
:47:42.908 main INFO ==> WORKFLOW API options: {"host":"http://10.20.0.100:8080","path":"/api/v1","headers":{"Accept":"application/json","Content-Type":"application/json"},"cache":true} [0m
12:47:42.909 main INFO ==> WORKFLOW API GET /deployments [0m
12:47:42.924 main INFO ==> WORKFLOW HTTP REQUEST [0] {"protocol":"http:","port":"8080","hostname":"10.20.0.100","method":"GET","headers":{"Accept":"application/json","Content-Type":"application/json"},"path":"/api/v1/deployments?page=1"} [0m
12:47:42.963 main INFO ==> WORKFLOW HTTP RESPONSE [0] 500 [0m
[31m12:47:42.967 main ERRO ==> WORKFLOW (node:1722) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: [500]: {"message":"Internal server error."} [0m
[31m12:47:42.967 main ERRO ==> WORKFLOW (node:1722) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. [0m
[32m12:47:42.975 main NOTI ==> Workflow execution took:  190.128683ms [0m

vamp-gateway-agent.vamp 
I0314 12:43:47.311805 12224 exec.cpp:161] Version: 1.0.3
I0314 12:43:47.315315 12232 exec.cpp:236] Executor registered on agent 8ec7a43e-3c4a-450c-9448-32b085e7f36a-S6
I0314 12:43:47.316411 12233 docker.cpp:815] Running docker -H unix:///var/run/docker.sock run --privileged --cpu-shares 204 --memory 268435456 -e MARATHON_APP_VERSION=2017-03-14T12:43:43.068Z -e HOST=10.0.4.44 -e MARATHON_APP_RESOURCE_CPUS=0.2 -e VAMP_KEY_VALUE_STORE_CONNECTION=zk-1.zk:2181 -e VAMP_KEY_VALUE_STORE_PATH=/vamp/gateways/haproxy/1.7/configuration -e MARATHON_APP_RESOURCE_GPUS=0 -e MARATHON_APP_DOCKER_IMAGE=magneticio/vamp-gateway-agent:0.9.3 -e MESOS_TASK_ID=vamp_vamp-gateway-agent.db672e46-08b3-11e7-8d6b-70b3d5800002 -e PORT=3647 -e MARATHON_APP_RESOURCE_MEM=256.0 -e PORTS=3647 -e VAMP_ELASTICSEARCH_URL=http://elasticsearch.marathon.mesos:9200 -e MARATHON_APP_RESOURCE_DISK=0.0 -e VAMP_KEY_VALUE_STORE_TYPE=zookeeper -e MARATHON_APP_LABELS= -e PORT_10021=3647 -e MARATHON_APP_ID=/vamp/vamp-gateway-agent -e PORT0=3647 -e LIBPROCESS_IP=10.0.4.44 -e MESOS_SANDBOX=/mnt/mesos/sandbox -e MESOS_CONTAINER_NAME=mesos-8ec7a43e-3c4a-450c-9448-32b085e7f36a-S6.a4fa9626-7a9c-4d2f-acc0-88c72885eeed -v /var/lib/mesos/slave/slaves/8ec7a43e-3c4a-450c-9448-32b085e7f36a-S6/frameworks/8ec7a43e-3c4a-450c-9448-32b085e7f36a-0001/executors/vamp_vamp-gateway-agent.db672e46-08b3-11e7-8d6b-70b3d5800002/runs/a4fa9626-7a9c-4d2f-acc0-88c72885eeed:/mnt/mesos/sandbox --net host --name mesos-8ec7a43e-3c4a-450c-9448-32b085e7f36a-S6.a4fa9626-7a9c-4d2f-acc0-88c72885eeed magneticio/vamp-gateway-agent:0.9.3
/sbin/runsvdir started
reaped child process 54 (0)
reaped child process 108 (15)
reaped child process 112 (15)
reaped child process 300 (15)
reaped child process 559 (15)
reaped child process 623 (15)
received terminated
reaped child process 1794 (0)
/sbin/sv stop dnsmasq: wait: no child processes
/sbin/sv stop rsyslog: wait: no child processes
reaped child process 1800 (0)
stopped 4: confd, filebeat, haproxy, vamp-gateway-agent
stopping supervisor with signal terminated...
shutdown handler exiting
/sbin/runsvdir exited cleanly
W0314 12:43:47.316411 12232 logging.cpp:91] RAW: Received signal SIGTERM from process 11264 of user 0; exiting

workflow-metrics.vamp
12:47:42.923 main INFO ==> WORKFLOW API options: {"host":"http://10.20.0.100:8080","path":"/api/v1","headers":{"Accept":"application/json","Content-Type":"application/json"},"cache":true} [0m
12:47:42.925 main INFO ==> WORKFLOW API GET /gateways [0m
12:47:42.945 main INFO ==> WORKFLOW HTTP REQUEST [0] {"protocol":"http:","port":"8080","hostname":"10.20.0.100","method":"GET","headers":{"Accept":"application/json","Content-Type":"application/json"},"path":"/api/v1/gateways?page=1"} [0m
12:47:42.974 main INFO ==> WORKFLOW HTTP RESPONSE [0] 500 [0m
[31m12:47:42.974 main ERRO ==> WORKFLOW (node:1826) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: [500]: {"message":"Internal server error."} [0m
[31m12:47:42.975 main ERRO ==> WORKFLOW (node:1826) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. [0m
[32m12:47:42.977 main NOTI ==> Workflow execution took:  174.001311ms [0m
[32m12:47:42.977 main NOTI ==> Workflow exit status code:  0 [0m

Unfortunately none of the log files actualy tells us why we have a internal error (500).

If I restart vamp without touching elasticsearch everything works again.

**Comment by RoelVanNyen** [comment]
I found the actual error:
"No such index"

```
	ERROR	io.vamp.common.notification.Notification	Persistence operation failure.
14:37:29.487	ERROR	io.vamp.common.notification.Notification	{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"vamp-persistence","index":"vamp-persistence"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"vamp-persistence","index":"vamp-persistence"},"status":404}

```

Still no idea why this happens.

**Comment by olafmol** [comment]
The error suggests that the index of the persistence store is not available for some reason.  We will further investigate.

**Comment by olafmol** [comment]
@RoelVanNyen is this still the case with DCOS 1.9.0?

**Comment by olafmol** [comment]
closing this as we make failure of vamp dependencies handling more robust, please re-open if reproducible and stil an issue.
