### ISSUE TITLE
Unknown reasons of deploy failures

### ISSUE THREAD

**Issue by Alessar** [magneticio/vamp#944]
During deploy services we can ask vamp about microservice states.
Some field in json named ```status.phase.name``` can show ```Updating```, ```Done``` or ```Failed```.
If value is ```Failed``` we can see field ```status.phase.notification``` with message that service cannot be deployed. But what the reason of this impossibility is unknown.
Is there a good approach to understand reasons of failures?
It will be good, if vamp api can notify something about deploy issues or failure reasons.

**Comment by olafmol** [comment]
@Alessar tnx for the suggestion, we already did some work on this, fe. #938 Assigning @ThomasMeijers to take a look into this.

**Comment by olafmol** [comment]
closing this with the implementation of #938
