### ISSUE TITLE
running the third tutorial blueprint with Vamp katana quickstart shows 404's in webport panels 

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#947]
deploying the blueprint from tutorial 3, go to gateways, select sava2/9060, click on the host/port type link, see "The requested resource could not be found." in the right panel. (nb this works correctly with the first tutorial which uses port 9050).

NB this was using docker toolbox

**Comment by dragoslav** [comment]
it's problem with sava:1.2 - it redirects to `/public` - an absolute path, e.g. localhost:8080/public and avoids using Vamp reverse proxy. Will update the `sava` images.

**Comment by dragoslav** [comment]
Resolved by https://github.com/magneticio/sava/commit/313a0af13c00bcd1330163d5ddb898c9be2e33ea
Be sure that browser's cache for redirects (301) is cleared.
