### ISSUE TITLE
support for multiple zookeeper nodes

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#956]
now if you put multiple comma delimited zk nodes in the config you see this error in the workflow agent containers:

(AT BEGINNING OF FILE)
I0410 22:54:22.497422 23867 exec.cpp:162] Version: 1.2.1
I0410 22:54:22.503435 23874 exec.cpp:237] Executor registered on agent 72a48eab-6a37-4e73-b2a6-26ba64d9d0e3-S2
WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.
/sbin/runsvdir started
2017/04/10 22:54:22 Failed to connect to zk-1.zk:2181,zk-2.zk:2181,zk-3.zk:2181,zk-4.zk:2181,zk-5.zk:2181: dial tcp: too many colons in address zk-1.zk:2181,zk-2.zk:2181,zk-3.zk:2181,zk-4.zk:2181,zk-5.zk:2181
2017/04/10 22:54:23 Failed to connect to zk-1.zk:2181,zk-2.zk:2181,zk-3.zk:2181,zk-4.zk:2181,zk-5.zk:2181: dial tcp: too many colons in address zk-1.zk:2181,zk-2.zk:2181,zk-3.zk:2181,zk-4.zk:2181,zk-5.zk:2181
2017-04-10T22:54:23Z 61b042102157 /usr/bin/confd[36]: ERROR zk: could not connect to a server

**Comment by ThomasMeijers** [comment]
Fixed by https://github.com/magneticio/vamp-gateway-agent/commit/118f3caf2126d51a5cbeeae8755c09be832bbdb2
