### ISSUE TITLE
Can't convert Docker4Drupal docker-compose.yml to Blueprint

### ISSUE THREAD

**Issue by yonas** [magneticio/vamp#959]
When converting the Docker4Drupal [docker-compose.yml](https://raw.githubusercontent.com/wodby/docker4drupal/master/docker-compose.yml) file, I get a `Error converting file` error message.

Using Vamp 0.9.4 and Ubuntu 17.04.

**Comment by yonas** [comment]
Turns out the comment lines (`#`) need to be removed.

**Comment by ThomasMeijers** [comment]
Hi @yonas thank you for reporting this issue :+1:. I created another issue for ignoring the comments in our compose parser, so that you don't have to do it. See #960.
