### ISSUE TITLE
on DCOS 190 EE on AWS no log tabs are shown and reverse proxy webport output is white

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#964]
webport iframe shows only a white space, and the log output tabs are not displayed. When opening the webport in a new tab the content is shown correctly. 

Running Vamp DCOS 094 on DCOS EE 190 on AWS

**Comment by jason-magnetic-io** [comment]
This works in recent EE builds on DC/OS 1.9 and 1.10.
