### ISSUE TITLE
don't set hostport field when network: USER  

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#984]
hostport is not required when running a container in network USER mode. Currently we set "hostport:0" when there is a port defined. When the network setting is configured to USER mode we should not set this hostport field.

https://mesosphere.github.io/marathon/docs/ports.html

" Multiple port mappings may be specified for a Marathon application; an unspecified hostPortdefaults to 0 (meaning that Marathon will assign one at random). In Docker USER mode the semantic for hostPort slightly changes: hostPort is not required for USER mode and if left unspecified Marathon WILL NOT automatically allocate one at random. This allows containers to be deployed on USER networks that include containerPort and discovery information, but do NOT expose those ports on the host network (and by implication would not consume host port resources).”

**Comment by ThomasMeijers** [comment]
Fixed by ceef1f8b290de891f96d7ed981782c10243586fa.
