### ISSUE TITLE
POST /api/v1/events returns 405 response without Accept header

### ISSUE THREAD

**Issue by stuartleeks** [magneticio/vamp#995]
# Observed behaviour

If a `POST` request is made to `/api/v1/events` without an `Accept` header then the API response is

```
HTTP method not allowed, supported methods: GET
```

# Desired behaviour

In this scenario, it might be better to return the same error message as for a `GET` request to `/api/v1/events` without an `Accept` header

```
Request is missing required HTTP header 'Accept'
```

In trying to work out why my API call wasn't working, I eventually discovered that curl adds `Accept: */*` to requests!

**Comment by RaduMihut** [comment]
Could not reproduce
