### ISSUE TITLE
Path to Log outputs is wrong, resulting in not showing log outputs in UI

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#999]
Notice the double var: /var//var/
removing one fixes it.

http://admin.dev.xxx.com/service/vamp-ee/xxx-xxxx-environment/proxy/host/10.0.2.75/port/5051/files/read?offset=0&path=/var//var/lib/mesos/slave/slaves/40b03013-22aa-4ca3-b05e-1b83ca770eed-S4/frameworks/40b03013-22aa-4ca3-b05e-1b83ca770eed-0000/executors/xxx-xxx-environment_deployment-savangw-service-f6688d352a6f996f10f41a736bf661babec6a45f.e3c3e0d3-5bdb-11e7-a678-fe475b4522f6/runs/4c806306-77aa-4ab3-b0d2-bc3fb4734ee7/stderr

**Comment by jason-magnetic-io** [comment]
@olafmol can you verify that this is now fixed?

**Comment by jason-magnetic-io** [comment]
Works correctly in EE version 0.9.5-1242-g15531f8c.
